### ISSUE TITLE
[FEATURE REQUEST]: Make "parent chain" term clearer

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1008]
During translation noticed that we exessive using "parent chain" term.
For user not deep in blockchain tech such: "Right ticker parent chain balance needs to be funded" message might be very confusing (not clear what is needed to be done), and it's quite tricky to translate "Parent chain" 

I think we have to specifiy clearly everywhere like a: "need ETH balance for BAT-ERC20", "need QTUM balance for QCASH-QRC20" and so on, otherwise it might be a tricky quest for user to determine what right ticker is, what parent chain is and so on.

Examples I've noticed on simple trading view (probably applicable to other views also, would be great to remove too):
![image](https://user-images.githubusercontent.com/24797699/122957178-e03e9c00-d3ab-11eb-8835-c8f42028faf0.png)

**Comment by smk762** [comment]
Seeing at 
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/qml/Constants/General.qml#L436
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/qml/Exchange/Trade/SimpleView/Trade.qml#L624

might need a function to determine what parent chain is, if not already available.
