### ISSUE TITLE
[BUG]: Top menu is on the left side on Windows

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1010]
On OSX it's on the right side last time I've checked. It would be great to make it's appereance consistent over all platofrms.

![image](https://user-images.githubusercontent.com/24797699/122959425-424bd100-d3ad-11eb-8d44-b38f151b3dd3.png)

**Comment by Milerius** [comment]
> On OSX it's on the right side last time I've checked. It would be great to make it's appereance consistent over all platofrms.
> 
> ![image](https://user-images.githubusercontent.com/24797699/122959425-424bd100-d3ad-11eb-8d44-b38f151b3dd3.png)

It's made on purpose, it's because of the window button positioning !
