### ISSUE TITLE
[BUG]: Min volume selector is confusing

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1012]
At the moment it's not clear what dots do and there is no visual representation of min trading volume (as well as an explanation of what min volume is/using for).

I think we can make it an optional input field (with activation way similar to custom dpow protection rules) with an indicator in percents from 0%  to 100% from order amount

**Comment by Milerius** [comment]
> At the moment it's not clear what dots do and there is no visual representation of min trading volume (as well as an explanation of what min volume is/using for).
> 
> I think we can make it an optional input field (with activation way similar to custom dpow protection rules) with an indicator in percents from 0% to 100% from order amount

I think with tutorial + visualization of min_vol we can keep the double selector, it's pretty clear what it does, left side is for min_trading_amount in case your order is not matched, the right side is the current_volume.

another solution is to use 2 slider, but in general yes the min_vol is almost never use expect for advanced user so we can hide it by default and use no min_vol in the backend until user really want it

**Comment by tonymorony** [comment]
`it's pretty clear what it does,` it's clear when you see the source code/implemented it. from the usual user perspective at the moment it's two dots with some numbers above

at least there should be a checkmark "set min volume" which enabling/disabling this second dot
and indication of which dot is for what volume

**Comment by Milerius** [comment]
> `it's pretty clear what it does,` it's clear when you see the source code/implemented it. from the usual user perspective at the moment it's two dots with some numbers above
> 
> at least there should be a checkmark "set min volume" which enabling/disabling this second dot
> and indication of which dot is for what volume

Let's use single selector i think like it's was in the past should be better
