### ISSUE TITLE
[FEATURE REQUEST]: Address verification when adding an address in the addressbook

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1013]
**Is your feature request related to a problem? Please describe.**
When adding an address to a contact in the addressbook, you can enter anything in the address field it will be valid.

<img width="411" alt="Capture d’écran 2021-06-22 à 16 03 39" src="https://user-images.githubusercontent.com/14373103/122989601-496de180-d3a3-11eb-8b7c-0433c248e9a2.png">

**Comment by Milerius** [comment]
> **Is your feature request related to a problem? Please describe.**
> When adding an address to a contact in the addressbook, you can enter anything in the address field it will be valid.
> 
> <img alt="Capture d’écran 2021-06-22 à 16 03 39" width="411" src="https://user-images.githubusercontent.com/14373103/122989601-496de180-d3a3-11eb-8b7c-0433c248e9a2.png">

You can use same approach as the wallet one and use the same variables:

```cpp
Q_INVOKABLE void validate_address(QString address);
        Q_INVOKABLE void
        convert_address(QString from, QVariant to_address_format); //<https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#convertaddress
```

```
Q_PROPERTY(bool validate_address_busy READ is_validate_address_busy WRITE set_validate_address_busy NOTIFY validateAddressBusyChanged)
        Q_PROPERTY(QVariant validate_address_data READ get_validate_address_data WRITE set_validate_address_data NOTIFY validateAddressDataChanged)
        Q_PROPERTY(bool convert_address_busy READ is_convert_address_busy WRITE set_convert_address_busy NOTIFY convertAddressBusyChanged)
        Q_PROPERTY(QString converted_address READ get_converted_address WRITE set_converted_address NOTIFY convertedAddressChanged)
```
