### ISSUE TITLE
[Enhancement]: Max button and ticker not centred with amount

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1022]
![image](https://user-images.githubusercontent.com/24797699/123080827-8986a000-d447-11eb-8a05-e00a6cbb8b18.png)

max is much higher, the ticker is a bit lower

also would be great to vertically center icon on coin selectors:

<img width="121" alt="Screenshot 2021-06-23 at 17 25 05" src="https://user-images.githubusercontent.com/24797699/123081399-1e899900-d448-11eb-81ae-17825c968519.png">

filter icon not centred to label:

<img width="392" alt="Screenshot 2021-06-23 at 17 29 02" src="https://user-images.githubusercontent.com/24797699/123081867-9d7ed180-d448-11eb-9e00-33b8be05b007.png">

**Comment by SylEze** [comment]
MAX button alignment fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1026/commits/98b0f3d9249eb6bfdaf02f4e6f47ca4f1b58c4ba

**Comment by SylEze** [comment]
Center coin selectors icon in 5e04bebe132b91c4766def8fc9278123669d4606

**Comment by SylEze** [comment]
Everything should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1026
