### ISSUE TITLE
[BUG]: Not able to match order with max button using

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1031]
video:

https://user-images.githubusercontent.com/24797699/123247117-bb176e00-d510-11eb-88b6-8c068c8dad3f.mp4

log:
https://paste.ubuntu.com/p/CDztNpxRmS/

then I was able to match the order from pro view from the first attempt with max:

![image](https://user-images.githubusercontent.com/24797699/123247298-f2861a80-d510-11eb-9ffc-bb66f81769a0.png)

I've tried with other coins and it worked the same way for all tries. According to log, it looks like max `order` volume passing to mm2 instead of max taker volume (https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#my-balance)

To reproduce:

1) Select some coin to sell on a simple trading view
2) Set max amount by max button
3) Select an order which covers your max selling balance of selected coin fully
4) Try to match

**Comment by smk762** [comment]
replicated in latest dev 
```[{"error":"rpc:173] dispatcher_legacy:155] lp_ordermatch:2798] check_balance:76] Not enough VRSC for swap: available 99.82985792, required at least 1548.926441897258687258687258687258687258687258687258687258687258687258687258687258687258687258687259, locked by swaps Some(BigDecimal(\"0\"))"}]```

**Comment by Milerius** [comment]
fixed: https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/0c45e8ec8a441fb0192e58f86a44cd6d9002ecc3
