### ISSUE TITLE
Addressbook validation button misleading

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1036]
In Addressbook, the button labelled "Validate" is misleading, as it appears there is no validation occuring. Suggest change to "Save" (and delegate validation to usage in sending from wallet page), or implement validation.

https://user-images.githubusercontent.com/35845239/123257298-8f05e800-d524-11eb-925b-2c472ca43936.mp4

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1030#issuecomment-867571835_

**Comment by Milerius** [comment]
But this is again a duplication of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1013 no ?

**Comment by smk762** [comment]
yep
