### ISSUE TITLE
[BUG]: Simpleview coin selection overflow for BEP20 coins with suffix

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1038]
**Describe the bug**
Long tickers with BEP20 suffix break out of the form area. This doesn't happen when both coins are long ticker / BEP20.

**To Reproduce**
1. Go to Simple trading view
2. Select a short ticker coin to send from
3. Select a long ticker coin to send to
4. See overflow

**Expected behavior**
Shift tickers left to fit within area

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/123397062-98e72400-d5d4-11eb-8417-001dce467743.png)

From coin long ticker and To coin short ticker is ok.

![image](https://user-images.githubusercontent.com/35845239/123396615-16f6fb00-d5d4-11eb-8a04-e54d56d73917.png)
Both long tickers is ok.

![image](https://user-images.githubusercontent.com/35845239/123397267-cdf37680-d5d4-11eb-8351-073864e2a337.png)
From coin short ticker and To coin long ticker - overflow

**Comment by ssakone** [comment]
It will be hard to keep alignment, maybe if we cut ticker name and complete with dot.

**Comment by Milerius** [comment]
Why we do not have an implicit witdh based on the size of every elements... should be straightforward to fix.

**Comment by SylEze** [comment]
> Why we do not have an implicit witdh based on the size of every elements... should be straightforward to fix.

This kind of hardcoded stuff is really bad because every time we'll encounter a bigger token name we will have to fix again the size.

**Comment by SylEze** [comment]
And if we keep alignment on too long tokens, it will be too much moved to the left.

What can I suggest is to have text elusion for token whose size is higher than a 5/6 characters.

**Comment by Milerius** [comment]
> And if we keep alignment on too long tokens, it will be too much moved to the left.
> 
> What can I suggest is to have text elusion for tokens whose size is higher than a 5/6 characters.

KMD-BEP20 -> KMD (i) -> (i) -> BEP-20 (with mouse on (i))
