### ISSUE TITLE
[BUG]: Pro View Filter overflow when long tickers

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1041]
**Describe the bug**
When using the filter form on DEX Pro view, if two long tickers are selected (e.g. with BEP20 suffix), part of the form is pushed under the adjacent panel and hidden from user. 

**To Reproduce**
1. Go to Dex Pro view while app not full screen, and all panels active.
2. Click on History tab
3. Click on Filter, select two BEP20 tokens
4. See to date input disappear under adjacent panel

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/123416740-862b1a00-d5e9-11eb-91d4-ecf18396665d.png)

**Extra context**
Issue disappears if app is maximised, or "Place order" panel is hidden.

**Comment by Milerius** [comment]
@ssakone can you solve this one in #1033 please ?
