### ISSUE TITLE
[FEATURE REQUEST]: Add segwit support

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#1061]
**Is your feature request related to a problem? Please describe.**

- [x] a way to switch legacy/segwit in the wallet page 
     - [x] Property to know if the coin support segwit (segwit)
     - [x] Property to know the current format (is_segwit_on)
     - [x] Backend switch_address_mode(bool segwit)
     - [x] Backend process_switch_address_mode(tx_hex)
- [x] A modal of transaction confirmation like the send modal (with more informations etc) (before the last step) onClicked() behave differently
- [x] a bool in desktop cfg `is_segwit_on` (optional) to determine both of the above properties (proposal) 

Front-end logic:

The logic of the segwit button is quite simple (we call it `segwit.checked`):

If the user clicks to enter / exit Segwit mode:

# IN CASE THERE IS NO BALANCE
-  It has no balance and in this case the `post_switch_address_mode(!segwit.checked)` function is called with the boolean at the opposite value of the switch

## POST SWITCH STEP
   * if segwit.checked == false -> post_switch_address_mode(true)
   * if segwit.checked == true -> post_switch_address_mode(false)
   * eg: `post_switch_address_mode(!segwit.checked)`
 
 # IN CASE THERE IS A BALANCE

- User has a balance, then we open a modal and we ask the user if he want to send funds to his new address or to skip this step and directly switch to the new address mode
    * YES -> OPEN SEND MODAL WITH MAX = TRUE AND CONVERTED ADDRESS (READ ONLY FOR BOTH) USING `switch_address_mode(!segwit.checked)`
    * NO -> SEE POST_SWITCH_STEP

## WHEN THE SEND MODAL IS OPEN

- If user click on cancel, then we abort the operation and nothing change, it's like the initial state.
- If user confirm & broadcast then see POST_SWITCH_STEP

segwit.checked will always follow the backend value `current_infos.is_segwit_on` so you never need to change the value of segwit.checked

### MISC

The above change on send_modal should absolutely not impact the existing send modal behaviour

**Comment by tonymorony** [comment]
https://github.com/KomodoPlatform/atomicDEX-API/pull/1116 is merged so we can test and implement separate BTC-Legacy BTC-Segwit coins approach (coins file needs to be updated at first)

**Comment by smk762** [comment]
Closing. Segwit is now available in the app.
![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/35845239/bc7320af-b1ff-408f-ba4b-dd3322e23d2e)
