### ISSUE TITLE
[BUG]: Addressbook entries do not persist after logout

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1064]
**Describe the bug**
When adding an address to the addressbook, after logging out it is no longer visible in the addressbook

**To Reproduce**
1. Go to addressbook
2. Add a new address
3. Logout, then back in
4. Check addressbook, entry will not be there.

https://user-images.githubusercontent.com/35845239/124859700-f1f68500-dfe2-11eb-8515-8c951471773d.mp4

**Expected behavior**
Saved addresses should be visible after logout.

**Additional context**
Likely related to error in console - `[11:44:56] [warning] [main.prerequisites.hpp:126] [651526]: qrc:/atomic_defi_design/qml/Wallet/AddressBook.qml:159: TypeError: Cannot read property 'categories' of null
`

**Comment by SylEze** [comment]
After looking through addressbook files, the data is indeed correctly saved. The problem occurs at loading time.
