### ISSUE TITLE
[BUG]: No taskbar icon in Linux 

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1065]
**Describe the bug**
When launching app in Linux, there is no icon displayed in the taskbar (just an empty space)
**To Reproduce**
1. Load app
2. Look at taskbar

**Expected behavior**
Atomicdex icon should display in taskbar. 

**Screenshots**
20.04
![image](https://user-images.githubusercontent.com/35845239/124863617-fe321080-dfe9-11eb-9559-914e3f4c55f0.png)
18.04
![image](https://user-images.githubusercontent.com/35845239/124867021-f07f8980-dfef-11eb-87eb-b396e03feb3a.png)

**Desktop (please complete the following information):**
 - OS: Linux 18.04 & 20.04

**Additional context**
Possible solutions
- https://www.enovision.net/how-create-appimage-entries-menu-ubuntu
- https://github.com/TheAssassin/AppImageLauncher

**Comment by smk762** [comment]
@Milerius I tested adding `    app->setWindowIcon(QIcon("/home/smk762/.atomic_qt/logo/dex-logo.png"));` to https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/app/main.prerequisites.hpp#L430 and icon was displayed in taskbar. 

![image](https://user-images.githubusercontent.com/35845239/125182512-2c5d5d80-e241-11eb-8f0a-ab3a84ce3507.png)

If you can properly assign with path variable via `atomic_logo_path` and icon filename for app (if whitelabel etc) with this, it should solve the problem.

**Comment by Milerius** [comment]
Fixed
