### ISSUE TITLE
[BUG]: Font settings dropdown does not update clicking 'apply'; allows dingbats

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1068]
**Describe the bug**
- In Settings > User Interface, when changing the font selection dropdown, selected font does not display in retracted dropdown input. When clicking "Apply changes" button, font does update. 
- The font selection menu includes illegible fonts like Dingbats, which might leave user in state they have problem getting out of.

**To Reproduce**
1. Go to settings > user interface
2. change font selection to dingbats
3. See selection not changed in dropdown input.
4. Click "Apply changes"
4. See illegible font applied.

**Expected behavior**
- When selecting a different font, the selected value should display in the dropdown input before clicking "apply changes"
- Fonts should all be readable by user (dingbats etc should not be an option)

**Screenshots**

https://user-images.githubusercontent.com/35845239/124868883-05115100-dff3-11eb-8260-cbb02536ea0f.mp4

**Comment by ssakone** [comment]
3 Font work well and have well text display
 - Montserrat
 - Ubuntu
 - Roboto
