### ISSUE TITLE
[BUG]: Duplication in portfolio percentages

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1076]
**Describe the bug**
When you have balance in two varieties of the same coin (e.g. BTC and BTC-BEP20), these are both shown as BTC, but in separate lines

![image](https://user-images.githubusercontent.com/35845239/125238234-89c4dd80-e319-11eb-85fc-a4db093cbf3c.png)

**To Reproduce**
1. Have BTC and BTC-BEP20 balance (or other coin with more than one variety)
2. Login and go to dashboard
4. See duplication

**Expected behavior**
Two options: 
- combine both balances into one row
- or, include "BEP20" etc in label where appropriate.

**Comment by Milerius** [comment]
> **Describe the bug**
> When you have balance in two varieties of the same coin (e.g. BTC and BTC-BEP20), these are both shown as BTC, but in separate lines
> 
> ![image](https://user-images.githubusercontent.com/35845239/125238234-89c4dd80-e319-11eb-85fc-a4db093cbf3c.png)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Have BTC and BTC-BEP20 balance (or other coin with more than one variety)
> 2. Login and go to dashboard
> 3. See duplication
> 
> **Expected behavior**
> Two options:
> 
> * combine both balances into one row
> * or, include "BEP20" etc in label where appropriate.

I think we should include -BEP20
