### ISSUE TITLE
[BUG]: Not clickable icons on login page

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1078]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24797699/125278811-fef1dc00-e334-11eb-9113-49dc67291d34.png)

Not clickable blurred icons drawing on the login page (introduced in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1055), we should remove the icons from this screen or make it clickable

**Comment by ssakone** [comment]
ok
