### ISSUE TITLE
[BUG]: Font in pie diagram is reducing (up to disappear) on diagram interaction or screen scroll

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1083]
tested on latest dev, OSX
@smk762 could you please try on your side / other platforms?

https://user-images.githubusercontent.com/24797699/125377975-b62b3900-e3af-11eb-9cba-4d487f5d10bc.mp4

**Comment by smk762** [comment]
Confirm same issue on linux and win with latest dev.
