### ISSUE TITLE
[BUG]: Recover funds causing crash if mm2 response takes too long

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1087]
**Describe the bug**
When attempting to recover a failed ETH swap, mm2 is not returning a response and as a result the app freezes then crashes.

Logs show
 `13 08:18:40, eth:3295] Max nonce 24 != 23 min nonce` and 
```
[15:54:09] [warning] [main.prerequisites.hpp:126] [131544]: Qt has caught an exception thrown from an event handler. Throwing exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
```

**To Reproduce**
1. Have failed ETH swap
2. Go to swap history
3. Attempt to recover funds
4. See app freeze and then crash

**Expected behavior**
App to use async call, and fail gracefully if no timely response.
Enhancement: Spinner shown while awaiting response, with status bar or notification alerting user on completion.

**Additional context**
Could be related to "a pending transaction on one of the ETH nodes not synced up to others so they return different nonces." - @artemii235

**Comment by Milerius** [comment]
Fixed
