### ISSUE TITLE
[BUG]: Fiat volume calculating not correctly in simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1099]
Fiat volume right now calculating as if an order has full volume by this price to cover user sell volume even if it's not the case:

![Screenshot 2021-07-15 at 22 03 10](https://user-images.githubusercontent.com/24797699/125820308-f0d4b7ba-867a-462c-9792-f3b34f372882.png)

**Comment by Milerius** [comment]
> Fiat volume right now calculating as if an order has full volume by this price to cover user sell volume even if it's not the case:
> 
> ![Screenshot 2021-07-15 at 22 03 10](https://user-images.githubusercontent.com/24797699/125820308-f0d4b7ba-867a-462c-9792-f3b34f372882.png)

If we do that the whole sort will be broken and it's will became unredeable

**Comment by tonymorony** [comment]
if I remember correctly you sort by CEX rate? 
it's totally wrong information which doesn't contain any practical sense atm in the Fiat Volume column

**Comment by Milerius** [comment]
> if I remember correctly you sort by CEX rate?
> it's totally wrong information which doesn't contain any practical sense atm in the Fiat Volume column

It's not wrong - it's based on the initial wish from the user, the title of the column should be `Fiat for Rates`, in this case you may want an extra column `Fiat for available quantity`

**Comment by Milerius** [comment]
<img width="340" alt="Capture d’écran 2021-07-15 à 18 17 47" src="https://user-images.githubusercontent.com/21139416/125822203-abb325db-3f68-449f-b2a8-185b964a9ad9.png">

**Comment by Milerius** [comment]
> > > if I remember correctly you sort by CEX rate?
> > > it's totally wrong information which doesn't contain any practical sense atm in the Fiat Volume column
> > 
> > 
> > It's not wrong - it's based on the initial wish from the user, the title of the column should be `Fiat (for initial vol)`, in this case you may want an extra column `Fiat for available quantity`
> 
> what information can I get from 18.7$ number from the screenshot? it only adding confusion in this case because actually, I'll be able to get only 0.35$ when click on this order

yes but if you click on it, the volume is adjusted and you can see how much you swap too

**Comment by tonymorony** [comment]
`what information can I get from 18.7$ number from the screenshot?` it's obviously a visual bug at the moment, not sure what we discussing here at the moment and why should we keep a bug even if it's currently sorting by this columnn

**Comment by Milerius** [comment]
> `what information can I get from 18.7$ number from the screenshot?` it's obviously a visual bug at the moment, not sure what we discussing here and why should we keep a bug even if it's currently sorting by this column

Note sure which kind of information you really want here, for me the initial wish is to sell a specific amount - mm2 doesn't exclude order that partial fill the initial wish, that's good so we can see more orders - anyway should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1100

**Comment by tonymorony** [comment]
> > `what information can I get from 18.7$ number from the screenshot?` it's obviously a visual bug at the moment, not sure what we discussing here and why should we keep a bug even if it's currently sorting by this column
> 
> Note sure which kind of information we really want here, for me the initial wish is to sell a specific amount - mm2 doesn't exclude order that partial fill the initial wish, that's good so we can see more orders - anyway should be fixed in #1100

Thanks for a prompt fix! Will test with CI build

Fiat evaluation of available quantity might be helpful (available quantity * cex price), however, this info user will get after order selection so it's not a big deal

**Comment by Milerius** [comment]
> > > `what information can I get from 18.7$ number from the screenshot?` it's obviously a visual bug at the moment, not sure what we discussing here and why should we keep a bug even if it's currently sorting by this column
> > 
> > 
> > Note sure which kind of information we really want here, for me the initial wish is to sell a specific amount - mm2 doesn't exclude order that partial fill the initial wish, that's good so we can see more orders - anyway should be fixed in #1100
> 
> Thanks for a prompt fix! Will test with CI build
> 
> Fiat evaluation of available quantity might be helpful (available quantity * cex price), however, this info user will get after order selection so it's not a big deal

Yes for the moment I fixed it with using the available quantity * price (base_max_vol) of the order

**Comment by tonymorony** [comment]
ty for a prompt fix
