### ISSUE TITLE
[BUG]: Private key not shown in settings > security

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1108]
**Describe the bug**
Seed, password and address are shown but area for private key is blank.
The private key data is present though if you click the copy icon the full private key is copied to the clipboard.

**To Reproduce**
1. Go to Settings > Security
2. Click on Show button
3. Enter password
4. See list of addresses without private key

**Expected behavior**
Private key is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/126068828-734117d1-fd5e-4251-a92d-da92bae4f228.png)

**Comment by Milerius** [comment]
Fixed in #1112
