### ISSUE TITLE
[BUG]: Notification message too much on the right in notifications box

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1113]
**Describe the bug**
When opening the notifications box, message of a notification seems to be too much on the right.

<img width="407" alt="Capture d’écran 2021-07-18 à 22 53 03" src="https://user-images.githubusercontent.com/14373103/126081882-b1189ab8-5471-4985-af5a-e26e539f4c72.png">

**Expected behavior**
Realign correctly the notification message to the left

**Comment by ssakone** [comment]
should be closed.
Already fixed & merged.
