### ISSUE TITLE
[FEATURE REQUEST]: Revert all eula translated to English 

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1115]
Russian and French translations are currently missing for the EULA.

**Comment by tonymorony** [comment]
EULA shouldn't be translated to any language only if not translated/translation reviewed by a `lawyer` and there should be a legally correct disclaimer that ENG EULA is the correct one and translation is for informational purposes only

**Comment by Milerius** [comment]
> EULA shouldn't be translated to any language only if not translated/translation reviewed by a `lawyer` and there should be a legally correct disclaimer that ENG EULA is the correct one and translation is for informational purposes only

So we should remove the Turkish translation of the EULA ?

**Comment by tonymorony** [comment]
> > EULA shouldn't be translated to any language only if not translated/translation reviewed by a `lawyer` and there should be a legally correct disclaimer that ENG EULA is the correct one and translation is for informational purposes only
> 
> So we should remove the Turkish translation of the EULA ?

yep, if it's translated it's better to revert
