### ISSUE TITLE
[BUG]: Crash on MacOS (M1)

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1119]
**Describe the bug**
Caught a crash on my mac, happened on tabs switching (from the dashboard to DEX if I remember correctly)

end of app log contains crash backtrace:
[2021-07-19-01-30-29.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/6837790/2021-07-19-01-30-29.log)

` 2# QQuickWebEngineViewPrivate::~QQuickWebEngineViewPrivate() in /Applications/atomicdex-desktop.app/Contents/Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine`

maybe it was a switch from wallet to dex, that correlates with reports of crashes with white screen on place of coin graph

**Comment by Milerius** [comment]
Hmm tried to spam during 20 min on my computer the same behaviour and no crash, could you please follow https://github.com/KomodoPlatform/atomicDEX-Desktop/wiki/Build-Instructions#build-atomicdex-desktop build (in debug) with rosetta and launch the program with lldb for the next testing session ?

This way if a crash occured you can type the command `bt` i will have much more infos than the stacktrace given by boost :/

**Comment by tonymorony** [comment]
> h



> Hmm tried to spam during 20 min on my computer the same behaviour and no crash, could you please follow https://github.com/KomodoPlatform/atomicDEX-Desktop/wiki/Build-Instructions#build-atomicdex-desktop build (in debug) with rosetta and launch the program with lldb for the next testing session ?
> 
> This way if a crash occured you can type the command `bt` i will have much more infos than the stacktrace given by boost :/
> 
> According to the logs, it's crash in QtWebEngine, would also be nice to give another test session after the migration to Qt 6.

I can't reproduce it, happened just once quite randomly

**Comment by Milerius** [comment]
> > h
> 
> > Hmm tried to spam during 20 min on my computer the same behaviour and no crash, could you please follow https://github.com/KomodoPlatform/atomicDEX-Desktop/wiki/Build-Instructions#build-atomicdex-desktop build (in debug) with rosetta and launch the program with lldb for the next testing session ?
> > This way if a crash occured you can type the command `bt` i will have much more infos than the stacktrace given by boost :/
> > According to the logs, it's crash in QtWebEngine, would also be nice to give another test session after the migration to Qt 6.
> 
> I can't reproduce it, happened just once quite randomly

Yeah i understand it's quite hard to reproduce, but it's will be easier if you have a debug build for this kind of purpose so in case of this random crash happen we can still catch it using lldb + bt
