### ISSUE TITLE
[FEATURE REQUEST]: Simple trading view no orders UX handling

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1120]
**Is your feature request related to a problem? Please describe.**
At the moment if there are no orders for the user's Sell selection app displaying an empty screen what might be quite confusing

![Screenshot 2021-07-19 at 10 10 49](https://user-images.githubusercontent.com/24797699/126101737-14d8480a-337b-4498-8f8b-bd27e8bcc97c.png)

**Describe the solution you'd like**
Show text label in the middle of buy orders list e.g. "No buy orders found for BTC. You can check later or try to sell a different coin."

**Describe alternatives you've considered**
We can also invite to place maker order in pro view

**Comment by Milerius** [comment]
> **Is your feature request related to a problem? Please describe.**
> At the moment if there are no orders for the user's Sell selection app displaying an empty screen what might be quite confusing
> 
> ![Screenshot 2021-07-19 at 10 10 49](https://user-images.githubusercontent.com/24797699/126101737-14d8480a-337b-4498-8f8b-bd27e8bcc97c.png)
> 
> **Describe the solution you'd like**
> Show text label in the middle of buy orders list e.g. "No buy orders found for BTC. You can check later or try to sell a different coin."
> 
> **Describe alternatives you've considered**
> We can also invite to place maker order in pro view

Here this should be another bug, in this case for this amount of BTC it's should show that you do not have the minimum trading amount of 0.0777 BTC ( i think the minimum trading amount is still this amount for BTC)

**Comment by tonymorony** [comment]
> Here this should be another bug, in this case for this amount of BTC it's should show that you do not have the minimum trading amount of 0.0777 BTC ( i think the minimum trading amount is still this amount for BTC)

true that, opened another issue https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1121
