### ISSUE TITLE
[BUG]: Incoherent cursor type in settings modal

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1122]
In settings modal, the displayed cursor type when hovering "SEARCH UPDATE" or "LOGOUT" buttons is incoherent.

Cursor is of "idle" type on buttons text but should be "clickable" type.

**Comment by ssakone** [comment]
should be close.

**Comment by ssakone** [comment]
> should be close.

already fixed & merged.
