### ISSUE TITLE
[BUG]: Filter applied to swap history overriding "orders" filter

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1136]
**Describe the bug**
Filtering applied to the History tab are also applied to the Orders tab. Setting filter to default (all/all) on Orders tab does not show orders in progress (unless they are matching History filter params). Issue affects both pro and simple views.

**To Reproduce**
1. Start an atomic swap
2. Go to history tab, and apply a filter that would not match the swap you just started
3. Go back to Orders tab
4. See order not displayed
5. Try and set Orders tab filter so it would match order in progress
6. See order stil not displayed

**Expected behavior**
Filtering should only be applied to the table within the tab it is in.

https://user-images.githubusercontent.com/35845239/126734742-c47fc499-9c83-4ba6-99f9-a5c0a90dc2f7.mp4

https://user-images.githubusercontent.com/35845239/126734748-a1c166e7-9b36-467c-bf6d-c560bb92ab4c.mp4

**Comment by Milerius** [comment]
> **Describe the bug**
> Filtering applied to the History tab are also applied to the Orders tab. Setting filter to default (all/all) on Orders tab does not show orders in progress (unless they are matching History filter params). Issue affects both pro and simple views.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start an atomic swap
> 2. Go to history tab, and apply a filter that would not match the swap you just started
> 3. Go back to Orders tab
> 4. See order not displayed
> 5. Try and set Orders tab filter so it would match order in progress
> 6. See order stil not displayed
> 
> **Expected behavior**
> Filtering should only be applied to the table within the tab it is in.
> 
>  filter-bleed.mp4 
>  filter-bleed-pro.mp4

Filtering should be reset on such click as it was before please @ssakone or @SylEze let's check and fix asap.
