### ISSUE TITLE
[FEATURE REQUEST]: Add additional warning if user wants to select "Allow custom seed"

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1138]
With confirmation like a:
![image](https://user-images.githubusercontent.com/24797699/126757656-bbf6a637-a5de-40d9-bd1c-47b7c87e67ff.png)

The text of modal is something like a (that might be a bit sharp/scary wording, @smk762 would be great if you advise on that):

```
I know what I'm doing and do understand that seed phrases should be secure enough (12+ words or enough entropy, e.g. WIF format). Otherwise, the seed might be brute-forced and the evil party will grant access to my funds. Type "I understand" to proceed."
```

**Comment by smk762** [comment]
"Custom seeds might be less secure and easier to crack than a generated BIP39 compliant seed. To confirm you understand this and know what you are doing, type 'I understand' in the box below."

**Comment by ssakone** [comment]
![image](https://user-images.githubusercontent.com/39985611/126771525-ad8c450f-1691-4cd7-9cb6-0583965a1de5.png)
i add border color in dialog manager

**Comment by Milerius** [comment]
> ![image](https://user-images.githubusercontent.com/39985611/126771525-ad8c450f-1691-4cd7-9cb6-0583965a1de5.png)
> i add border color in dialog manager

I think you may want something different than the dialog manager for this one since you need input verification, but that looks nice otherwise

**Comment by ssakone** [comment]
![image](https://user-images.githubusercontent.com/39985611/126773803-56885e3d-de47-485a-b3b9-e505c60ceb77.png)
