### ISSUE TITLE
[BUG]: Unknown error in address validation

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1150]
**Describe the bug**
Entering a GLEEC-OLD address for GLEEC (smartchain) returns "unknown error"

**To Reproduce**
1. Go to GLEEC wallet
2. Try to send funds to `FEMqAugC5U7atqDuV8s9EBEuCKJb2UGb3p`
3. See error

**Expected behavior**
Should return "GLEEC address is invalid"

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/127423875-c2ce97b8-2a3c-4dc9-8fd3-0f57aaeb76f6.png)
![image](https://user-images.githubusercontent.com/35845239/127424349-dd510657-deac-4df2-956b-d27dc68cd56b.png)

**Additional context**
removing one char = "GLEEC address is invalid"
changing last char = "Invalid checksum"

As the address is valid (just not for smartchains), it does not fail the checksum test. 
A similar error appears when entering a smartchain address for GLEEC-OLD

**Comment by Milerius** [comment]
@smk762 do you mind to test in CLI and let us know how react mm2 in this case ?

**Comment by smk762** [comment]
`{"result":{"is_valid":false,"reason":"utxo_common:1493] Address FNX7LtPxdutGkeLYhBybRixJ7FFZAhyBkp has invalid prefixes"}}
`
