### ISSUE TITLE
[BUG]: Coin list filter by search not reset when leaving the dashboard

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1157]
https://drive.google.com/file/d/19We3cmFiP5kBS5ZH7vIXFVHoSmo4GF6d/view

Searching in dashboard and dex page coin list should be independent, thus after searching on one page, the search filter should be reset.

**Comment by tonymorony** [comment]
@SylEze, unfortunately, this one is actual rn in opposite way: if I enable the filter on the wallet page it works for the dashboard, and since input in search on the dashboard page is empty users have no clue what happened

https://user-images.githubusercontent.com/24797699/130515356-63e743de-8ab7-439f-be85-a065144d91f3.mov

**Comment by SylEze** [comment]
> @SylEze, unfortunately, this one is actual rn in opposite way: if I enable the filter on the wallet page it works for the dashboard, and since input in search on the dashboard page is empty users have no clue what happened
> Screen.Recording.2021-08-24.at.03.31.08.mov

Sorry for the inconvenience, take a look at 665dfdd96d980f4ea86a450db8867fd39f20f8c6
