### ISSUE TITLE
[FEATURE REQUEST]: Light mode tweaks

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1158]
- Common button state colors (disabled/enabled/hover). At the moment, the "Add Asset" button on the dashboard, and the "New Contact" button on the Addressbook do not align with the buttons on the wallet page, or buttons within the add address panels.

- "accentColor" currently applies to the default state of the "New Contact" and " Add Asset" buttons, but also some text such as balance in title bar and within the dex page (also the outlines in settings). Also used when hovering over dropdowns in pro mode, and for the privacy toggle (and other toggles). The text elements should be separated so the buttons, text, dropdown highlight can be set to a different color flag. Highlit in purple below.
![image](https://user-images.githubusercontent.com/35845239/127874067-d7f437a0-de3e-4281-aeaf-ce13abb4b8b1.png)

- Fiat / Coming soon tooltips from sidebar are different text color. Why are there two tooltips?
- `hightlightColor` should be `highlightColor` (spelling)
- Unsure what/why there is a gap between sidebar and submenu
![image](https://user-images.githubusercontent.com/35845239/127878417-c4ae4393-da60-4826-86c3-6802dc387943.png)

- Dashboard coin rows hover effect broken in light mode for every second line.

- Portfolio balance text is too obscured (with and without hover). I'm not sure if there are flags for this in the json?
![image](https://user-images.githubusercontent.com/35845239/127879962-60dca0cf-470b-4939-98cb-f029464d5349.png)

- also unable to find flag for changing the green and red in transaction history (green looks like also used for copy button and in other places.
![image](https://user-images.githubusercontent.com/35845239/127881150-4baf01b5-a759-4f42-9596-66fb9f2f8ce3.png)

- Addressbook also seems to be missing flags to define colors, and hard to read with white on off-white
![image](https://user-images.githubusercontent.com/35845239/127881487-c4f7ed0b-361a-4230-afcf-338723da0e3d.png)

![image](https://user-images.githubusercontent.com/35845239/127881450-7406e691-0a28-4565-9553-5b4d829ca3f3.png)

Attached an alt-light theme, might be some colors in it worth trying. Some subtle greys to reduce eye strain (vs brighter whites), a less dark green for dex bars, shades of blue for buttons.

[smk_light.zip](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/6917781/smk_light.zip)

Within this, I tagged flags I couldn't find where they were being used with `#000001`. Are they obsolete?

**Comment by tonymorony** [comment]
thank you for the report @smk762 
blocker for https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1125

**Comment by ssakone** [comment]
@smk762 
all json property possible
```qml
property string theme: "dark"

    property color accentColor: Style.colorTheme4
    property color backgroundColor: Style.colorTheme7
    property color foregroundColor: Style.colorText


    property color backgroundLightColor0: backgroundColor
    property color backgroundLightColor1: Qt.darker(backgroundColor, 0.9)
    property color backgroundLightColor2: Qt.darker(backgroundColor, 0.8)
    property color backgroundLightColor3: Qt.darker(backgroundColor, 0.7)
    property color backgroundLightColor4: Qt.darker(backgroundColor, 0.6)
    property color backgroundLightColor5: Qt.darker(backgroundColor, 0.5)

    property color backgroundDarkColor0: backgroundColor
    property color backgroundDarkColor1: Qt.lighter(backgroundColor, 0.9)
    property color backgroundDarkColor2: Qt.lighter(backgroundColor, 0.8)
    property color backgroundDarkColor3: Qt.lighter(backgroundColor, 0.7)
    property color backgroundDarkColor4: Qt.lighter(backgroundColor, 0.6)
    property color backgroundDarkColor5: Qt.lighter(backgroundColor, 0.5)
    property color backgroundDarkColor6: Qt.lighter(backgroundColor, 0.4)
    property color backgroundDarkColor7: Qt.lighter(backgroundColor, 0.3)
    property color backgroundDarkColor8: Qt.lighter(backgroundColor, 0.2)
    property color backgroundDarkColor9: Qt.lighter(backgroundColor, 0.1)

    property color accentLightColor0: accentColor
    property color accentLightColor1: Qt.darker(accentColor, 0.9)
    property color accentLightColor2: Qt.darker(accentColor, 0.8)
    property color accentLightColor3: Qt.darker(accentColor, 0.7)
    property color accentLightColor4: Qt.darker(accentColor, 0.6)
    property color accentLightColor5: Qt.darker(accentColor, 0.5)

    property color accentDarkColor0: accentColor
    property color accentDarkColor1: Qt.lighter(accentColor, 0.9)
    property color accentDarkColor2: Qt.lighter(accentColor, 0.8)
    property color accentDarkColor3: Qt.lighter(accentColor, 0.7)
    property color accentDarkColor4: Qt.lighter(accentColor, 0.6)
    property color accentDarkColor5: Qt.lighter(accentColor, 0.5)
    property color accentDarkColor6: Qt.lighter(accentColor, 0.4)
    property color accentDarkColor7: Qt.lighter(accentColor, 0.3)
    property color accentDarkColor8: Qt.lighter(accentColor, 0.2)
    property color accentDarkColor9: Qt.lighter(accentColor, 0.1)

    property color primaryColorLightColor0: primaryColor
    property color primaryColorLightColor1: Qt.darker(primaryColor, 0.9)
    property color primaryColorLightColor2: Qt.darker(primaryColor, 0.8)
    property color primaryColorLightColor3: Qt.darker(primaryColor, 0.7)
    property color primaryColorLightColor4: Qt.darker(primaryColor, 0.6)
    property color primaryColorLightColor5: Qt.darker(primaryColor, 0.5)

    property color primaryColorDarkColor0: primaryColor
    property color primaryColorDarkColor1: Qt.lighter(primaryColor, 0.9)
    property color primaryColorDarkColor2: Qt.lighter(primaryColor, 0.8)
    property color primaryColorDarkColor3: Qt.lighter(primaryColor, 0.7)
    property color primaryColorDarkColor4: Qt.lighter(primaryColor, 0.6)
    property color primaryColorDarkColor5: Qt.lighter(primaryColor, 0.5)
    property color primaryColorDarkColor6: Qt.lighter(primaryColor, 0.4)
    property color primaryColorDarkColor7: Qt.lighter(primaryColor, 0.3)
    property color primaryColorDarkColor8: Qt.lighter(primaryColor, 0.2)
    property color primaryColorDarkColor9: Qt.lighter(primaryColor, 0.1)

    property color foregroundColorLightColor0: foregroundColor
    property color foregroundColorLightColor1: Qt.darker(foregroundColor, 0.9)
    property color foregroundColorLightColor2: Qt.darker(foregroundColor, 0.8)
    property color foregroundColorLightColor3: Qt.darker(foregroundColor, 0.7)
    property color foregroundColorLightColor4: Qt.darker(foregroundColor, 0.6)
    property color foregroundColorLightColor5: Qt.darker(foregroundColor, 0.5)

    property color foregroundColorDarkColor0: foregroundColor
    property color foregroundColorDarkColor1: Qt.lighter(foregroundColor, 0.9)
    property color foregroundColorDarkColor2: Qt.lighter(foregroundColor, 0.8)
    property color foregroundColorDarkColor3: Qt.lighter(foregroundColor, 0.7)
    property color foregroundColorDarkColor4: Qt.lighter(foregroundColor, 0.6)
    property color foregroundColorDarkColor5: Qt.lighter(foregroundColor, 0.5)
    property color foregroundColorDarkColor6: Qt.lighter(foregroundColor, 0.4)
    property color foregroundColorDarkColor7: Qt.lighter(foregroundColor, 0.3)
    property color foregroundColorDarkColor8: Qt.lighter(foregroundColor, 0.2)
    property color foregroundColorDarkColor9: Qt.lighter(foregroundColor, 0.1)


 // Old Theme
    property string chartTheme: Style.dark_theme ? "dark" : "light"
    property color primaryColor: "#171A2C"
    property color surfaceColor: backgroundDarkColor2
    property color backgroundColorDeep: backgroundDarkColor2
    property color dexBoxBackgroundColor: backgroundDarkColor6//Style.colorTheme9

    property color hightlightColor: accentDarkColor3
    property color hoverColor: accentDarkColor4

    property int sidebarShadowRadius: 32

    property color sideBarGradient1: DexTheme.primaryColorDarkColor8
    property color sideBarGradient2: DexTheme.primaryColorDarkColor4
    property real sideBarAnimationDuration: Style.animationDuration

    property color navigationSideBarButtonGradient1: DexTheme.accentLightColor2
    property color navigationSideBarButtonGradient2: DexTheme.accentLightColor1
    property color navigationSideBarButtonGradient3: DexTheme.accentDarkColor2
    property color navigationSideBarButtonGradient4: Style.colorSidebarHighlightGradient4

    property color chartTradingLineColor: Style.colorTrendingLine
    property color chartTradingLineBackgroundColor: Style.colorTrendingUnderLine
    property color lineChartColor: accentColor
    property color chartGridLineColor: Qt.rgba(255,255,255,0.4)

    

    // Button
    property color buttonColorDisabled: DexTheme.accentDarkColor5
    property color buttonColorHovered: DexTheme.accentLightColor4
    property color buttonColorPressed: DexTheme.accentDarkColor4
    property color buttonColorEnabled: DexTheme.accentLightColor2
    property color buttonColorTextDisabled: DexTheme.backgroundDarkColor7
    property color buttonColorTextHovered: DexTheme.backgroundDarkColor8
    property color buttonColorTextEnabled: DexTheme.backgroundDarkColor9
    property color buttonColorTextPressed: DexTheme.backgroundDarkColor0




    property color colorInnerShadowBottom: Style.colorRectangleBorderGradient1
    property color colorInnerShadowTop: Style.colorRectangleBorderGradient2

    property color colorSidebarDropShadow: Style.colorSidebarDropShadow

    property color barColor: Style.colorTheme5

    property color colorLineGradient1: Style.colorLineGradient1
    property color colorLineGradient2: Style.colorLineGradient2
    property color colorLineGradient3: Style.colorLineGradient3
    property color colorLineGradient4: Style.colorLineGradient4

    property color floatShadow1: Style.colorDropShadowLight
    property color floatShadow2: Style.colorDropShadowLight2
    property color floatBoxShadowDark: Style.colorDropShadowDark

    property color textSelectionColor: Style.colorSelection
    property color textPlaceHolderColor: Style.colorPlaceholderText
    property color textSelectedColor: Style.colorSelectedText
    property color innerShadowColor: Style.colorInnerShadow

    property color whiteblack: Style.colorWhite1
    property color colorThemeDarkLight: Style.colorThemeDarkLight

    property color rectangleBorderColor: DexTheme.backgroundDarkColor2

    property color colorScrollbarGradient1: Style.colorScrollbarGradient1
    property color colorScrollbarGradient2: Style.colorScrollbarGradient2

    property color greenColor: Style.colorGreen
    property color redColor: Style.colorRed

    // Widget settings 

    property int rectangleRadius: Style.rectangleCornerRadius

    // Other Data

    property string bigSidebarLogo: "dex-logo-sidebar.png"
    property string smallSidebarLogo: "dex-logo.png"
```

**Comment by ssakone** [comment]
@smk762 for accentColor applied to multiple element, i change, but defaultly some qml component applie accent color automaticaly to some widget (Material design guideline) Slider, Switch, CheckBox, Navigation Tab,

so now i just create new property `headTextColor` for different important text, like box head title, balance

**Comment by ssakone** [comment]
@smk762  you want also ItemBox icon color different by accent, you want property for that too?

**Comment by smk762** [comment]
As much as practical, if most components etc have a property it would be good, or a shared property for group etc so consistent. 
Can you pls add screenshot of the itembox icon so I am sure which component you mean?

**Comment by ssakone** [comment]
![image](https://user-images.githubusercontent.com/39985611/128170813-76a71faf-65bb-44fc-9e03-cd6121c98441.png)

**Comment by ssakone** [comment]
![image](https://user-images.githubusercontent.com/39985611/128173323-6a115a9a-9b9c-4d8c-a13a-f4fc70511203.png)

```qml
property bool walletSidebarShadowVisibility: true
 property color walletSidebarLeftBorderColor: backgroundColorDeep

```

**Comment by smk762** [comment]
![image](https://user-images.githubusercontent.com/35845239/128295586-a357392d-af36-425c-b4e0-991ef209665f.png)
[] Icon text not visible
[] user icon next to wallet name not visible
[] import / new wallet text bad contrast.
[] border around language dropdown would be better a lighter shade of grey

![image](https://user-images.githubusercontent.com/35845239/128295783-eaa6dddb-5d01-43ba-832c-28d858f1d3d0.png)
[] "Connect" text when disabled could be tiny bit darker
[] wallet name above input field had bad contrast, could be a little bigger.

![image](https://user-images.githubusercontent.com/35845239/128296033-53bc0a14-9dac-4b5f-9b81-f137f4c857a6.png)
[] logging in logo text not visible

![image](https://user-images.githubusercontent.com/35845239/128296194-1a97b186-6d08-4171-a39a-429f2fff8847.png)
[] pie chart slice on hover should not be so similar to the background (white is fine in dark mode, but not lite mode)
[] portfolio bars should be a little darker shade of grey

![image](https://user-images.githubusercontent.com/35845239/128296399-45f60894-c773-45a7-bf89-752b96aafecc.png)
[] selected wallet highlight in submenu is too subtle, darker shade of grey would be better
[] remove the grey line between the sidebar and coins submenu

![image](https://user-images.githubusercontent.com/35845239/128296696-7297cfcf-19ed-44d1-b768-fd4526171dd6.png)
[] shade when hovering over coin in submenu is nice, but text remains dark, might be better if hover changes text to lighter shade so better contrast.
[] tooltip positioning would be better to the right, not above (tooltip is covering coin above hover).

![image](https://user-images.githubusercontent.com/35845239/128297327-e8d3e8f7-6bbb-4675-9bae-e696453dd8d4.png)
[] 24hr % change needs to be darker



https://user-images.githubusercontent.com/35845239/128296937-d0e3ed6c-d8c3-4e14-887a-c87665da95b0.mp4
https://user-images.githubusercontent.com/35845239/128297003-bcceb4ea-638e-498f-b7b1-21970e0e444c.mp4
Hover effects are a bit buggy.
[] cant see hover in simple mode menus
[] hover in tx history seems to be only active inbetween rows, and effecting 2 at a time
[] hover in dashboard coins table only works on every second line

![image](https://user-images.githubusercontent.com/35845239/128297606-7c6b5e8a-6d62-4de3-8b04-cd7014e45a59.png)
[] default input text  is too light
[] not enough contrast for magnifying glass icon

Addressbook needs more attention
![image](https://user-images.githubusercontent.com/35845239/128297737-798ad181-2107-4ceb-9590-b3698b1b66e2.png)
[] invisible text in wallet type category selection

![image](https://user-images.githubusercontent.com/35845239/128297874-104eb8e9-c065-4ee0-8606-df8fec78636e.png)
[] address text is invisible if not highlighted
[] type / key are bad contrast when highlighted
[] tags being yellow look a bit inconsistent with rest of theme

**Comment by ssakone** [comment]
@smk762  i update little your theme json, its nice
```qml
{
    "accentColor": "#92b5cf",
    "backgroundColor": "#dddddd",
    "backgroundColorDeep": "#f0f0f0",
    "barColor": "#00001",
    "bigSidebarLogo": "dex-logo-sidebar-dark.png",
    "buttonColorDisabled": "#e3f2fd",
    "buttonColorEnabled": "#b6d0e3",
    "buttonColorHovered": "#92b5cf",
    "buttonColorTextDisabled": "#777777",
    "buttonColorTextEnabled": "#405366",
    "buttonColorTextHovered": "#405366",
    "chartTheme": "light",
    "chartGridLineColor":"#000001",
    "chartTradingLineBackgroundColor": "#e3f2fd",
    "chartTradingLineColor": "#37a6ef",
    "colorInnerShadowBottom": "#dddddd",
    "colorInnerShadowTop": "#efefef",
    "colorLineGradient1": "#eef1f7",
    "colorLineGradient2": "#dce1e8",
    "colorLineGradient3": "#eef1f7",
    "colorLineGradient4": "#dce1e8",
    "colorSidebarDropShadow": "#a1b2cb",
    "colorThemeDarkLight": "#000001",
    "dexBoxBackgroundColor": "#f9f9fb",
    "floatBoxShadowDark": "#becde2",
    "floatShadow1": "#21ffffff",
    "floatShadow2": "#60ffffff",
    "foregroundColor": "#232b33",
    "hightlightColor": "#b6d0e3",
    "innerShadowColor": "#becde2",
    "navigationSideBarButtonGradient1": "#8b95ed",
    "navigationSideBarButtonGradient2": "#ad7faaf0",
    "navigationSideBarButtonGradient3": "#a06dc9f3",
    "navigationSideBarButtonGradient4": "#006bcef4",
    "primaryColor": "#000001",
    "greenColor": "#00ac52",
    "redColor": "#9a1165",
    "sideBarGradient1": "#eeeeee",
    "sideBarGradient2": "#cccccc",
    "smallSidebarLogo": "dex-logo.png",
    "surfaceColor": "#ededed",
    "textPlaceHolderColor": "#5f6777",
    "textSelectedColor": "#202040",
    "textSelectionColor": "#14bca6",
    "whiteblack": "#222222",
    "walletSidebarLeftBorderColor": "transparent",
    "walletSidebarShadowVisibility": false,
    "headTextColor": "#4c7ca1"
}
```

**Comment by ssakone** [comment]
![image](https://user-images.githubusercontent.com/39985611/128456043-06c55b34-6d5e-42f8-914c-2f467672d9b4.png)

**Comment by smk762** [comment]
50 shades of grey = sexy :p

**Comment by tonymorony** [comment]
Thanks for the progress! It's definitely a great idea to use some grey for contrast. I think we should try the lighter color in a zone marked as 1, to keep some grey contrast only on blocks with information. Probably not popular opinion, but my first impression was is that it's kinda dirt / dirty white t-shirt association (too much grey):

<img width="1028" alt="Screenshot 2021-08-06 at 13 53 43" src="https://user-images.githubusercontent.com/24797699/128469052-5a23bb19-430b-4cea-aff6-570d67c40244.png">

On Monday I'll be able to consult with the designer for optimal shades of total sexiness

**Comment by tonymorony** [comment]
<img width="155" alt="Screenshot 2021-08-09 at 15 43 17" src="https://user-images.githubusercontent.com/24797699/128680524-1093b3b9-9e14-4c07-8038-d4c73c1ea837.png">
