### ISSUE TITLE
SLP tokens integration.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/atomicDEX-Desktop#1168]
Coins PR with corresponding configs: https://github.com/KomodoPlatform/coins/pull/298
MM2 branch: https://github.com/KomodoPlatform/atomicDEX-API/tree/mm2.1-slp-swap
Activation commands examples are in this diff: https://github.com/KomodoPlatform/atomicDEX-API/commit/b9a4c28ca77a1458012d72f49262418a969d11f1

Important notes:
1. Tx history is not implemented for SLP tokens yet. Enable request will return an error if it contains `tx_history:true`.
2. The platform coin (tBCH) must be activated before the SLP tokens enabling attempt. If tBCH is not activated MM2 will return an error.
3. Please ensure that tBCH has `BCH` protocol type as per https://github.com/KomodoPlatform/coins/pull/298/files#diff-62f014cb316258f89133bb263f1fa74f85b308430765a403fbc87e20b367c959R5620. If it doesn't MM2 may burn SLP tokens belonging to the users' address.

**Comment by artemii235** [comment]
PS. tBCH explorer with SLP support: https://explorer.bitcoin.com/tbch.

**Comment by artemii235** [comment]
@Milerius Could you please also add an sTST token deployed by @damascene? https://github.com/KomodoPlatform/coins/commit/1d5daca58c5d4f39d654aa3f278a1b826e05a0cf

**Comment by artemii235** [comment]
The implementation on the API side is complete finally and merged to the dev branch.
As of now, BCH and SLP require the coins file from https://github.com/KomodoPlatform/coins/tree/bch-slp-mainnet-TEST-ONLY.

There are new RPC 2.0 calls needed to integrate into GUIs:
1. `enable_bch_with_tokens` -  for initial BCH coin activation with a bunch of SLP tokens at the same time.
2. `enable_slp` - to activate additional SLP tokens after `enable_bch_with_tokens` is made.
3. `my_tx_history` - to get BCH or SLP history.

Docs are not ready yet, but there are examples in the https://github.com/KomodoPlatform/developer-docs/issues/343.
Please note that these RPCs are not considered *stable* yet so they might be changed *without prior notice*.

**Comment by tonymorony** [comment]
@artemii235 we plan to complete integration into desktop GUI during this sprint (during August)

is any information in initial post needs to be actualised? (besides the fact that `mm2.1` branch API can be used now)

**Comment by smk762** [comment]
> PS. tBCH explorer with SLP support: https://explorer.bitcoin.com/tbch.

This link seems to not point to tBCH explorer anymore. We can use https://tbch.loping.net/ as an alternative.

**Comment by smk762** [comment]
@artemii235 while scanning over @Milerius earlier work I see https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1176/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR95 
`configure_file(${arrr-cache-db_SOURCE_DIR}/ARRR_CACHE.db ${CMAKE_CURRENT_SOURCE_DIR}/assets/tools/mm2/ARRR_CACHE.db COPYONLY)`

It is commented out, but is it possible to "pre-load" for users to reduce sync? Are there any potential issues with doing this?
