### ISSUE TITLE
[BUG]: scrollbar overlapping 

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1170]
**Describe the bug**
In wallet coin menu, the scrollbar appears above background

**To Reproduce**
1. Go to wallet page with enough coins activated to need a scrollbar
2. Look at the scrollbar

**Expected behavior**
Scrollbar does not overlap text / background  should be alongside the data being scrolled, not above it.

**Screenshots**
![image](https://user-images.githubusercontent.com/35845239/128686574-197b5922-c8a5-476c-91b0-2735d6226a32.png)

**Additional context**
Reviewing other areas using scrollbar, it appears a number of different approaches have been implemented. 
Previously the scrollbar was over the portfolio percentages (next to the pie chart) - in latest build, there is no scrollbar.
In most places, the scrollbar gutter has been removed (this is ok), but in FAQ it still exists, and is offset from the scrollbar

![image](https://user-images.githubusercontent.com/35845239/128687347-6269e35f-4ce3-4bd5-9284-fbf7693031f2.png)
![image](https://user-images.githubusercontent.com/35845239/128687428-4439619a-3cd1-464e-a578-02ba78fc529e.png)

**Comment by smk762** [comment]
The offset is also present in the "view private keys" panel with a secondary scrollbar also present for some reason.

https://user-images.githubusercontent.com/35845239/128688450-50be187b-a808-49be-b822-970ed5fa6c9c.mp4

**Comment by ssakone** [comment]
@smk762  @tonymorony  need review
