### ISSUE TITLE
[BUG]: Filter coin selection hides selected coin

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1171]
**Describe the bug**
When selecting a coin for filtering history in PRO mode, some return `...` once selected. Strangely this applies more to short tickers than long ones.

**To Reproduce**
1. DEX pro view
2. Go to history tab
3. Select a few different coins
4. See how they are displayed

**Expected behavior**
Selected coin tickers should always be visible.

**Screenshots**

https://user-images.githubusercontent.com/35845239/128687857-97076ad6-dab2-4c3f-af29-1f87269202d1.mp4

**Comment by Milerius** [comment]
They just seems hidden because of the wrap text mode, could you please check @ssakone ?

**Comment by Milerius** [comment]
@SylEze if you can handle this one it's cool
