### ISSUE TITLE
[FEATURE REQUEST]: NVC Token (BSC) Integration

### ISSUE THREAD

**Issue by WikiMin3R** [KomodoPlatform/atomicDEX-Desktop#1177]
**Is your feature request related to a problem? Please describe.**
The feature is related to expanding existing NVC coin / token swaps. We are transitioning NVC project to multi-platform (UTXO + BEP20 + Others). Would like to add BEP20 token as the first phase of this transition (UTXO already in ADEX).

**Describe the solution you'd like**
Please add NVC-BEP20 token to be available for swaps on the BSC chain.

**Additional context**
Required BEP20 NVC token code:

{
                "coin": "NVC-BEP20",
                "name": "nvc_bep20",
                "fname": "Novacoin",
                "rpcport": 80,
                "mm2": 1,
                "chain_id": 56,
                "avg_blocktime": 0.05,
                "required_confirmations": 3,
                "protocol": {
                        "type": "ERC20",
                        "protocol_data": {
                                "platform": "BNB",
                                "contract_address": "0xBF84720097de111A80f46f9D077643967042841A"
                        }
                }
        },

**Comment by cipig** [comment]
added in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1178
