### ISSUE TITLE
[FEATURE REQUEST]: Adding Custom SLP tokens

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1190]
**Is your feature request related to a problem? Please describe.**
Similar to how we can add ERC20 etc, it would be nice to do with SLP also

**Additional context**
A searchable index is available here - https://simpleledger.info/
User can search for token, then input the token ID hash like https://simpleledger.info/token/a5a459d56f2f623f3f80eb31e0732c42ecd1bd7126c2a7ac17d2fbc2a40263d7

Internally, an API which returns info in json is also available for a given token ID
e.g. https://rest.bch.actorforth.org/v2/slp/list/a5a459d56f2f623f3f80eb31e0732c42ecd1bd7126c2a7ac17d2fbc2a40263d7

**Comment by damascene** [comment]
Any progress on this? Adding this may encourage many people to experiment with SLP tokens trading as it doesn't currently have any non working custodial exchange that I'm aware of.

**Comment by smk762** [comment]
closing, transfered to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1879
