### ISSUE TITLE
[BUG]: Batch enable sometimes fails to include parent chains in app

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1192]
**Describe the bug**
After enabling a large amount of coins, I've gotten into a state where BNB is not listed in my dashboard, but when attempting to enable it again I get an "already enabled" error.

**To Reproduce**
1. Reset assets config
2. Enable lots of coins (including BNB / ETH )
3. Check if BNB and ETH were actually enabled. If not, try and enable them again.

**Expected behavior**
Ideally parent chains are given priority in batch enable, or are enabled before the batch.

**Additional context**
Alternatively
- parent chains could be added to the "enabled by default" list.
- or when user attempts to enable a coin which returns an "already enabled" error, check if coin is listed within app as expected or not.

**Comment by Milerius** [comment]
should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1176 please test on this branch

**Comment by smk762** [comment]
issue no longer present in current dev
