### ISSUE TITLE
[THEME TWEAKS]: Lite mode Dashboard screen

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1198]
Default pie arc color (when first going to dashboard screen from another screen) is not the same as the bar color to the left.
If you mouseover the arcm then mouseoff, the bar and arc are same color. 
Color also resets to mismatching default if balance changes (e.g. swap ends) or after a while if doing nothing (periodic redraw?)
(FIXED) :heavy_check_mark: 

https://user-images.githubusercontent.com/35845239/130035900-b4d455eb-b5ec-4c54-b67e-767ab2577a41.mp4

Green text and line need to be darker 
![image](https://user-images.githubusercontent.com/35845239/130036536-032bc5b1-d39b-43c0-ad07-4a799cfea22b.png)
(SEMIFIXED) Text is now darker, but there is no line? :white_check_mark:

**Comment by smk762** [comment]
Some slight dancing on toggle if number changes
https://user-images.githubusercontent.com/35845239/130036818-234dc415-679f-4693-a516-40152ac716b2.mp4

**Comment by tonymorony** [comment]
> Green text and line need to be darker

ref with visible green:

https://coingecko.com/en

![image](https://user-images.githubusercontent.com/24797699/130055114-e20be1e1-19c5-4750-a19e-36826d2ddbf1.png)

**Comment by tonymorony** [comment]
![Screenshot 2021-08-20 at 14 24 55](https://user-images.githubusercontent.com/24797699/130196415-24bb2fd7-0115-495c-8bf5-4bebfc9d6ac0.png)

@ssakone just noticed that notifications checkmarks aren't visible

**Comment by smk762** [comment]
> ![Screenshot 2021-08-20 at 14 24 55](https://user-images.githubusercontent.com/24797699/130196415-24bb2fd7-0115-495c-8bf5-4bebfc9d6ac0.png)
> 
> @ssakone just noticed that notifications checkmarks aren't visible

Looks like fixed now :heavy_check_mark:

**Comment by tonymorony** [comment]
graph colour would be great to make same as percentage change number colour :

<img width="512" alt="Screenshot 2021-08-24 at 00 42 19" src="https://user-images.githubusercontent.com/24797699/130492851-377f0cd4-08b3-4078-b0cb-dba2c61299e8.png">

**Comment by tonymorony** [comment]
not related directly to Dashboard,
Settings -> EULA, close button isn't on place

![image](https://user-images.githubusercontent.com/24797699/130511416-76e6ed9f-1dbb-44bb-9410-551810a1a740.png)

**Comment by smk762** [comment]
> not related directly to Dashboard,
> Settings -> EULA, close button isn't on place
> 
> ![image](https://user-images.githubusercontent.com/24797699/130511416-76e6ed9f-1dbb-44bb-9410-551810a1a740.png)

Can't see confirm button on your screenshot, otherwise same here
![image](https://user-images.githubusercontent.com/35845239/130540892-0973bb32-0429-4349-bbba-4049feac400d.png)

**Comment by smk762** [comment]
EULA button overflow fixed :heavy_check_mark: 
colors fixed :heavy_check_mark: 
toggle still dances :man_dancing: 
notifications tick color ok :heavy_check_mark:
