### ISSUE TITLE
[THEME TWEAKS]: Lite mode Wallet screen

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1199]
Enable "select all assets" checkbox seems to only have two states (all or nothing, not partial selection). The select all assets toggle also seems to be broken when selecting a coin from the unfiltered list after selecting a coin from filtered list state.

https://user-images.githubusercontent.com/35845239/130027225-24cd3164-52e3-41ef-ae90-f6d9f40a43d1.mp4

Positive 24hr change text color is too light (FIXED) :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/35845239/130027462-98dcb027-ecf6-447d-a8c1-d74dc3601a4a.png)

Arrows on buttons have different color to figma sample; line between price and balance is different color
![image](https://user-images.githubusercontent.com/35845239/130027640-21b04b2e-25c1-4d84-b26b-9df3eb5c6122.png)

Faucet button expands, where claim rewards button doesn't. Faucet button has older style with less rounded corners.
![image](https://user-images.githubusercontent.com/35845239/130027881-dd584e66-408f-4eb7-b0ff-22eeb401d3f2.png)
![image](https://user-images.githubusercontent.com/35845239/130027925-ba440db0-05f4-4287-acdd-8dde398cf0bc.png)

"smart chain" text is too dark against background
![image](https://user-images.githubusercontent.com/35845239/130028241-f2e02c30-26d2-4af5-8cdb-0b59d5886e23.png)

Transaction details looks good :heavy_check_mark: 
Send / receive forms look good :heavy_check_mark: 
Faucet message pop up ok :heavy_check_mark: 

Rewards estimate text is almost invisible (FIXED) :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/35845239/130029433-f3184e14-333f-4ea1-87be-3845cb3f7bd2.png)

dark hover on addressbook selection for sending  (FIXED) :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/35845239/130029773-34bb0614-91ee-496c-8601-07ef4e121816.png)
![image](https://user-images.githubusercontent.com/35845239/130029825-34349f6f-8ffc-4997-8133-d4262bb9e22b.png)

**Comment by smk762** [comment]
Can we change "wallet" to coin name here?
![image](https://user-images.githubusercontent.com/35845239/130028762-2810f551-2491-48f5-aa74-b9693ccf34ce.png)

**Comment by tonymorony** [comment]
moving here from PR

Some feedback: 

1) add crypto button not centered and looks different:

mockup:

![Screenshot 2021-08-19 at 01 42 36](https://user-images.githubusercontent.com/24797699/129960617-bbd60291-1a3d-45c6-b4a8-67490ed35e2f.png)

app:

![image](https://user-images.githubusercontent.com/24797699/129960676-c665f349-b739-4e68-a954-54d45121f0f3.png)


2) tickers and tickers search not centered and tickers should align with the search:

app:

![Screenshot 2021-08-19 at 02 37 16](https://user-images.githubusercontent.com/24797699/129961249-c13a742c-dae2-41e3-ae7e-3e40b582899d.png)


mockup:

![image](https://user-images.githubusercontent.com/24797699/129961349-4e319f47-2343-406b-83b8-8a664ea062fe.png)


3) Green dot:

![Screenshot 2021-08-19 at 02 39 03](https://user-images.githubusercontent.com/24797699/129961505-50732384-0c5b-44fa-9eb4-813f9978f1f0.png)

4) Arrows on buttons got different colors:

app:

![image](https://user-images.githubusercontent.com/24797699/129961860-d6b1419c-dea7-4cb9-a160-cdd3c85a7429.png)

mockup:

![image](https://user-images.githubusercontent.com/24797699/129962110-c96bc63a-27b6-43a7-b20e-5b24dc38230c.png)

5) this green is too green :)

app:

![image](https://user-images.githubusercontent.com/24797699/129963144-ddbd07c7-feee-4a2e-a276-a5e38bf34662.png)

mockup:

![image](https://user-images.githubusercontent.com/24797699/129963209-cbf37cd3-8f52-479a-9037-eee4f12ce49c.png)


6) this green also

![Screenshot 2021-08-19 at 14 47 31](https://user-images.githubusercontent.com/24797699/130029214-4990eae7-c5b7-4640-a463-31e0b85a4b67.png)

7) fiat "coming soon" message not visible (moving from another comment to not forget)
 
![image](https://user-images.githubusercontent.com/24797699/130029304-49d2aff3-5941-442d-83ee-6015b04217c3.png)

_Originally posted by @tonymorony in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1195#issuecomment-901379985_

**Comment by ssakone** [comment]
> Can we change "wallet" to coin name here?
> ![image](https://user-images.githubusercontent.com/35845239/130028762-2810f551-2491-48f5-aa74-b9693ccf34ce.png)

yes

**Comment by ssakone** [comment]
> moving here from PR
> 
> Some feedback:
> 
>     1. add crypto button not centered and looks different:
> 
> 
> mockup:
> 
> ![Screenshot 2021-08-19 at 01 42 36](https://user-images.githubusercontent.com/24797699/129960617-bbd60291-1a3d-45c6-b4a8-67490ed35e2f.png)
> 
> app:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129960676-c665f349-b739-4e68-a954-54d45121f0f3.png)
> 
>     1. tickers and tickers search not centered and tickers should align with the search:
> 
> 
> app:
> 
> ![Screenshot 2021-08-19 at 02 37 16](https://user-images.githubusercontent.com/24797699/129961249-c13a742c-dae2-41e3-ae7e-3e40b582899d.png)
> 
> mockup:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129961349-4e319f47-2343-406b-83b8-8a664ea062fe.png)
> 
>     1. Green dot:
> 
> 
> ![Screenshot 2021-08-19 at 02 39 03](https://user-images.githubusercontent.com/24797699/129961505-50732384-0c5b-44fa-9eb4-813f9978f1f0.png)
> 
>     1. Arrows on buttons got different colors:
> 
> 
> app:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129961860-d6b1419c-dea7-4cb9-a160-cdd3c85a7429.png)
> 
> mockup:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129962110-c96bc63a-27b6-43a7-b20e-5b24dc38230c.png)
> 
>     1. this green is too green :)
> 
> 
> app:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129963144-ddbd07c7-feee-4a2e-a276-a5e38bf34662.png)
> 
> mockup:
> 
> ![image](https://user-images.githubusercontent.com/24797699/129963209-cbf37cd3-8f52-479a-9037-eee4f12ce49c.png)
> 
>     1. this green also
> 
> 
> ![Screenshot 2021-08-19 at 14 47 31](https://user-images.githubusercontent.com/24797699/130029214-4990eae7-c5b7-4640-a463-31e0b85a4b67.png)
> 
>     1. fiat "coming soon" message not visible (moving from another comment to not forget)
> 
> 
> ![image](https://user-images.githubusercontent.com/24797699/130029304-49d2aff3-5941-442d-83ee-6015b04217c3.png)
> 
> _Originally posted by @tonymorony in [#1195 (comment)](https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1195#issuecomment-901379985)_

I m already focus on it, i push soon

**Comment by tonymorony** [comment]
when switching language have to switch sections to make buttons re-draw correctly:

https://user-images.githubusercontent.com/24797699/130511033-d40a9e39-299c-410f-886c-c233a4ff60cf.mov

**Comment by smk762** [comment]
From above, still pending on latest build
- addressbook hover background from wallet send screen too dark
- faucet button style not matching with claim rewards button style

**Comment by smk762** [comment]
Wallet button text overflowing in different languages (French), or reduced too small (Turkish / English), or flowing outside app window (Russian)
![image](https://user-images.githubusercontent.com/35845239/130542796-359e6338-de0a-4f53-89d9-2ab7296273a1.png)
![image](https://user-images.githubusercontent.com/35845239/130542933-3f3bc2a6-36c8-4822-b73c-d7aba4c416de.png)
![image](https://user-images.githubusercontent.com/35845239/130542962-6b8eb93e-8352-4b5e-9ad1-c0548717d4a6.png)
![image](https://user-images.githubusercontent.com/35845239/130543094-3b3968c2-0a46-4398-93f6-5b2d7e1390c0.png)


Switching to other page then back, Russian doesnt go outside app window, but still overflows button
![image](https://user-images.githubusercontent.com/35845239/130543047-7881fe5a-5f3d-48df-a0a7-be580892a153.png)

**Comment by smk762** [comment]
The above language issue is better in latest CI build (1e79182), but...

In Russian, slight overlap with arrows and "swap" button text
![image](https://user-images.githubusercontent.com/35845239/130610830-ee689941-e87e-4cb4-85d6-24b6a4fc4319.png)

In non-English Languages, seems that some of the button and chart are cut off by the right edge of the app

https://user-images.githubusercontent.com/35845239/130611323-e9cca205-5b99-4476-8130-a4acfc270e23.mp4

**Comment by smk762** [comment]
Some clipping in French on Wallet > Send > Addressbook
![image](https://user-images.githubusercontent.com/35845239/130612027-38854fc4-5671-4488-a250-ea23c67ebb6b.png)

Other languages ok.

We could probably reduce the name column here so theres a better chance the address will fit
![image](https://user-images.githubusercontent.com/35845239/130612328-fe086815-be54-4e9d-badf-d283f8660f10.png)

**Comment by smk762** [comment]
Green colors ok :heavy_check_mark: 
Faucet button not as rounded as the others :round_pushpin: 
Enable tristate still weird :waffle: 
Wallet coin selection menu alignment :heavy_check_mark: 
Bar between wallet balance and coin price still black (different in figma) :diamonds: 
fiat tooltip :heavy_check_mark: 


Arrows on swap button are inverted (compared to figma) but I think this is ok?
![image](https://user-images.githubusercontent.com/35845239/130778476-7cb85989-52b0-4c39-bfee-3de6c0742dcc.png)
