### ISSUE TITLE
[THEME TWEAKS]: Lite mode DEX screens

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1205]
Filter dropdown background too dark,has no hover effect
![image](https://user-images.githubusercontent.com/35845239/130456931-d2405974-2764-414b-9684-353f983acfdb.png)

Some text too light (FIXED) :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/35845239/130457069-f6878224-4605-4257-a8c7-f941d0d1d5ae.png)

column cell padding is uneven
![image](https://user-images.githubusercontent.com/35845239/130457191-2fac2383-7599-492e-86bd-04ec83d1e111.png)

darker green for this text (FIXED) :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/35845239/130457435-ea038402-82b5-4d18-82d0-6c2339e2e579.png)

Change icon for filter (and/or make larger)
![image](https://user-images.githubusercontent.com/35845239/130457819-a23e9b67-9dd5-4014-b060-3e71376a820b.png)

**Comment by smk762** [comment]
The red text on Pro view is a bit too light / bad contrast on my screen
![image](https://user-images.githubusercontent.com/35845239/130458191-b4c27bc1-32c1-4587-ba36-d580b0b991ca.png)

**Comment by tonymorony** [comment]
swap status card have a little glitch:

<img width="720" alt="Screenshot 2021-08-24 at 00 45 43" src="https://user-images.githubusercontent.com/24797699/130493037-0abcf6c7-e0ea-40ae-a5d0-31dd178b632e.png">

**Comment by tonymorony** [comment]
<img width="641" alt="Screenshot 2021-08-24 at 00 49 46" src="https://user-images.githubusercontent.com/24797699/130493540-fbe2fd1d-10d4-40c1-a219-72e0f9b45309.png">

**Comment by tonymorony** [comment]
this font is barely visible, needs to be black:

<img width="400" alt="Screenshot 2021-08-24 at 03 06 22" src="https://user-images.githubusercontent.com/24797699/130512296-e5aa695a-612e-491c-875f-2a642769f6dc.png">

**Comment by tonymorony** [comment]
not-visible text:

<img width="568" alt="Screenshot 2021-08-24 at 03 09 14" src="https://user-images.githubusercontent.com/24797699/130512617-a3fc0ba0-9403-4719-93ef-cb8a697e0e57.png">

**Comment by smk762** [comment]
Sighted same light text as Tony on screens above
Unable to replicate ticker/icon mismatch so far

**Comment by smk762** [comment]
Some things seen in logs:
```[11:14:25] [warning] [main.prerequisites.hpp:92] [549439]: qrc:/atomic_defi_design/qml/Exchange/Trade/SimpleView/SubOrders.qml:118: ReferenceError: hovered is not defined
[11:14:25] [warning] [main.prerequisites.hpp:92] [549439]: qrc:/atomic_defi_design/qml/Exchange/Trade/SimpleView/SubHistory.qml:125: ReferenceError: hovered is not defined
```

**Comment by smk762** [comment]
Some text overflow in French for swap confirmation   
![image](https://user-images.githubusercontent.com/35845239/130642423-252b05a6-e11d-4207-88a3-e6def936c6c1.png)

And Russian
![image](https://user-images.githubusercontent.com/35845239/130642750-7703f66e-b753-4a9c-b0a9-7e08602bd533.png)
