### ISSUE TITLE
[BUG]: order details using not correct tickers

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1206]
order details using not correct tickers (from selectors, not from order)

i click on MCL/KMD order details, can see MCL and KMD logos but KMD/DASH tickers

<img width="1013" alt="Screenshot 2021-08-24 at 00 47 36" src="https://user-images.githubusercontent.com/24797699/130493339-fd8db8a0-916e-4823-8ecb-62d9195976f5.png">

**Comment by SylEze** [comment]
Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1195/commits/619bf174ee36cdee31d58046b159c132bc6ec1c1

**Comment by tonymorony** [comment]
ty for the fix!
