### ISSUE TITLE
[BUG]: Orders and History don't display after logout/login.

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1207]
**Describe the bug**
In both Simple and Pro views, the orders and history tables are not populated after a user logs out and back in. Entries to these tables are only visible on initial login from app launch.

**To Reproduce**
1. Load app and login. 
2. Check your swap history (make sure you've made some previously)
3. Start a Rick/Morty swap, and make sure it is shown in the Orders table
4. Logout and back in to the same account
5. Check Orders and History tables, they will  both be empty.
6. The swap initiated in step 3 will continue in the background, but notifications will be the only indicator of progress.

**Expected behavior**
Orders in progress and History tables display correct data

**Screenshots**

https://user-images.githubusercontent.com/35845239/130606219-bdab6c41-36f6-4cf0-912a-e31a5a54ccce.mp4

**Desktop (please complete the following information):**
Happens in all OS

**Comment by tonymorony** [comment]
Thank you for the issue opening, just small addition: swap card will not be created for both swaps which were started before and new swaps until you restart the app

**Comment by smk762** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/df0eabbc759420337e6989213a863ce857d60459
