### ISSUE TITLE
[BUG]: Wrong base amount requested

### ISSUE THREAD

**Issue by CHMEX** [KomodoPlatform/atomicDEX-Desktop#1209]
**Describe the bug**
I issued around 10 times 10000 OOT at different prices those order filled and completed
than I issued a 2 OOT Order as you can see in the screen shot.
The Order is than executes for the 10000 OOT from before as if some variable if not correctly reset / reinitialized.

**To Reproduce**
Buy a lot of orders from at the same basevol and than change the basevol to the rest of the orderbook amount

**Expected behavior**
I expect to WYSIWYG

**Screenshots**
Select Order
![image](https://user-images.githubusercontent.com/33424502/130670131-8fcb5c0f-2a80-45d2-a9b2-e5a9616c6638.png)

Confirm order
![image](https://user-images.githubusercontent.com/33424502/130670207-22c15783-036e-414b-827d-dfca85a1c265.png)

See issued order call
![image](https://user-images.githubusercontent.com/33424502/130670252-36c6fa42-25a3-45ea-9d89-c28965072053.png)

 
**Desktop (please complete the following information):**
 - OS: Win
 - Version 0.4.3.beta

**Comment by CHMEX** [comment]
additional Observation:
I closed the App and restarted it after that I got a correct match. Which somehow tells me the variable in question was set correctly now

**Comment by smk762** [comment]
After restart did you place order again, or did the values update to what they should have been on the previously placed order?

**Comment by CHMEX** [comment]
I did place the order again

**Comment by smk762** [comment]
I still haven't encountered this one in the wild - please advise if it happens again

**Comment by smk762** [comment]
Closing - please reopen if issue presents itself again.
