### ISSUE TITLE
[FEATURE REQUEST]: Application updater polishing

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1228]
Let's combine the previous version checker we had (komodo.live/adexproversion) with auto-updater, with the actual version number/link specifying on the endpoint, so:

a) if something will go wrong as for win 0.5.0 we'll be able to change the version number on the endpoint to old and users will not see notifications
b) if GH will change API structure we'll able just update the link on endpoint
c) we'll be able to block app login if a hard forking update needs to be installed (as it was before with 3 states: availiable/required/mandatory)

So same view/notifications as we had before with komodo.live endpoint just with button to auto-update and info from endpoint

**Comment by Milerius** [comment]
> Let's combine the previous version checker we had (komodo.live/adexproversion) with auto-updater, with the actual version number/link specifying on the endpoint, so:
> 
> a) if something will go wrong as for win 0.5.0 we'll be able to change the version number on the endpoint to old and users will not see notifications
> b) if GH will change API structure we'll able just update the link on endpoint
> c) we'll be able to block app login if a hard forking update needs to be installed (as it was before with 3 states: availiable/required/mandatory)
> 
> So same view/notifications as we had before with komodo.live endpoint just with button to auto-update and info from endpoint

Hey @tonymorony  - thanks for the issue, could you provide the current json answer for komodo.live, i guess we will have to combine the old infos + the new checksum, additionally the endpoint need to fetch the last release informations, do we need to extend the python program or write a new one ?

**Comment by tonymorony** [comment]
I think we should not use auto-updater at all, but just inform the user about the patch by gathering info from an endpoint so at least there will be info about the update (as it was implemented initially, and it worked just fine until was broken by the auto-updater patch). auto-updating adds too much complexity and tricky bugs imo

right now there is no way to notify existing users in-app about the new patch, in case of a critical update it will be a very serious problem
