### ISSUE TITLE
[BUG]: v0.5.0 DEX Tooltip required minimum amount is sometimes a really long number

### ISSUE THREAD

**Issue by theblackmallard** [KomodoPlatform/atomicDEX-Desktop#1230]
**Describe the bug**
AtomicDEX Desktop v0.5.0 sometimes has very long "required minimum" amount in the tooltip for a trade. This is viewable on the Pro DEX tab when viewing a trade you are unable to perform.  

**To Reproduce**
1. Go to DEX tab, Pro view
2. Mouse-over Orderbook on an order you cannot fulfill (e.g. sell side for a coin you don't have) 
3. Tooltip pops up explaining "This order require a minimum amount of..." (unrelated: "requires")
4. Sometimes this number can be 104 digits long (see screenshot)

**Expected behavior**
A more reasonable/rounded minimum number related to the minimum transaction amount for the DEX or the blockchain

**Screenshots**
![image](https://user-images.githubusercontent.com/42389961/131404253-96430b97-6179-4d69-a099-f7fddcb376bc.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu, AppImage version

**Additional context**
Code line providing this tooltip.
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/qml/Exchange/Trade/OrderBook/ListDelegate.qml#L72

**Comment by tonymorony** [comment]
thanks for the issue opening @theblackmallard !
at the moment it displaying in the same format as receiving from API (it using rational numbers so decimals with very high precision creating)
 it would be great to decorate it to 8 decimal points

**Comment by tonymorony** [comment]
this one should be resolved now, can't find number with precision more than 8 digits in this tooltip
