### ISSUE TITLE
[FEATURE REQUEST]: Show a tooltip next to fees display with details about expenses

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX-Desktop#1252]
I've noticed that when I did a trade involving sTST test coin that around 12 sTST was taken from my balance. I didn't know the reason for it till I was told that the DEX charge 0.13% from any traded token. 

I think it would clear the confusion for new users to have a tooltip explaining which fees went to the dex and which one went as a network fees in different windows in the dex (before broadcast, ongoing and history)

I suggest having the following explanation as example:

_tbch fees 0.00000144 as tbch network fees
sTST fees 14 as 0.13% DEX fees from total 5000 order_

currently the fees taken are shown without explanation.
![image](https://user-images.githubusercontent.com/411046/132192140-fdc6db2e-2153-4543-8d05-04c31b484ec9.png)

An example tooltip used in the dex:

![image](https://user-images.githubusercontent.com/411046/132192289-33ddd9b1-84f7-4e26-8570-caf10a4aec7e.png)

Thank you and keep the good work.

**Comment by Milerius** [comment]
Excellent idea, i believe it's already like that in AtomicDEX Mobile, we can inspire from that

**Comment by Milerius** [comment]
We need to do something like that @SylEze:
![image](https://user-images.githubusercontent.com/21139416/132978171-49d79117-dedd-479e-bf5f-181ef8d46438.png)
