### ISSUE TITLE
[FEATURE REQUEST]: Better contrast for coin type in enable menu (lite mode)

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1255]
**Is your feature request related to a problem? Please describe.**
It is hard to read some of the coin types in enable menu when in lite mode.

**Describe the solution you'd like**
White text here should be best for both light and dark theme (dark theme is already white text)

**Additional context**
![image](https://user-images.githubusercontent.com/35845239/132210966-78ae90d9-fac6-4e31-98ec-21e84f0764c3.png)
![image](https://user-images.githubusercontent.com/35845239/132211103-4126235b-691e-4313-b255-d69e22d8cf39.png)

**Comment by tonymorony** [comment]
that how it looks like in figma:

![image](https://user-images.githubusercontent.com/24797699/133436942-431c4f49-7d5a-45ad-9508-b1311aac79fc.png)
