### ISSUE TITLE
[BUG]: Volume slider in place older section is not moving, stuck in it's place

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX-Desktop#1264]
For some reason the slider in the place order section is getting stuck and not moving. However you can see number changing when you hold it and slide left and right. 

**To Reproduce**
1. Go to the DEX section
2. Select pairs and select an order from the orderbook
3. Hold the slider handle and try to move it to the left
4. It's stuck

**Expected behavior**
The slider handle should move

**Screenshots**

https://user-images.githubusercontent.com/411046/132738570-6c5e2a82-080a-49d0-adaf-f731f581dc05.mp4

**Desktop (please complete the following information):**
APP: 0.5 beta
MM: 2.1.4027_mm2.1-slp-swap_2aae2b680_Linux_Release
Qt: 5.15.2

**Comment by tonymorony** [comment]
thank you for the issue opening, we've reworked this widget and I'm not able to reproduce this problem anymore on dev branch
