### ISSUE TITLE
[BUG]: Price providers icons overflow if KMD/LTC portfolio evaluation selected

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1278]
<img width="1190" alt="Screenshot 2021-09-15 at 14 47 45" src="https://user-images.githubusercontent.com/24797699/133394514-484bc009-fd01-49a9-801a-7d6cea6e122f.png">
<img width="1190" alt="Screenshot 2021-09-15 at 14 47 30" src="https://user-images.githubusercontent.com/24797699/133394521-cd9af253-9ffd-453f-be0a-2a67ee074d22.png">

**Comment by SylEze** [comment]
Should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1266

**Comment by tonymorony** [comment]
thanks for the prompt fix! looks good
