### ISSUE TITLE
[BUG]: Not correct sorting by balance in simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1279]
tested on https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1266/commits/9e291b7ef46c882fb78e6bdc55558499a43a6759 
it's alphabetical now it seems instead of fiat balance column usage

![image](https://user-images.githubusercontent.com/24797699/133397560-e7fdaa0d-f8a5-4f60-b359-0606894efe9c.png)

**Comment by Milerius** [comment]
fixed in last komodo_price branch

**Comment by tonymorony** [comment]
thanks for the prompt change
