### ISSUE TITLE
[BUG]: Price of evaluation asset is not equal 1

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1282]
Price of 1 LTC in LTC should be 1, price of 1 BTC in BTC should be 1, price of 1 KMD in KMD should be 1

<img width="1057" alt="Screenshot 2021-09-15 at 15 44 11" src="https://user-images.githubusercontent.com/24797699/133401528-54a13009-4d1c-4152-9386-be6bb110b5dc.png">
<img width="1057" alt="Screenshot 2021-09-15 at 15 44 50" src="https://user-images.githubusercontent.com/24797699/133401541-e2507efc-94ed-433f-9bde-308f15d32499.png">
<img width="1057" alt="Screenshot 2021-09-15 at 15 44 36" src="https://user-images.githubusercontent.com/24797699/133401579-9397b8e1-8ceb-4271-84a7-dd3051c9a391.png">

**Comment by Milerius** [comment]
should be fixed in komodo_price_service_branch

**Comment by tonymorony** [comment]
thanks for the prompt fix
