### ISSUE TITLE
[BUG]: Balance of other coin displaying for some time when switching sell coin in simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1283]
We can improve that now I believe since max_taker_vol returns ticker now

**Comment by Milerius** [comment]
should be partially fixed in the last komodo_price_change branch, now it's showing 0 meanwhile he fetch the max_taker_vol

**Comment by tonymorony** [comment]
thanks, now it's better :)

@SylEze @smk762 it would be great to show a spinner instead of 0 in a simple trading view during the "From" currency switch
