### ISSUE TITLE
[FEATURE REQUEST]: change the support@smartfi.com email to support@smartfi.zendesk.com in the TOS

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1285]

**Comment by tonymorony** [comment]
@smk762 could you please change it in `smartdex` branch?

**Comment by smk762** [comment]
Done in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/3cc8f834976399832d8276b5e1afbd7213fa0533
