### ISSUE TITLE
[BUG]: Bug when switch balance evaluation from one currency to another

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1288]
according to the report: There is a bug when you switch your balance from USD to BTC. The wallet balance is inaccurate

I was not able to reproduce it on my side yet, would be great to reproduce it and collect more info in this state

![image](https://user-images.githubusercontent.com/24797699/133404290-0a315abb-0d50-4f11-a346-0711b01edba7.png)

**Comment by smk762** [comment]
I was also unable to replicate this during testing so far. If they can specify steps before it might narrow it down, will try a few more approaches.

**Comment by tonymorony** [comment]
can confirm that switching is broken on smartdex branch @Milerius @SylEze :

![image](https://user-images.githubusercontent.com/24797699/134931944-e15cc48e-a7ba-4fdb-9b2d-a22e8872408b.png)
