### ISSUE TITLE
[BUG]: wrong chart in DEX tab after switching base from KMD to USDx

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1315]
Switching from SMTF/KMD to SMTF/USDC in DEX tab by clicking on "Best Orders" (buy SMTF) entry USDC shows chart of KMD/USD:
![image](https://user-images.githubusercontent.com/32116761/133910937-059c2170-7d3a-46f2-8a71-5baa56016904.png)
The bug can be reproduced with any stablecoin, switching base from KMD to BUSD has the same.
If switching base from KMD to USDx from coin selection dropdown, the bug is not there, only through "Best Orders".

**Comment by smk762** [comment]
@cipig I've been unable to reproduce this one, can you please try again and add a short video of the steps?

**Comment by cipig** [comment]
can't record videos, but follow this steps:
1. go to SMTF/KMD orderbook (no chart)
![image](https://user-images.githubusercontent.com/32116761/159270240-0d049dfe-5194-48fc-90e5-7120a87cb9b3.png)
2. click on a sell order, so that best_orders show up
![image](https://user-images.githubusercontent.com/32116761/159270444-fff4e091-bf2e-4c72-801c-b79f66b02f3b.png)
3. click on the `USDC`entry, the orderbook will change to SMTF/USDC
4. result: it shows the charts of KMD/USD
![image](https://user-images.githubusercontent.com/32116761/159270800-d7ec6c47-d3a7-49ac-82d5-6e9aad7466b9.png)

**Comment by smk762** [comment]
Not sure why, but my CLI bestorders response has items not visible in the app. This is using same mm2 instance as in app with app rpcpass.
![image](https://user-images.githubusercontent.com/35845239/160575310-5f43c3fd-f8b9-448a-b768-b3a1cdc7eaf8.png)
[bestorders.txt](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/8369767/bestorders.txt)

**Comment by cipig** [comment]
weird, i still have the problem
- open SMTF/KMD orderbook
- click on a SMTF ask (as if you would want to buy SMTF and pay with KMD)
- click on the USDC entry in best orders (orderbook switches to SMTF/USDC)
- ADEX shows chart of KMD/USD
![image](https://user-images.githubusercontent.com/32116761/161166337-51d6c7da-235d-4e6e-b81c-b09d73bd5b80.png)

**Comment by smk762** [comment]
replicated here also, previously was doing opposite of `click on a SMTF ask (as if you would want to buy SMTF and pay with KMD)` i.e. clicking on bid (sell SMTF).

Also replicated with same sequence using BTC instead of SMTF. Might need to add some logs to track this down.

**Comment by cipig** [comment]
bug is there if you switch from xxx/KMD orderbook to xxx/USD orderbook
it then shows KMD/USD chart, instead of xxx/USD
so there is a pattern
somewhere in code (switching orderbook), it selects the wrong side when asking for charts (base is rel and rel is base)
