### ISSUE TITLE
[BUG]: Show low volume coins price as N/A in simple trading view

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1316]
Steps to reproduce:
- go to simple swap
- choose from KMD, amount 2
- pick an order
- search for AUR

The result is empty:
![image](https://user-images.githubusercontent.com/32116761/133916624-3070a61d-79a3-49dc-a562-eda92e86fa72.png)

but AUR/KMD orderbook contains enough entries, the cheapest one is this, which should be part of the answer:
```
      "coin": "AUR",
      "price": "0.165",
      "maxvolume": "996",
      "min_volume": "0.00105",
```

unfortunately there are also orders like this in the orderbook:
```
      "coin": "AUR",
      "price": "0.17131904",
      "maxvolume": "19.6403061",
      "min_volume": "19.6403061",
```
those are not usable for simple swap, since you would need to match the amount exactly
could they be part of the problem?

**Comment by cipig** [comment]
buying from the cheapest ask in pro view works fine, ~ same amount as above, order matches
![image](https://user-images.githubusercontent.com/32116761/133916938-62889030-ce78-4b8d-ac2e-55f6b11a6905.png)
so this ask
```
      "coin": "AUR",
      "price": "0.165",
      "maxvolume": "996",
      "min_volume": "0.00105",
```
should definitely be part of the answer in simple view

**Comment by tonymorony** [comment]
we did exclude completely coins with <10k$ daily volume from the simple trading view to protect the users, probably it's still excluded because of that. 
we should display such coins with CEX rate as N/A if it's the case @Milerius

**Comment by cipig** [comment]
the coin has a CEX rate, this one is from the above ask:
![image](https://user-images.githubusercontent.com/32116761/133917113-879eb3b9-897a-4e5f-af71-d577ff6a48cc.png)

**Comment by tonymorony** [comment]
> the coin has a CEX rate, this one is from the above ask:
> ![image](https://user-images.githubusercontent.com/32116761/133917113-879eb3b9-897a-4e5f-af71-d577ff6a48cc.png)

it's in a Pro view

**Comment by cipig** [comment]
it works the other way around, selling AUR:
![image](https://user-images.githubusercontent.com/32116761/133917281-66316e8c-37f3-453d-847e-0fc30c2bba9d.png)

what about this?
![image](https://user-images.githubusercontent.com/32116761/133917409-68104692-717c-4a3e-b550-d8c57e1d0159.png)

honestly, i would remove the volume limit, list contains anyways coins like AXE, with a fake volume on Hotbit:
![image](https://user-images.githubusercontent.com/32116761/133917163-9f59b0f7-8a17-4b0e-9db5-ba3f50dd1588.png)
orderbook is empty, but trade history contains trades 100x higher than orderbook, all priced between best ask and best bid:
![image](https://user-images.githubusercontent.com/32116761/133917448-04e7b741-7c76-4562-8bad-f92e957a9136.png)

**Comment by tonymorony** [comment]
`honestly, i would remove the volume limit, list contains anyways coins like AXE, with a fake volume on Hotbit:` it's quite hard to moderate everything, we just excluded totally dead coins for now from cex price calculator, probably volume limit should be much higher with an option to configure/disable it by the user - will open an issue for that now

**Comment by auroracoin101** [comment]
> we did exclude completely coins with <10k$ daily volume from the simple trading view to protect the users, probably it's still excluded because of that.
> we should display such coins with CEX rate as N/A if it's the case @Milerius

Where are you getting the daily volume from ?

**Comment by auroracoin101** [comment]
Just as another thought....   Komodo platform is promoting decentralized trades, yet coins like Auroracoin are filtered out because of centralized exchange volume, despite having more volume on AtomicDEX than many higher volume coins. 

Perhaps we are in a unique position as we are having to re-establish ourselves from the previous team members being less active.

Thanks for all the consideration.   mikael hannes
