### ISSUE TITLE
[BUG]:  There seems to be a bug when manually adding BEP-20 tokens to ADEX

### ISSUE THREAD

**Issue by fujicoin** [KomodoPlatform/atomicDEX-Desktop#1329]
There seems to be a bug when manually adding BEP-20 tokens to ADEX. 
A preview of the configuration file when FJCB is added is attached.
ContractID: 0xda73AE86D38D9b5D22C64722320cCC071cB79ba3

[preview.txt](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/7211825/preview.txt)

There are two descriptions of  `"platform" : "ETH"` , but I think this must be "BNB".

![preview](https://user-images.githubusercontent.com/7656623/134370018-c9ceddf2-e7f1-43b4-892c-bd4775d0cffe.png)

**Comment by fujicoin** [comment]
@tonymorony 
I think this line is suspicious. The three-letter "ETH" is not required in the configuration file. But this line contains "ETH".
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/79eccda068bb9231519189333a0e0d649e12755f/src/core/atomicdex/pages/qt.settings.page.cpp#L417

```
-                    &::mm2::api::g_etherscan_proxy_http_client, "/api/v1/token_infos/bep20/"s + contract_address.toStdString(), "BEP20"s, "ETH"s, "BEP-20"s, "BNB"s, "ERC20"s);
+                   &::mm2::api::g_etherscan_proxy_http_client, "/api/v1/token_infos/bep20/"s + contract_address.toStdString(), "BEP20"s, "BNB"s, "BEP-20"s, "BNB"s, "ERC20"s);
```

It's hard to guess, but I want you to consider it.

**Comment by tonymorony** [comment]
@fujicoin thank you for catching, issue opening, and hinting at an actual solution!

https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1331 should eliminate this PB

artefacts: https://github.com/KomodoPlatform/atomicDEX-Desktop/runs/3687466814

**Comment by tonymorony** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/releases/tag/0.5.2-beta
