### ISSUE TITLE
[BUG]: re-work best_price widget content

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1333]
![image](https://user-images.githubusercontent.com/32116761/134786050-dc20d7b9-8d70-464e-8905-925729557ba1.png)
this is for sell 300 SMTF when in SMTF/KMD orderbook
the fiat price in best orders is wrong

this is the SMTF/USDC orderbook at the same time:
![image](https://user-images.githubusercontent.com/32116761/134786144-4f30e582-8082-466f-8601-f72013c1d6ad.png)
for 300 SMTF you get 150 USDC, but above best orders shows a fiat price of 2742$ for USDC
2742$ would be the price when you sell the max amount of SMTF (from that particular order), not the 300
the prices shown there are not comparable to each other, since different volumes are used (order volume instead of the volume entered, 300)

**Comment by Milerius** [comment]
I think it's not related to desktop imo

**Comment by tonymorony** [comment]
@cipig thank you for the issue opening! we definitely need to improve this widget information reflection (that was one of the main reasons why we do not show it by default on the layout since the previous release)
Right now in "Fiat price" column displaying something like a "Fiat volume" for your amount with the best price (something extra tricky and hard to guess)

**Comment by cipig** [comment]
in buy mode it works fine, just sell mode uses wrong volume for the calculation (from order instead of the one entrered by the user)
this is the same, just for buying 100 SMTF:
![image](https://user-images.githubusercontent.com/32116761/134806396-6275f6ef-4237-4f49-8020-e4c93db90ae3.png)
the values are all correct

**Comment by Milerius** [comment]
But again it's not a bug, this commit: https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/3c40ac628de1f74481cafa9e147f4d8b983d7abc from 2 month ago was required and asked by @tonymorony  I do not remember what was the issue, but from what I remember we stopped use the CEX rate for sorting and use the fiat price instead, and we had to do it this way to satisfy the simple trading view

**Comment by cipig** [comment]
it's not about the sorting, the value "Fiat Price" is simply wrong in sell mode as compared to buy mode, where it is correct

**Comment by cipig** [comment]
the value "fiat price" is wrong in "sell" mode, even with available prices from cex
![image](https://user-images.githubusercontent.com/32116761/145343945-98ec7d94-11ef-4257-9227-44cb642a279d.png)
simply because it is calculated based on the max_volume from the particular order from that orderbook entry... but it should be calculated based on the volume i want to sell... just a different variable
