### ISSUE TITLE
[FEATURE REQUEST] Add a filter to the History (recent swaps) list

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Desktop#134]
For an active trader, soon enough the list would grow too large to be manageable.

Possible Filters:
- Successful
- Failed
- Coin Bought
- Coin Sold

**Comment by jansako** [comment]
[]https://github.com/KomodoPlatform/atomicDEX-Pro/issues/135)

**Comment by naezith** [comment]
Another feature to consider at UI design @ca333

**Comment by tonymorony** [comment]
👍 missing this one a lot during the usage :)

also some export for profit/loss calculating will be superb. maybe we can implement trades statistics right in app in future

as I remember @smk762 had few examples of implementation of that

**Comment by smk762** [comment]
Some code here - https://github.com/smk762/atomicDEX_pystats/blob/master/lib/stats_lib.py
Will be reviewing the stats repo this week to include new events or json changes output from mm2 over the last few months.

**Comment by tonymorony** [comment]
> Some code here - https://github.com/smk762/atomicDEX_pystats/blob/master/lib/stats_lib.py
> Will be reviewing the stats repo this week to include new events or json changes output from mm2 over the last few months.

Oh thats a good one but it's for overall network success rate stats tracking if I remember correct.

 I more meant views you had in mmbot_qt for profit/loss of swaps tracking

**Comment by smk762** [comment]
It had some calculation of coin deltas (also in pytomicDEX), but no fiat price (at time of swap) associated. 

![image](https://user-images.githubusercontent.com/35845239/87300986-5f431780-c541-11ea-9f34-062570b186a5.png)

Ideally fiat price would need to be recorded at time of swap and stored locally.

**Comment by Milerius** [comment]
Implemented long time ago, possible to filter by date and coins.
