### ISSUE TITLE
[BUG]: Long coin names doesn't fit selectors in pro view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1342]
cf:  https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1303

<img width="618" alt="Screenshot 2021-09-28 at 15 48 05" src="https://user-images.githubusercontent.com/24797699/135055215-30794362-6324-4490-9e6d-1372c561b65b.png">

**Comment by smk762** [comment]
Current style uses ellipses where there is an overflow
![image](https://user-images.githubusercontent.com/35845239/153298224-eea2663e-f3fe-43ae-af70-b57c6c8128c7.png)

Font color in light mode obscures ellipses.
![image](https://user-images.githubusercontent.com/35845239/153298203-d961ccac-9ea0-46b8-9c84-f1bb204aab64.png)
