### ISSUE TITLE
[FEATURE REQUEST]: CLI only AtomicDex with front-end

### ISSUE THREAD

**Issue by BitSec01** [KomodoPlatform/atomicDEX-Desktop#1360]
**Is your feature request related to a problem? Please describe.**
I am always annoyed when I am using AtomicDex and my internet is unstable or that I have to have keep my PC turned on in order for my trades to stay "alive".

**Describe the solution you'd like**
I would like you to create a CLI only that I can host on a server. And also a web interface so that I can do all the things I can do with the AtomicDex but then in the browser and without the need of having my PC on 24/7.

So basicaly a CLI only version that I can host on my own server and then make the front-end to connect to the server so I can close it / open it whenever I want and every trade will be on the 24/7 server.

**Describe alternatives you've considered**
I heard in the Discord that there already is a CLI only version of AtomicDex. Perhaps someone can make an interface so I don't have to deal with CLI commands only because those are always hard to get a good view of the market and of swaps and statuses etc.

It's kinda like Bitcoin has an RPC and some people create front-ends for the RPC. I guess this is something similar.
The RPC lives on the 24/7 server and I can just connect to it with either the web interface or a client that connects to the RPC server to do my trades.

**Comment by Milerius** [comment]
You mean https://github.com/Milerius/mm2-client @BitSec01 ?

It's a personal project - that I do in my spare time and that works in CLI including browser wasm console - if this one get popular we may consider it in our roadmap or so (would probably need to be ported to rust).

**Comment by BitSec01** [comment]
> You mean https://github.com/Milerius/mm2-client @BitSec01 ?
> 
> It's a personal project - that I do in my spare time and that works in CLI including browser wasm console - if this one get popular we may consider it in our roadmap or so (would probably need to be ported to rust).

I'll check it out soon. I quickly looked over it but in the features it didn't check the boxes on buy and sell what does that mean?

**Comment by Milerius** [comment]
> > You mean https://github.com/Milerius/mm2-client @BitSec01 ?
> > It's a personal project - that I do in my spare time and that works in CLI including browser wasm console - if this one get popular we may consider it in our roadmap or so (would probably need to be ported to rust).
> 
> I'll check it out soon. I quickly looked over it but in the features it didn't check the boxes on buy and sell what does that mean?

Just implemented setprice so far (maker)

**Comment by BitSec01** [comment]
@Milerius project looks nice but I am really looking for something that has a front-end that might look like AtomicDex.

**Comment by gcharang** [comment]
@Milerius 

I think @BitSec01 wants 
1) mm2 to run on a server 
2) a GUI on their local system that looks like AtomicDEX-desktop to interface with the remote mm2 and allows all features(wallet/trading)

This has the benefit of allowing no-cli/low-cli users to leave their mm2 connected to the internet 24/7 without having a local system also running 24/7 but also use a GUI to access it

**Comment by BitSec01** [comment]
@Milerius yes pretty much exactly that. You worded it way better than I did :P

**Comment by cipig** [comment]
see https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2303 and https://docs.komodoplatform.com/basic-docs/atomicdex-api-20/start_simple_market_maker_bot.html
