### ISSUE TITLE
[BUG]: switch button in filter section don't work

### ISSUE THREAD

**Issue by ciumete** [KomodoPlatform/atomicDEX-Desktop#1373]
**Describe the bug**

**To Reproduce**
1. Go to Dex -> Orders tab or History tab
2. Click on Filter , chose 2 assets and click on switch button 

**Expected behavior**
Switch between 2 assets

**Desktop (please complete the following information):**
 - OS: Win 10 pro x64

**Comment by smk762** [comment]
Current dev branch no longer has this issue
