### ISSUE TITLE
light theme login screens tweaks.

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1412]
all screens for the login/import process looks not good now in light theme

<img width="1270" alt="Screenshot 2021-11-08 at 17 57 19" src="https://user-images.githubusercontent.com/24797699/140730245-83820d15-c9c2-4350-b3fa-7039dc8bf5de.png">
<img width="1270" alt="Screenshot 2021-11-08 at 17 57 02" src="https://user-images.githubusercontent.com/24797699/140730248-f2c9708e-5839-4af1-9290-4472bc85b6df.png">
<img width="1270" alt="Screenshot 2021-11-08 at 17 55 02" src="https://user-images.githubusercontent.com/24797699/140730253-f180af39-3dfb-42d3-8f5f-3f443d8c9c47.png">

there is UI for the light theme, also you can use colors from the same screen webdex design.
if necessary @polevin will make figma screens especially for desktop

_Originally posted by @tonymorony in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1399#issuecomment-963040310_

**Comment by tonymorony** [comment]
@SylEze Relevant designs were added to figma

**Comment by tonymorony** [comment]
Closing this one in favor of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1427
