### ISSUE TITLE
[FEATURE REQUEST]: add nomics charts

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1420]
Adding charts from nomics has this advantages:
- we can have charts for all base coins, eg BTCZ/KMD
- we don't have to configure tradingview pairs for each new coin and each new pair

example code
```
<div class="nomics-ticker-widget" data-name="BitcoinZ" data-base="BTCZ" data-quote="KMD"></div><script src="https://widget.nomics.com/embed.js"></script>
```
from https://nomics.com/assets/btcz-bitcoinz/widget

`data-base` and `data-quote` are the `nomics_id` from coins config: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/0.5.2-coins.json#L1107

We can either use nomics when no tradingview pair is configured or replace tradingview completely.

**Comment by Milerius** [comment]
> Adding charts from nomics has this advantages:
> 
> * we can have charts for all base coins, eg BTCZ/KMD
> * we don't have to configure tradingview pairs for each new coin and each new pair
> 
> example code
> 
> ```
> <div class="nomics-ticker-widget" data-name="BitcoinZ" data-base="BTCZ" data-quote="KMD"></div><script src="https://widget.nomics.com/embed.js"></script>
> ```
> 
> from https://nomics.com/assets/btcz-bitcoinz/widget
> 
> `data-base` and `data-quote` are the `nomics_id` from coins config: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/0.5.2-coins.json#L1107
> 
> We can either use nomics when no tradingview pair is configured or replace tradingview completely.

Thanks for opening the issue, unfortunately this widget have a better suits for the wallet view rather than the tradingview, however I see that nomics have a tradingview chart also for each pair, maybe we can gently ask them the URL to use it in our project

**Comment by smk762** [comment]
Nomics charts (via widget) don't offer a darkmode yet.
