### ISSUE TITLE
[FEATURE REQUEST]: Release visual blockers

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1427]
this issue cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1383 (might be duplicates also) 

# Login part

- [x] Welcome screen is visually broken now in light theme, there shouldn't be a grey color

![image](https://user-images.githubusercontent.com/24797699/141751286-e8ed307c-adb4-41b7-8fd3-69e1a7e72ff5.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141751534-8c15d48e-ff03-4a0f-a9b4-b895f918e04b.png)

- [x]  2) Login screen is visually broken now in light theme, there shouldn't be a grey color:

![image](https://user-images.githubusercontent.com/24797699/141751637-ccb98bde-2df6-4f3a-bd97-bc8aa64b6b75.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141751699-7cb49896-3dd0-46b0-be6c-1c6efa757aad.png)

- [x] 3) Seed import screen is visually broken now in light theme, there shouldn't be a grey color

![image](https://user-images.githubusercontent.com/24797699/141752136-a2e23431-ca89-42a2-a07d-d654d423410f.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141752287-a95d4bc5-f13f-4c8e-9b09-9d2e87455e2b.png)

- [x] 4) Custom seed popup is visually broken now in light theme

![image](https://user-images.githubusercontent.com/24797699/141752448-70114f49-1766-4019-8e1e-824f86c560a7.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141752507-6b193e1f-56c3-46ff-b6c6-fa2d8468fb55.png)

- [x] 5) New wallet creation process is visually broken now  in light theme

![image](https://user-images.githubusercontent.com/24797699/141752716-3bdb032f-375b-4af3-8ed7-4d9e1694e4f6.png)

figma: 

![image](https://user-images.githubusercontent.com/24797699/141752761-bcc1b66b-abad-41bb-a812-4c5141308109.png)

- [x] 6) words confirmation - same

![image](https://user-images.githubusercontent.com/24797699/141752843-dc26537e-28b6-45e3-92cb-04d13ab0e5a4.png)
 
![image](https://user-images.githubusercontent.com/24797699/141752968-4ab7c953-0aa9-46e3-856f-eb57bf25c5d3.png)

- [x] 7) wallet deletion modal:

![image](https://user-images.githubusercontent.com/24797699/141757862-7a343c17-034d-4653-b7ce-11b7ceb3a100.png)

- [ ] 8) Green color on text selection and spinner spoil a bit overall impression - it should follow the main theme color

![Screenshot 2021-11-26 at 06 18 43](https://user-images.githubusercontent.com/24797699/143507542-7e591acb-456e-4caf-a44f-ce2f065640ae.png)

![Screenshot 2021-11-26 at 06 18 21](https://user-images.githubusercontent.com/24797699/143507558-83fb2ec8-2d87-484d-a825-0b07fb9356f5.png)

 - [x] 9) Now nothing happens if the user inputs not correct password and presses "Connect"

**Comment by tonymorony** [comment]
# Dashboard/wallet part

- [ ] 1) Notifications in light theme

![image](https://user-images.githubusercontent.com/24797699/141753180-73bce6d6-8988-4d91-a9ee-9d93de83b90f.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141753303-2d806594-0df1-4793-adfb-e603f3b4ddc3.png)

- [ ] 2) Logout modal

![image](https://user-images.githubusercontent.com/24797699/141753449-a4f5663e-bf54-4ab3-a6ea-54104296b524.png)

- [ ] 3) Light/dark theme mode switching button is missing

- [ ] 4) Price graph is missing in coin details view

will add more items here

**Comment by tonymorony** [comment]
# Trading (simple view)

- [ ] 1) Swap now button is visually broken

<img width="592" alt="Screenshot 2021-11-15 at 16 11 28" src="https://user-images.githubusercontent.com/24797699/141754258-00dec055-9633-46a6-a422-edcbecd0ced8.png">

figma:

<img width="524" alt="Screenshot 2021-11-15 at 16 13 50" src="https://user-images.githubusercontent.com/24797699/141754423-3005069b-518f-4179-bd53-8cc8c7e39450.png">

- [ ] 2) Swap filters are visually broken

![image](https://user-images.githubusercontent.com/24797699/141754532-072ca509-799f-4545-aaa2-5efe76274579.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141754622-7a7c1673-3272-4c28-a485-5842b67d2fdd.png)

- [ ] 3) Swap cards are visually broken (especially on selection)

<img width="1006" alt="Screenshot 2021-11-15 at 16 16 14" src="https://user-images.githubusercontent.com/24797699/141754795-6ecd90aa-15e5-47df-a62d-4fcd10075910.png">

figma:

![image](https://user-images.githubusercontent.com/24797699/141754872-a504a6cf-2a86-4b51-a579-3aabf0d0d34c.png)

- [ ] 4) Swap card is not updated accordingly to figma

![image](https://user-images.githubusercontent.com/24797699/141754951-465b13a4-1924-4e2e-b026-72de114b830c.png)

figma:

![image](https://user-images.githubusercontent.com/24797699/141755102-19e9337d-1803-440b-b0d5-df8b03ed83ac.png)

- [ ] 5) colours looks visually broken (coin icons are not visible, search icon isn't visible)

![image](https://user-images.githubusercontent.com/24797699/141755435-8c96b81e-ad67-4995-8340-105053d1c591.png)

figma:

probably we'll need @poleving help for this one since not found relevant content in figma

**Comment by tonymorony** [comment]
# Pro view

- [ ] 1) Not writing about the overall mismatch with designs since we have not worked on this part much yet, want just to highlight one p0 to not miss - after order select price field content is not visible

<img width="608" alt="Screenshot 2021-11-15 at 16 24 02" src="https://user-images.githubusercontent.com/24797699/141756124-365c81c2-1b69-4c8e-8fbd-5c1fcbc77345.png">

**Comment by smk762** [comment]
>  5) colours looks visually broken (coin icons are not visible, search icon isn't visible)

Search now visible, icons still very faded where not enables. maybe could reduce transparency?

>  6) It would be awesome to make Simple / Pro switcher not dancing (on the same position in both pro and simple views)

Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1479
