### ISSUE TITLE
[FEATURE REQUEST]: Allow adding custom SEP-20 (SmartBCH-based ERC-20) similarly to ERC-20

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/atomicDEX-Desktop#1428]
**Is your feature request related to a problem? Please describe.**
It was requested during the initial SmartBCH integration discussion https://github.com/KomodoPlatform/atomicDEX-API/issues/1063#issuecomment-919853573

**Describe the solution you'd like**
Allow adding custom SEP-20 assets.

**Describe alternatives you've considered**
I guess there are no alternatives for such functionality :slightly_smiling_face: 

**Additional context**
We may need at least one token added to the coins file as an initial example.

cc @damascene

**Comment by Milerius** [comment]
Require the equivalent of https://docs.etherscan.io/api-endpoints/tokens#get-token-info-by-contractaddress to query token infos

**Comment by artemii235** [comment]
@damascene
> Require the equivalent of https://docs.etherscan.io/api-endpoints/tokens#get-token-info-by-contractaddress to query token infos

Does SmartScan have a similar API?

**Comment by damascene** [comment]
An API from a DEX provider is provided here:
https://docs.benswap.cash/features/api#list-of-all-public-api-endpoints
Example:

Cat
https://api.benswap.cash/api/sep20/token/0x265bd28d79400d55a1665707fa14a72978fa6043

Honk
https://api.benswap.cash/api/sep20/token/0xF2d4D9c65C2d1080ac9e1895F6a32045741831Cd

However It's not an official source

**Comment by smk762** [comment]
Closing, transfered to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1879
