### ISSUE TITLE
[BUG]: Can't find orders for some coins in simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1445]
<img width="790" alt="Screenshot 2021-11-22 at 18 27 29" src="https://user-images.githubusercontent.com/24797699/142853882-d1addfbe-2c20-47ce-856b-a3578aba9413.png">
<img width="790" alt="Screenshot 2021-11-22 at 18 27 21" src="https://user-images.githubusercontent.com/24797699/142853896-cf416a2b-4cb7-444e-af77-42988d636281.png">
<img width="790" alt="Screenshot 2021-11-22 at 18 27 13" src="https://user-images.githubusercontent.com/24797699/142853902-85f71f51-d214-4356-aa5f-f1c9d2b002ad.png">

in PRO view I see orders for these coins:

![image](https://user-images.githubusercontent.com/24797699/142854094-822e2a07-34cb-4cb2-a252-82f663a9db4c.png)

**Comment by cipig** [comment]
maybe because coins with a 24h_volume < 10k USD are filtered out: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L169

**Comment by tonymorony** [comment]
> maybe because coins with a 24h_volume < 10k USD are filtered out: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L169

hmm, can remember that last time we've agreed with @Milerius  to just show this coins on bottom with N/A as a CEX rate

**Comment by Milerius** [comment]
> > maybe because coins with a 24h_volume < 10k USD are filtered out: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L169
> 
> hmm, can remember that last time we've agreed with @Milerius to just show this coins on bottom with N/A as a CEX rate

I think last time we discussed about removing this limit and keep seeing the CEX rates for smart chain, and use N/A CEX rate for other coins, I did the first part in #1446 by restoring best orders for smartchain, will require a bigger refactor for the N/A for other coins.

**Comment by tonymorony** [comment]
both assets on the screenshots above are smartchains (TKL and MCL)

**Comment by Milerius** [comment]
> both assets on the screenshots above are smartchains (TKL and MCL)

Yeah as I said above should be fixed in #1446 for all smart chain!

**Comment by tonymorony** [comment]
oh, it's a fresh patch (read comment briefly and thought you refer to some previously merged one) - will test it, thanks!
