### ISSUE TITLE
[BUG]: Design tweaks feedback

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1453]
Creating this issue to keep problems blocking this particular PR in a single place

- [x] 1) Let's revert pro-view changes and do it in one of the future splits

- [x] 2) Logo loading in not correct state after login https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1418#issuecomment-979514065

- [x] 3) Send modal fields background disappeared https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1418#issuecomment-980646119

- [x] 4) Top panel is visible without login https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1418#issuecomment-980668754

- [x] 5) A bit too far from order :)

<img width="756" alt="Screenshot 2021-11-30 at 05 17 41" src="https://user-images.githubusercontent.com/24797699/143951626-6f8a8bbd-54e5-4845-8f03-965a78e084a4.png">

- [ ] #1473

https://user-images.githubusercontent.com/24797699/143952855-2a6d9ec1-8bd3-4cbf-b780-d7c981791010.mov

- [ ] #1472

<img width="922" alt="Screenshot 2021-12-02 at 23 44 36" src="https://user-images.githubusercontent.com/24797699/144465546-cb9e2b86-b95b-4f32-9f25-e89032fdca12.png">

**Comment by SylEze** [comment]
> 5) A bit too far from order :)

This one is present since 0.5.2, I suggest we find a more elegant alternative since I did not find any fix

**Comment by tonymorony** [comment]
> > 5. A bit too far from order :)
> 
> This one is present since 0.5.2, I suggest we find a more elegant alternative since I did not find any fix

@SylEze on 0.5.2 it drawing near the orderbook

![image](https://user-images.githubusercontent.com/24797699/144034931-01c84e45-ce74-4b7f-b086-2b9e7f426c1c.png)
