### ISSUE TITLE
Show min_volume of maker order

### ISSUE THREAD

**Issue by coingirl87** [KomodoPlatform/atomicDEX-Desktop#1458]
Hello,

it would nice to see the minimum volume of an order:

my ideas:

1.
![idea 1](https://user-images.githubusercontent.com/64635975/144201523-842fe680-0cb5-4655-b84d-59a934a79a02.png)

2.
![idea 2](https://user-images.githubusercontent.com/64635975/144201549-75e079f7-44d8-451d-ae58-424c9a2f1ac6.png)

I prefer number 1.

Many thanks

**Comment by Milerius** [comment]
Thanks for opening the issue @coingirl87 - It's definitely a good improvement - I thumb it up.

cc @tonymorony

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/146639315-4f7dc4a7-fff6-435b-a2c1-a400f011fbc2.png)
min volume is now shown when you select an order from orderbook

**Comment by tonymorony** [comment]
also, there is a warning sign if balance is less than min volume. additional column in orderbook will overcomplicate/make it harder to read a bit imo
so closing this one as implemented, thank you for the issue opening!

<img width="484" alt="image" src="https://user-images.githubusercontent.com/24797699/155181206-585f83d4-db90-433c-927f-946377c55e43.png">
