### ISSUE TITLE
Import wallet attempts and fails to login once complete

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1461]
After creating wallet via import seed, it attempts autologin and gets stuck.

https://user-images.githubusercontent.com/35845239/143798809-1e0a27f6-de71-40ff-af51-5e5ca7246177.mp4

in 0.5.3 release, after importing wallet it takes you back to the start screen to select a wallet (does not try and log you in automatically)

In dev / design branches, after creating wallet with bi39 seed, it also doesnt try and auto login.

I that it should drop back to start screen, not try and auto login.

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1451#issuecomment-981234268_

**Comment by tonymorony** [comment]
Yeah, we should make it auto-login successfully or redirect back to the start screen. We definitely can't release an application that hangs on wallet creation CC [ @SylEze @ssakone ]

**Comment by cipig** [comment]
sure it's related to wallet creation? i had this also on normal startup, without new wallet... after i entered my password, it hang at the same place... check if mm2 was started... in my case it was started every time, but GUI couldn't talk to it... had to kill everything and try again
