### ISSUE TITLE
Moving menu introduced a visual bug with the moving chart

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1473]
https://user-images.githubusercontent.com/24797699/143952855-2a6d9ec1-8bd3-4cbf-b780-d7c981791010.mov

**Comment by smk762** [comment]
Issue no loner applies since we use different charts now, and the chart area remains static.
https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/35845239/dd45b354-7a24-4e09-9814-924ba65f25e1
