### ISSUE TITLE
Enhancement proposals (Milerius)

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1475]
<img width="1792" alt="Capture d’écran 2021-12-04 à 05 46 49" src="https://user-images.githubusercontent.com/21139416/144697426-b4c074f5-3573-4ddb-8621-147ce04c5304.png">

The list doesn't fit with the rounded design; looks not natural.

In comparaison the sub list of filtering looks more natural:

<img width="1792" alt="Capture d’écran 2021-12-04 à 05 47 56" src="https://user-images.githubusercontent.com/21139416/144697457-fbbe8445-64ba-4bef-9596-93746b123bd6.png">

In the following video, the cursor changes only on the first button, but not on the second one:

https://user-images.githubusercontent.com/21139416/144697575-8034ffed-63e5-4cea-a1f4-73fc8b4af0ce.mov

Room for improvements, in the following screenshot having a search bar, would be nice, also note that the number of default wallets shown in the list is 3. There is enough place to have more, even in full screen:

<img width="381" alt="Capture d’écran 2021-12-04 à 05 53 52" src="https://user-images.githubusercontent.com/21139416/144697659-161fe34d-9344-4b41-86fa-a3193be89761.png">

<img width="1838" alt="Capture d’écran 2021-12-04 à 05 55 51" src="https://user-images.githubusercontent.com/21139416/144697673-5c368b5b-f450-4261-9b82-6af79060e79e.png">

Not a fan of the word `connect` here, also missing one uppercase at the beginning of the word IMHO:

<img width="1838" alt="Capture d’écran 2021-12-04 à 05 56 54" src="https://user-images.githubusercontent.com/21139416/144697711-dd1e8392-e33f-47af-b470-e201eb519124.png">

I've shared a new icon package logo for lang on keybase, and it's not used in settings or login page, making it very ugly on settings. Also, there is a lack of over effect, and it look a bit unnatural:

https://user-images.githubusercontent.com/21139416/144697826-0a0f862e-ff14-4df4-ac7b-0fd790c9992d.mov

_Originally posted by @Milerius in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1418#issuecomment-985967068_

**Comment by smk762** [comment]
- [ ] Standardise dropdown design. rounded edges, no border
- [x] Fix button cursor
- [ ] Make wallets list searchable
- [ ] Show more than 3 wallets in scroll menu (expand to fill available space)
- [ ] Change "Connect" to "Log In"
- [ ] Add hover effect to language icons

**Comment by smk762** [comment]
All issues mentioned above have been resolved.
