### ISSUE TITLE
On first load after tabswitch to dex > orders, half of the right side coin is cut off.

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1510]
On first load after tabswitch to dex > orders, half of the right side coin is cut off. Issue also present if hovering over sidebar and it is expanded, but gets gets auto-fixed after hovering off once sidebar retracts.

On history page, scrollbar makes it always partially cut off, and almost completely hidden when sidebar expanded.

https://user-images.githubusercontent.com/35845239/146180534-e2299733-0e68-4a36-9d6d-ece7a76fe5d3.mp4

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1487#issuecomment-994712036_

**Comment by tonymorony** [comment]
on my mac it looks like this by default:

![image](https://user-images.githubusercontent.com/24797699/146263355-48101e8d-2f93-4ab3-95cb-80ecdb43f73e.png)

orderbook and bestorders widgets became too wide, there is a lot of unused space. @SylEze I think we should improve that before the release since its regression + on small laptop (1366x768 what is the second most popular resolution in the world https://gs.statcounter.com/screen-resolution-stats) it'll be not possible to maximize and see all content. 
Also maybe we can show fiat value in orders on hover and will save some space this way.
 
<img width="668" alt="Screenshot 2021-12-15 at 22 56 16" src="https://user-images.githubusercontent.com/24797699/146263917-b98fa9cf-38f6-4701-bfad-3222fb21e2f7.png">

**Comment by cipig** [comment]
> orderbook and bestorders widgets became too wide, there is a lot of unused space.
There is only space when values are small, but if there are values like 12345678.12323343 there is no space any more... look at other orderbooks, like BIDR/KMD.

**Comment by tonymorony** [comment]
> > orderbook and bestorders widgets became too wide, there is a lot of unused space.
> 
> There is only space when values are small, but if there are values like 12345678.12323343 there is no space any more... look at other orderbooks, like BIDR/KMD.

checked BIDR/KMD orderbook - there is a lot of empty space still. in the case of large numbers, we can show only significant digits

<img width="400" alt="Screenshot 2021-12-16 at 12 19 53" src="https://user-images.githubusercontent.com/24797699/146353447-81fe4df7-68ef-477a-b7e7-b374bd450501.png">

**Comment by SylEze** [comment]
> > > orderbook and bestorders widgets became too wide, there is a lot of unused space.
> > 
> > 
> > There is only space when values are small, but if there are values like 12345678.12323343 there is no space any more... look at other orderbooks, like BIDR/KMD.
> 
> checked BIDR/KMD orderbook - there is a lot of empty space still. in the case of large numbers, we can show only significant digits
> 
> <img alt="Screenshot 2021-12-16 at 12 19 53" width="400" src="https://user-images.githubusercontent.com/24797699/146353447-81fe4df7-68ef-477a-b7e7-b374bd450501.png">

That's the problem, if we show only significant digits, rows with few digits and decimals will be misaligned with other rows. That will disturb the user to know which one of the orders has the highest/lowest price

This left empty space does not seem a problem to me

![image](https://user-images.githubusercontent.com/14373103/146357132-9831b980-f38f-44a4-af22-7ecf174e07fe.png)

**Comment by cipig** [comment]
> checked BIDR/KMD orderbook - there is a lot of empty space still. in the case of large numbers, we can show only significant digits

BIDR/KMD was just an example, there are pairs with higher values possible, the bigger the price difference between the 2 coins, the higher/lower the values can get... BIDR/BTC would have higher/lower numbers, but that does not contain orders atm because prices below 0.00000001 are not allowed by mm2
Using dynamic number of decimals would be the ideal solution, just need to make sure the same number of decimals is used for all entries of an orderbook. This is possible, but needs changes to the bignumber.js lib https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1491#issuecomment-993021118
