### ISSUE TITLE
[BUG]: Transaction history CSV has space in column names

### ISSUE THREAD

**Issue by theblackmallard** [KomodoPlatform/atomicDEX-Desktop#1513]
**Describe the bug**
Minor bug: Exporting the transaction history as CSV has an extra space at the beginning of each column name except "Date" for example column names are:
'Date', ' BaseCoin', ' BaseAmount', ' Status', ' RelCoin', ' RelAmount', ' UUID', ' ErrorState'
Which can cause headaches when working with the CSV data later.

**To Reproduce**
1. Open AtomicDEX DEX tab
2. Select Simple trading view
3. Select History
4. Select Export, save CSV
5. Open CSV in any spreadsheet editor

**Expected behavior**
CSV file columns shouldn't begin with spaces.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Version 0.5.3

**Additional context**
Potential locations of additional space:
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/4c023b1780a501a3f13ff285018904289b53a494/src/core/atomicdex/models/qt.orders.model.cpp#L65

in combination with:
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/ebdb7042d6d97a7bf298363d43ab64741e68b5e6/src/core/atomicdex/models/qt.orders.proxy.model.cpp#L288

**Comment by smk762** [comment]
@theblackmallard this should be fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/2021739577
please let us know if it now as expected.
