### ISSUE TITLE
[BUG]: chain_id param from coins.json not using

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1516]
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/config/raw.mm2.coins.cfg.hpp#L88 
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1361

**Comment by Milerius** [comment]
solved by #1520

**Comment by tonymorony** [comment]
it was not, #1520 added this param for custom tokens only

**Comment by tonymorony** [comment]
nvm, re-read PR
