### ISSUE TITLE
Download link for atomicDEX-Desktop misdirects to atomicdex.io 

### ISSUE THREAD

**Issue by SaltyCrocodile** [KomodoPlatform/atomicDEX-Desktop#1536]
A minor but important detail on two great looking sites: 

komodoplatform wallets page links "Desktop" wallet to atomixdex.io. No download link found at atomicdex.io, which only has download links for the mobile wallets afaics.

It would be handy for new users to download in-house from either KP or atomicdex.io, as github can be intimidating for noobs.

**Comment by tonymorony** [comment]
Thank you for the issue opening

There is a desktop download button on atomicdex.io which points to most recent GH release bundle for your OS:

<img width="1015" alt="Screenshot 2021-12-29 at 18 40 49" src="https://user-images.githubusercontent.com/24797699/147658722-0a908dcc-8004-453d-9a24-54309e91c513.png">
