### ISSUE TITLE
[FEATURE REQUEST]: Update dogedex logos

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1537]
[DogeDEX Logo.zip](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/7788968/DogeDEX.Logo.zip)

**Comment by smk762** [comment]
Updated from what was in archive. Not sure if ideal for sidebar (expanded vs retracted).  Should we get rid of the purple?

https://user-images.githubusercontent.com/35845239/147852967-d74b9e20-5c77-4ea1-a957-ef8c38160307.mp4

![image](https://user-images.githubusercontent.com/35845239/147852990-f1266d63-1826-4f80-b5c4-2551dd2f85e3.png)

Tray icons for windows / osx to be tested.

https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/1643715250

**Comment by tonymorony** [comment]
@smk762 thank you for the changes, will check it next week

next time please open PR into branded dex branch instead of direct pushing
