### ISSUE TITLE
[BUG]: Last row of portfolio is tinier than the others

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1567]
<img width="303" alt="Capture d’écran 2022-01-22 à 2 46 18 PM" src="https://user-images.githubusercontent.com/14373103/150641160-254ea17e-2770-4ea9-8e07-8d2aa03ddb9b.png">

**Comment by smk762** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1612
