### ISSUE TITLE
New Dash Logo

### ISSUE THREAD

**Issue by Seko1900** [KomodoPlatform/atomicDEX-Desktop#1581]
It was brought to my attention on Telegram that Dash apparently has a new logo. 

![324697](https://user-images.githubusercontent.com/49843358/151973395-479c1524-aacd-4712-82b1-b704c907047a.png)

**Comment by cipig** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/assets/images/coins/dash.png
same as existing one

**Comment by Seko1900** [comment]
> https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/atomic_defi_design/assets/images/coins/dash.png same as existing one

Correct yes, it's about the mobile AtomicDEX version, sorry.

**Comment by tonymorony** [comment]
Thank you for the issue opening 👍
We'll update dash icon in the next mobile release
