### ISSUE TITLE
[BUG]: withdraw/swap not possible-DigiByte (response too large over 1,000,000 bytes)

### ISSUE THREAD

**Issue by Der-Garten-Pilz** [KomodoPlatform/atomicDEX-Desktop#1585]
Payout or Swap with DigiByte no longer possible.

error message: "Failed to send" and "Failed to place the order"

2022-02-03 06-50-27](https://user-images.githubusercontent.com/98934166/152289021-1eca1341-c322-436c-9e6d-792ddb281030.png)

2022-02-03 06-31-48](https://user-images.githubusercontent.com/98934166/152289244-d0a5ace4-b057-49d3-80b8-78413b8750e0.png)

Debian
Kernel Linux 5.14.0-9parrot1-amd64 x86_64
Mate 1.24.1
atomicdex-desktop-0.5.4-beta-linux-AppImage

i use the address for mining,and have 
because of a high number of deposit

(hope I'm right here!
and thanks for your work)

**Comment by cipig** [comment]
the size of the answer from electrum servers is limited to 1,000,000 bytes
will increase it to 2M for DGB, but the error will happen again sooner or later, so if you mine to this address, consolidate the many UTXOs regularly, or stop mining to it
@Milerius please consider using `utxo_merge_params` https://github.com/KomodoPlatform/developer-docs/blob/master/docs/basic-docs/atomicdex-api-legacy/coin_activation.md#arguments when enabling UTXO coins (except BTC), so the UTXOs are merged automatically

**Comment by Der-Garten-Pilz** [comment]
Thanks to you

here again a good explanation for non-coder
like me :)
https://coinguides.org/transaction-too-large-error-fix/

remains straight
Mfg
