### ISSUE TITLE
[FEATURE REQUEST]: Improve portfolio page for empty wallets 

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1594]
This screen looks quite sad right now for the new users. @SylEze can we not display the chart at all if the USD evaluation of the user's assets == 0 or if assets amount with USD evaluation <= 1 ?

![Screenshot 2022-02-06 at 07 41 30](https://user-images.githubusercontent.com/24797699/152663833-35d82855-036b-44f1-875b-977d3c69874d.png)

**Comment by smk762** [comment]
resolved in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1621
