### ISSUE TITLE
[FEATURE REQUEST]: Don't increase chart diagram on window resize

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1595]
it would be a good enhancement I think to show more assets in a list instead of making a pie diagram giant

standard window now:
![image](https://user-images.githubusercontent.com/24797699/152663925-c67d15a7-268c-4f43-ab1d-bdd0e5256106.png)

maximized window:
![image](https://user-images.githubusercontent.com/24797699/152663932-b0d447ef-047a-411e-abcf-0bbc6871ff1b.png)

**Comment by tonymorony** [comment]
it works extra weird now, lets fix it in this sprint please:

https://user-images.githubusercontent.com/24797699/154210706-2b09d2d1-823d-46e7-a978-8eb3415f247e.mov

**Comment by smk762** [comment]
resolved in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1621
