### ISSUE TITLE
[BUG]: Seed words hinter stop works correctly after not correct word is selected

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1603]
Click on not correct word - words choice will refresh

Click on correct word next time - words choice will not refresh and you'll not have a right option to select

~0:45 on video:

https://user-images.githubusercontent.com/24797699/152888088-ecc23527-f73a-4612-8346-6ff48a4600fc.mov

**Comment by smk762** [comment]
Solved in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1600
