### ISSUE TITLE
Optimize column width in addressbook send to selection.

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1608]
Select address from addressbook - maybe can make columns width so full address visible (can create other issue if you want)
![image](https://user-images.githubusercontent.com/35845239/153156994-eea8b940-8e47-4e06-ad2b-f00f36ee44cd.png)

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1550#issuecomment-1033489507_

**Comment by SylEze** [comment]
Done in #1616
