### ISSUE TITLE
Addressbook layout issues

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1658]
Addressbook related: 

Something weird with select wallet button
![image](https://user-images.githubusercontent.com/35845239/156773043-dd154db0-c928-4bb5-a02e-6288c0c90d06.png)

address selection has no scroll and searchbar goes missing
![image](https://user-images.githubusercontent.com/35845239/156773201-0fbd627d-683c-44ad-ab4d-eee457a6fa1b.png)

`[warning] [main.prerequisites.hpp:92] [3994192]: file:///home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-fdad333.zip/atomicdex-desktop-linux-fdad333/AntaraAtomicDexAppDir/usr/qml/QtQuick/Controls/Private/ScrollBar.qml:100: TypeError: Cannot read property 'hitTest' of null`

error cut off on east side
![image](https://user-images.githubusercontent.com/35845239/156773429-4995d45c-b0ec-4fdb-a083-5418740025b7.png)

Validation for address fails if address not enabled
`resp validateaddress: [{"error":"rpc:211] dispatcher_legacy:160] lp_coins:1362] No such coin: DEX"}]`

Actions column cut off
![image](https://user-images.githubusercontent.com/35845239/156773959-81dddf59-bf90-4df6-8974-b550c4f88735.png)

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1616#issuecomment-1059174238_

**Comment by SylEze** [comment]
Should be fixed in #1616 atm
