### ISSUE TITLE
`View private keys` modal wrapping

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1660]
If we can reduce margin/padding a tiny bit, privkeys will fit on single line without wrap. Most are ok but ETH keys have 3 char wrapped to second line.

seed words wrapping is breaking words in half on line break

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1616#issuecomment-1059175464_

**Comment by SylEze** [comment]
Should be done by #1664, closing.
