### ISSUE TITLE
[BUG] Possible overflow in swap details

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#1715]
i have this in "Confirm Exchange Details":
![image](https://user-images.githubusercontent.com/32116761/161357453-00b47158-4c84-4e52-87ee-39d6b9f56b56.png)

and in swap details
![image](https://user-images.githubusercontent.com/32116761/161357501-6f9f2eb5-8909-45b9-95a0-d6d7426f7f29.png)

guess it's worth trying to use 3 separate lines for ticker, name and price in all this places

_Originally posted by @cipig in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1706#issuecomment-1086437721_

**Comment by smk762** [comment]
closing - combobox wraping and layout has since updated and resolved this issue.
