### ISSUE TITLE
[BUG]: swap history tab does not expand to window height

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1732]
![image](https://user-images.githubusercontent.com/32116761/162215077-d37f1e8e-971d-4879-b103-0e0fada5ce5e.png)

it shows only couple of swaps while there is plenty of room
would be nice if it would expand to window height

**Comment by smk762** [comment]
@cipig can you please check the latest dev and let me know if this is still the case for you? If so, pls let me know your screen res for testing. Seems ok here now/
![image](https://user-images.githubusercontent.com/35845239/166308365-af46a9e0-10bc-4fed-92fd-b817ce906984.png)

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/166313987-e4cab65f-4bf7-4c91-89f1-954464e096d9.png)
still the same here... weird
my screen resolution is 3840x2160, but i don't use fullscreen
