### ISSUE TITLE
[BUG]: orderbook does not expand when resizing window

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1733]
![image](https://user-images.githubusercontent.com/32116761/162216539-511b9854-d20d-4350-9a08-f2161d4c6b7b.png)
resizing the window (in order to be able to see more orderbook entries without scrolling) changes size of  "best orders", but orderbook stays at max 6 entries, no matter how big i make the window
would be nice if orderbook would resize too, the space in "best orders" is unused when there are no other best orders
can "best orders" be changed so it uses 1/3 of the height while orderbook uses 2/3?
making both resizable or separating them from each other would be even better

**Comment by smk762** [comment]
tabs might be good here to give either option the full height.
