### ISSUE TITLE
[FEATURE REQUEST]: Dynamic 2FA

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1743]
**Is your feature request related to a problem? Please describe.**
Suggested via twitter feedback - https://twitter.com/ATroianov/status/1515340477503098884

**Describe the solution you'd like**
We might be able to integrate something like https://www.twilio.com/docs/verify/quickstarts/totp to allow simple dynamic multiOS 2FA

**Additional context**
Current 2FA is limited to Mac/Windows, and uses the host OS password. I assume once hardware wallet support is active that is another 2FA vector, though something like authy would have the widest end user coverage.

**Comment by smk762** [comment]
closing, merged into https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/544

**Comment by r4ndomar** [comment]
https://freeotp.github.io/
https://www.freeipa.org/
https://web.mit.edu/kerberos/
