### ISSUE TITLE
[BUG]: using custom fee when sending does not work

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#1753]
first, the text to select custom fee is not visible in dark mode
![image](https://user-images.githubusercontent.com/32116761/166102059-c2aca8d0-cefe-4ddf-8409-f51a48e01442.png)

and using it does not work, i can't click on "Prepare", it shows this error instead:
![image](https://user-images.githubusercontent.com/32116761/166102097-7f3991e8-77c9-40cb-92df-dbd343685747.png)

if not using custom fees, it works and it would cost $2 txfees, so enough to send $26 of ETH
![image](https://user-images.githubusercontent.com/32116761/166102162-3d47b82d-eceb-4b9c-8581-2ca40c88e5b5.png)

**Comment by smk762** [comment]
@cipig this should now be fixed after https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1789/files#diff-96edacc8529a8a84043664f1b494ae73d9a13ea46b8edcdfc735d70b5630d6af in nomics pr was merged. Can you please confirm?

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/174297543-88220203-61e1-4152-896e-ee0ffb759121.png)
i only have 0.00022313 ETH left ($0.24), which is likely not enough to pay the txfees, but error shown is wrong anyway, it checks the balance of USDC-ERC20

also found that MATIC/PLG20 tokens are treated as UTXO, the form shows up like this
![image](https://user-images.githubusercontent.com/32116761/174298162-9ec1863b-4cfc-414b-aa38-8660460a9b61.png)
which, if used leads to error
![image](https://user-images.githubusercontent.com/32116761/174298297-729b96c9-ae7a-4cd1-9893-fb98a0d03f27.png)
on "Prepare" because of wrong syntax (of UTXO coin withdraw instead of ERC20)

**Comment by smk762** [comment]
missing text fixed, but I think the custom fee syntax error issue persists.
