### ISSUE TITLE
[BUG]: Unthemed elements 

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1754]
We have a few things that seem to be dropping to a default grey color, making them hard to see in darkmode. I've recently fixed the searchbars in dark mode, but there are other cases. Creating this issue for any that might be found so we can fix.

Loading spinners: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1750 / https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1755

Confirmation text:
![image](https://user-images.githubusercontent.com/35845239/166109562-894b871b-2e92-4da5-a811-46474190f5e3.png)

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/166109924-e263aa1f-3b86-4247-ba5f-cea86345be98.png)
the "Min" and "Max" labels for min volume slider in DEX Pro after switching pairs

after you click on an order it looks fine
![image](https://user-images.githubusercontent.com/32116761/166110034-bc674632-63c6-4e59-acbc-01280ffd18e5.png)
