### ISSUE TITLE
[BUG]: russian translation feedback

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/atomicDEX-Desktop#1757]
### Moments without translation in home page

New wallet button
<img width="470" alt="image" src="https://user-images.githubusercontent.com/77272165/166263633-8ec2b8b2-02d3-4989-9c3f-f7fd827285ac.png">
*******
**New wallet page**

<img width="491" alt="image" src="https://user-images.githubusercontent.com/77272165/166264232-7a19ded3-4516-482c-90aa-26232b3370c0.png">

Confirm seed phrase
<img width="469" alt="image" src="https://user-images.githubusercontent.com/77272165/166264351-204bd607-a730-4077-9ef9-6b13cbf33ca3.png">

Password confirmation -> text does not fit
<img width="494" alt="image" src="https://user-images.githubusercontent.com/77272165/166265174-4257a3ac-26aa-4e3b-b28d-dd9ab236ef20.png">
ps:  in import wallet it looks nice
<img width="499" alt="image" src="https://user-images.githubusercontent.com/77272165/166265790-b5cca123-5d95-42b6-84d9-97a83351e630.png">

**************
**Import wallet page**

Allow custom seed window -> buttons
<img width="504" alt="image" src="https://user-images.githubusercontent.com/77272165/166264736-793640b1-f9bc-4eb5-8303-6881aa40efeb.png">

**************

### Log in page

*name* wallet
<img width="359" alt="image" src="https://user-images.githubusercontent.com/77272165/166266564-50bdbed2-df58-44c6-9117-658b34d595f4.png">

Log in button
<img width="280" alt="image" src="https://user-images.githubusercontent.com/77272165/166266382-7fa9210e-00a9-49c7-98c9-870dabafd02f.png">

**Comment by Canialon** [comment]
### Moments without translation in Portfolio tab
<img width="225" alt="image" src="https://user-images.githubusercontent.com/77272165/166260123-30ac3b77-e99a-4083-a0a4-cdd8d0b6aa3e.png">

**Comment by Canialon** [comment]
### Moments without translation in Wallet tab
<img width="379" alt="image" src="https://user-images.githubusercontent.com/77272165/166260372-69b5bcb1-55fc-4ad1-9495-292ba4138780.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/77272165/166261628-d31a7f30-ebee-49c6-b39b-4772f5d66877.png">

Faucet window for Rick and Morty
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/77272165/166261996-d8ab0a39-89ae-40af-b2f3-61317f36e252.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/77272165/166269307-21c535d3-9804-40c6-876c-67c75ac280de.png">

looks like incorrect translation
<img width="212" alt="image" src="https://user-images.githubusercontent.com/77272165/166263039-dd108441-abc2-486d-82b0-2e983180ee78.png">


Here text is too long. "add assets" button
<img width="202" alt="image" src="https://user-images.githubusercontent.com/77272165/166260540-d6cf0a32-c1d6-4a9f-a682-f23d0ce52326.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/77272165/166262329-888ad363-3c34-4e62-8489-2e28bf7872dc.png">

Right click on any asset from the list
<img width="317" alt="Screenshot 2022-05-02 at 17 34 38" src="https://user-images.githubusercontent.com/77272165/166262662-11557bd6-010d-40cd-8195-109657daf59d.png">


Receive window
<img width="553" alt="image" src="https://user-images.githubusercontent.com/77272165/166260703-65419c09-63a5-46ab-99f2-775d095d522c.png">

Send window:
<img width="699" alt="Screenshot 2022-05-02 at 17 26 16" src="https://user-images.githubusercontent.com/77272165/166261144-f14a8cd8-eb17-4543-9cc2-95c070082e7e.png">

What happened with receive button if open wallet tab -> open settings -> change language  (exp: russian->english)
<img width="190" alt="image" src="https://user-images.githubusercontent.com/77272165/166267849-de3322d4-07a9-43df-bb86-3edb63877384.png">
<img width="164" alt="image" src="https://user-images.githubusercontent.com/77272165/166267915-d673d8e4-ce1b-4557-8b5e-6272bc16b274.png">

**Comment by Canialon** [comment]
### Moments without translation in the DEX tab

- Simple / Pro buttons
<img width="164" alt="image" src="https://user-images.githubusercontent.com/77272165/170881234-4beae3e7-1b55-4211-8157-e1c277facdc0.png">

************
**Simple tab**

- Trade tab
<img width="512" alt="image" src="https://user-images.githubusercontent.com/77272165/170881703-e7d858b0-5f7d-42f4-8503-36f7ac56ccf6.png">


- trade -> select coin -> token column
<img width="463" alt="image" src="https://user-images.githubusercontent.com/77272165/170881671-a7096a9c-df96-4b58-814b-cf3e1d53a64d.png">

- loading wallet
<img width="424" alt="Screenshot 2022-05-29 at 18 52 23" src="https://user-images.githubusercontent.com/77272165/170882026-5cfbb808-3d29-4cde-b01a-8c61687100d1.png">

- swap now button 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/77272165/170882133-d69fcd72-0adf-4b40-9e6a-15db3c486c96.png">

-confirm exchange details window
<img width="691" alt="Screenshot 2022-05-29 at 18 57 20" src="https://user-images.githubusercontent.com/77272165/170882844-84e0a2b5-4a6f-4608-8199-7fa25745c5b5.png">

-selected order was deleted window
<img width="1032" alt="Screenshot 2022-05-29 at 19 08 55" src="https://user-images.githubusercontent.com/77272165/170883026-c16369d4-98d2-4a3b-a040-c2b46028eb4f.png">

- дл] -> для
<img width="602" alt="Screenshot 2022-05-29 at 19 10 32" src="https://user-images.githubusercontent.com/77272165/170883045-08099186-2d39-4875-9324-7fc6da5d81fa.png">

- orders -> show button
<img width="413" alt="Screenshot 2022-05-29 at 19 13 42" src="https://user-images.githubusercontent.com/77272165/170883073-a6d73e8c-50fb-41ec-92d3-ce58dc53ccbf.png">

- swap deteils -> order type
<img width="739" alt="Screenshot 2022-05-29 at 19 15 36" src="https://user-images.githubusercontent.com/77272165/170883111-e7d52252-9077-4701-a9ca-5439424ea3de.png">

- order count, if last digit is:
1 ордер
2-4 ордера
5-10 ордеров
<img width="493" alt="Screenshot 2022-05-29 at 19 16 06" src="https://user-images.githubusercontent.com/77272165/170883240-b4f06bc3-6854-46d4-b695-27c5ced34f6e.png">

- orders -> filters -> filters settings
<img width="416" alt="image" src="https://user-images.githubusercontent.com/77272165/170883540-e1970e4c-a845-4473-9ec9-8f0470882016.png">

************************************

**Pro tab**

- pro view settings
-> display settings
-> list goes out of window
<img width="218" alt="image" src="https://user-images.githubusercontent.com/77272165/170883884-ee827425-d1a1-448f-b66a-932976de2828.png">

- 'loading maker data' for graphic 
<img width="751" alt="Screenshot 2022-05-29 at 19 41 12" src="https://user-images.githubusercontent.com/77272165/170884101-166d767f-c1c3-4ccd-bc0e-4a516b01ed56.png">

- maker data window
<img width="702" alt="Screenshot 2022-05-29 at 19 44 16" src="https://user-images.githubusercontent.com/77272165/170884217-1a037a70-add5-4108-953d-8d5c595c3ba8.png">

**Comment by Canialon** [comment]
I hope this issue is over.

**Comment by SirSevenG** [comment]
Also an overflow on notifications dropdown:
![rus_overflow_notifications](https://user-images.githubusercontent.com/44422309/202216489-cd5879db-44e0-4e45-88ac-901ee9c71601.png)
