### ISSUE TITLE
Addressbook restyle tweaks 🎉

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1770]
**Crashing:**
- [x] Found on Windows 10:
1. create any contact 
2. edit this contact -> delete the name, like "", nothing
3. press the "confirm" button
4. edit this contact -> enter any name
6. press the "confirm" button
==> application crashed D':
logs: [2022-05-13-16-08-26.log](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/8689337/2022-05-13-16-08-26.log)

- [x]  When clicking "send" button for smartchain, app crashes. In this case, user should be given a pop-up list of smartchains to complete the selection.

https://user-images.githubusercontent.com/35845239/168439634-e48e4d3c-6301-4e84-91f5-7e51462f786c.mp4

https://user-images.githubusercontent.com/35845239/168439631-58889c80-0f57-4774-97a9-088731b25ef4.mp4

```
[22:16:06] [error] [mm2.service.cpp:501] [35910]: error answer for tx or my_balance: {
    "error": "rpc:211] dispatcher_legacy:160] lp_coins:1419] No such coin: Smart Chain"
}
[22:16:06] [error] [main.prerequisites.hpp:112] [35899]: stacktrace:  0# signal_handler(int) at main.cpp:?
 1# 0x00007F30EB7D50C0 in /lib/x86_64-linux-gnu/libc.so.6
 2# atomic_dex::wallet_page::get_ticker_infos() const in ./atomicdex-desktop
 3# atomic_dex::wallet_page::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in ./atomicdex-desktop
 4# 0x00007F30EE2719CE in /home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-abook.zip/atomicdex-desktop-linux-0603cb0/AntaraAtomicDexAppDir/usr/bin/../lib/libQt5Qml.so.5
 5# 0x00007F307022DFBF
```

**Comment by smk762** [comment]
- tags background is difficult to see in dark mode
![image](https://user-images.githubusercontent.com/35845239/168429434-25bb79a6-08c8-44ba-9015-e93146ef8858.png)

- no icon for "smartchain"
![image](https://user-images.githubusercontent.com/35845239/168429466-018935d5-ae14-41fc-a396-06cc46533522.png)

- When clicking "send" button for smartchain, app crashes. In this case, user should be given a pop-up list of smartchains to complete the selection.

https://user-images.githubusercontent.com/35845239/168429548-27a460e2-921c-42ab-8d17-833c8254e692.mp4

https://user-images.githubusercontent.com/35845239/168430492-a71ac456-24e1-455e-962c-47c1a12eb9eb.mp4

```
[22:16:06] [error] [mm2.service.cpp:501] [35910]: error answer for tx or my_balance: {
    "error": "rpc:211] dispatcher_legacy:160] lp_coins:1419] No such coin: Smart Chain"
}
[22:16:06] [error] [main.prerequisites.hpp:112] [35899]: stacktrace:  0# signal_handler(int) at main.cpp:?
 1# 0x00007F30EB7D50C0 in /lib/x86_64-linux-gnu/libc.so.6
 2# atomic_dex::wallet_page::get_ticker_infos() const in ./atomicdex-desktop
 3# atomic_dex::wallet_page::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in ./atomicdex-desktop
 4# 0x00007F30EE2719CE in /home/smk762/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-abook.zip/atomicdex-desktop-linux-0603cb0/AntaraAtomicDexAppDir/usr/bin/../lib/libQt5Qml.so.5
 5# 0x00007F307022DFBF
```
- Smartchain / BEP20 / ERC20 etc options not visible in address selection drop down. If editing a "smart address" entry, the dropdown reverts to LTC.

https://user-images.githubusercontent.com/35845239/168433329-8a5139f9-4cb4-481a-8d30-c35d8d3bdf5d.mp4

- Spacing between addressbook entries could be reduced (see above video and space between hovered backgrounds)

- Unexpected behaviour when using send button on coins which are not enabled. In this case, I would expect a pop up to enable the coin, and if cancelling the enable, it should not appear as the selected coin in wallet screen afterwards.

https://user-images.githubusercontent.com/35845239/168429703-5c9fe088-287f-44c2-b2b3-164d780b97f3.mp4

- No "do you confirm" pop up when clicking "delete"" for a contact.

https://user-images.githubusercontent.com/35845239/168429779-96d42905-53c8-4af4-a60f-fc9517c6490a.mp4

- Button text too short - we should have this say "add address"
![image](https://user-images.githubusercontent.com/35845239/168429924-6aafe1fc-6280-44f1-8691-510412b85041.png)

- Add "tag button" should have same  styling color as add/close buttons (incl on hover)

**General impression of layout:**
      -  There is dead space which could be freed up to make the scrollable address list area taller.
![image](https://user-images.githubusercontent.com/35845239/168430192-a05c2a8e-0821-412d-b36b-226818a38a88.png)

- Contact name input would be nice to use similar to the notes input on sent transactions:
![image](https://user-images.githubusercontent.com/35845239/168430232-6ac3566c-226c-41db-99c5-35745470131c.png)

- Rather than an "+ Add" button below the scrollable, address list, we could make a small `+` button to the right of the `Address list` title. Same applies for the `Tags` title. These changes would almost double the available space for the scrollable address list area. 

- A slight change to background color of address list area like below might be a good idea, along with a "There are no saved addresses for this contact" message if no addresses in list. Same for tags area, along with a `no tags for this contact` message if no tags are set. Similar to below:

![image](https://user-images.githubusercontent.com/35845239/168430372-485fc62f-631b-4143-9496-32b1a7407b59.png)

- it would be cool to be able to add addresses to the addressbook via a button next to addresses on transaction details modal (see above).

- This input gives no indicator when focused (i.e. blinking cursor or slight background / border change)

![image](https://user-images.githubusercontent.com/35845239/168430723-16e3bfe1-ef69-4ecc-9cc4-3a91937e0e43.png)

- Error message would be good to be centered between buttons and inputs, and perhaps center aligned.

![image](https://user-images.githubusercontent.com/35845239/168430867-3b352ccb-333f-49b1-bcd0-c73b4e8ccef7.png)

- Edit state is not reset when switching contacts
![image](https://user-images.githubusercontent.com/35845239/168431258-fd716d6a-cf47-41e1-88d9-86c358caaaf0.png)

- coin selection dropdown might benefit from slightly different background and adding a search field.
![image](https://user-images.githubusercontent.com/35845239/168431498-375b1cba-e482-493d-9143-0369259ef395.png)

- contact address list not shown in main screen after adding (If switching tabs to wallet and back, they are seen)

https://user-images.githubusercontent.com/35845239/168432044-3df6a61f-d15a-4d8c-8d4a-8b34c9d1338b.mp4

- Address input fields should be renamed to `Label` and `Address`. using "field" and "key" might confuse grandma.

- The `Label: Address` format used on main age could also be used on the edit contact page. This would allow for more addresses visible in the scrolling area. A space should be added after the `:` to allow for wordwrap if long label/address needing extra line.

![image](https://user-images.githubusercontent.com/35845239/168432216-279191c5-ec5e-4952-8be1-e7e16515a8a3.png)
![image](https://user-images.githubusercontent.com/35845239/168432254-ff98aacd-f2f9-4363-91fc-034c7606ede5.png)

- Do we need the extra space below the addresses here?
![image](https://user-images.githubusercontent.com/35845239/168433637-43f93e73-a5ce-40cc-bec7-850693c31215.png)

**Comment by smk762** [comment]
- remove assets key
- make tags colorful 
- remove the "no tags" test
- add a background for the "edit address" button
- update the "edit contact" window as it is on Figma
- add horizontal center alignment to elements 

![image](https://user-images.githubusercontent.com/77272165/168335995-15aa3547-40c8-41a4-8105-6fdf42311dfd.png)


![image](https://user-images.githubusercontent.com/77272165/168334937-b688fce9-f08b-4432-a807-f26241e75f0d.png)
![image](https://user-images.githubusercontent.com/77272165/168334981-51b81b2b-25ad-4710-8c62-dc2424714e0e.png)

**Comment by smk762** [comment]
**UX**
- [ ] Add a "do you confirm?" pop up when clicking `delete` for a contact.

- [ ] Streamline new contact creation
```
And I am a little bit unsure about this way to create a new contact. I mean when
 I press the "+new contact" button, I expect to see a big window where I can add the
name of the contact, and add some address and tags. But now to do that I must create a
contact name -> find this contact among other contacts -> press the "edit" button -> and
only then I can add some addresses. It's really annoying to do so many steps.
So, is it possible to show the "edit contact" window after pressing
the "+new contact" button to avoid unnecessary actions?
```

- [ ] The `Label: Address` format used on main age could also be used on the edit contact page. This would allow for more addresses visible in the scrolling area. A space should be added after the `:` to allow for wordwrap if long label/address needing extra line.
![image](https://user-images.githubusercontent.com/35845239/168432216-279191c5-ec5e-4952-8be1-e7e16515a8a3.png)
![image](https://user-images.githubusercontent.com/35845239/168432254-ff98aacd-f2f9-4363-91fc-034c7606ede5.png)

- [ ] Tags background is difficult to see (make tags colorful)
![image](https://user-images.githubusercontent.com/35845239/168429434-25bb79a6-08c8-44ba-9015-e93146ef8858.png)
![image](https://user-images.githubusercontent.com/77272165/168334937-b688fce9-f08b-4432-a807-f26241e75f0d.png)

- [ ] If no tags for entry, leave area blank (on main page). 

- [ ]  A slight change to background color of address list area like below might be a good idea, along with a "There are no saved addresses for this contact" message if no addresses in list. Same for tags area, along with a `no tags for this contact` message if no tags are set. Similar to below:
![image](https://user-images.githubusercontent.com/35845239/168430372-485fc62f-631b-4143-9496-32b1a7407b59.png)

**Comment by smk762** [comment]
**Enhancements**
- [ ] It would be cool to be able to add addresses to the addressbook via a button next to addresses on transaction details modal (see above).

- [ ] Coin selection dropdown might benefit from slightly different background and adding a search field.
![image](https://user-images.githubusercontent.com/35845239/168431498-375b1cba-e482-493d-9143-0369259ef395.png)

- [ ] Rather than an "+ Add" button below the scrollable, address list, we could make a small `+` button to the right of the `Address list` title. Same applies for the `Tags` title. These changes would almost double the available space for the scrollable address list area.

**Comment by SylEze** [comment]
> * Coin selection dropdown might benefit from slightly different background and adding a search field.

We should not use different colors when component has already one defined in themes, it will make the application harder to maintain accross other themes

In that case reducing dropdown height should be sufficient
