### ISSUE TITLE
[BUG]: wrap amount in the coin transaction history

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/atomicDEX-Desktop#1844]
the context of a transaction in the coin transactions list is not center-aligned if the amount takes two lines.

UPD:
should remove text wrap  if the string is too long for a single line

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/77272165/177058451-b3e4892a-cb7d-46f7-bf6d-3e00802ae3c3.png">

**Comment by cipig** [comment]
can we make sure it's always only one line?

**Comment by Canialon** [comment]
> can we make sure it's always only one line?

alignment with amount in one line:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/77272165/177060143-a01ff56f-2569-4e82-9921-2845c8b86fad.png">

alignment with wrap amount :
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/77272165/177060199-9f6b5544-4e58-49d5-afa3-d1ac0ae5d67e.png">
I meant the horizontal alignment

**Comment by Canialon** [comment]
> You meant vertical alignment right ? @Canialon

horizontal -_-

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/77272165/177165393-97a36538-3c06-4208-b88e-d30353fb5baa.png">

**Comment by cipig** [comment]
> > You meant vertical alignment right ? @Canialon
> 
> horizontal
> 
> <img alt="image" width="1648" src="https://user-images.githubusercontent.com/77272165/177165393-97a36538-3c06-4208-b88e-d30353fb5baa.png">

that's what i meant... if the string "DOGE-BEP20 200" would be one line and not two, the problem wouldn't exist. if the string is too long for single line on certain resolutions, remove "DOGE-BEP20" from the string and keep only the value... it's clear anyway that it's DOGE-BEP20 because you are looking at DOGE-BEP20 wallet
