### ISSUE TITLE
[FEATURE REQUEST]: Improve 2FA setting

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1862]
Currently we have a setting in mac/windows that, if turned on, prompts user to enter password when sending funds out.
There exists a potential case for a malicious user to bypass this by simply entering settings and turning the option off. To avoid this, we should make user enter their password when turning off this option.

While 2FA is turned on, currently withdrawals are password protected, but orders can still be placed and executed. This action should also require password input.

**Comment by SylEze** [comment]
> Currently we have a setting in mac/windows that, if turned on, prompts user to enter password when sending funds out. There exists a potential case for a malicious user to bypass this by simply entering settings and turning the option off. To avoid this, we should make user enter their password when turning off this option.

How did we not even think of that :joy:
