### ISSUE TITLE
[BUG]: Link to explorer displaying in every case when there is no transactions for asset

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#1867]
**Describe the bug**
Right now message with the link to explorer showing even if there is just no transactions (but tx history is working in general).
What imo is a bit confusing and looks not pretty (especially for the new user when he/she don't have txs at all)

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/24797699/178789571-ee941dde-adc3-42e8-8ff2-62b76cc48ada.png">

**Comment by smk762** [comment]
In current dev it looks like this:
![image](https://user-images.githubusercontent.com/35845239/178910040-cc26ca33-caf5-412b-821a-16df3c050ccf.png)

Is that ok or should we remove link and change message to something else?
