### ISSUE TITLE
[BUG]: new addresses are not immediately displayed in the drop-down list of addresses for contact

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/atomicDEX-Desktop#1868]
A new address does not add to the address book immediately. To see the addresses which were added to the contact you need to reopen the address book tab

**To reproduce:**
1. log in to your wallet
2. go to the address book
3. create a new contact
4. add an address to this contact
5. open the dropdown address list of this contact
<img width="678" alt="image" src="https://user-images.githubusercontent.com/77272165/178824851-94e27131-9a5a-4324-ba95-9de844370b23.png">

**Actual result:**
The new address is not displayed in the dropdown list. 

**Expected result:**
The new address appeared in the dropdown list immediately.

**To fix:**
To make it visible you need to reopen the address book tab.

**Video example:**

https://user-images.githubusercontent.com/77272165/178825925-5854c162-44a6-4b43-b0d7-3552ba5bce50.mov

note: editing address works fine and without extra-step

**Comment by smk762** [comment]
I can confirm this on my side. New addressbook entries will appear for existing contacts, but when adding addresses to a contact which was just created, added addresses do not appear until cycling to another tab and back
