### ISSUE TITLE
[BUG]: AtomicDex-desktop beta version 5.6 - Amount/Price is not being trimmed/wordwrapped (falling out of it's container/overlapping)

### ISSUE THREAD

**Issue by bobpepers** [KomodoPlatform/atomicDEX-Desktop#1903]
**Describe the bug**
Amount/Price looks wack

**Expected behavior**
A nicely trimmed amount  or a wordwrap when it exceeds the boundries

**Screenshots**
![image](https://user-images.githubusercontent.com/40283955/182298765-884c6cd6-90aa-43da-9ad6-15058e49b8d8.png)
![image](https://user-images.githubusercontent.com/40283955/182298786-91c0343b-72dd-4878-a55e-9ecd0ff506b3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by cipig** [comment]
related: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1721
