### ISSUE TITLE
[FEATURE REQUEST]: Change the limitation in the price API of ADEX: 

### ISSUE THREAD

**Issue by ilienongithub** [KomodoPlatform/atomicDEX-Desktop#1904]
Change the limitation in the price API of ADEX... "it has a setting that removes prices if timestamp is older then 10 minutes" Change to 24 hours

At the moment we have a token ILN on the polygone network, and even with trades every 3 to 4 minutes it is not showing trades on Nomics for up to 1 hour later.
Also New small cap tokens may not have a trade every 10 mins
**Describe the solution you'd like**
Change the limitation in the price API of ADEX to a longer time 12 or 24 hours.

**Describe alternatives you've considered**
Maybe allow user to selectd in seetings how often this should be updated 10min , 1 hour, 12 hours or 14hours.

**Additional context**
https://youtu.be/43mel9FY5w8 video showing our current problim

**Comment by ilienongithub** [comment]
Ok so we have been talking to dodo and nomics to speed up trades showing. I have been
<img width="1381" alt="Screenshot 2022-08-03 at 21 31 04" src="https://user-images.githubusercontent.com/90349751/182706574-3d83a323-d941-4e86-89ad-8ae03a182105.png">
 testing for the last few hours with trades every few minutes but price never updated. In attched image you see trades hapening every 4 min. Last one at 9.29 pm and if you look at the top right corner you wil see the current time of 21.31pm so less than 2 min but in ADEX no price showing. Hope this helps

**Comment by smk762** [comment]
This doesn't seem like something that can be changed in desktop app. The prices endpoint has a parameter `expire_at` which will filter out stale data older than this value (in seconds).
If nomics increased this value could include older trades, but wont do anything for price updates lag. This is again likely something on nomics side e.g. temporal smoothing or suspected wash trade filtering.

**Comment by ilienongithub** [comment]
thanks for update. Got this from cipi. "price is not shown in https://prices.komodo.live:1313/api/v2/tickers?expire_at=600
but shows up in my own endpoint https://prices.cipig.net:1717/api/v2/tickers?expire_at=600" does that help?

**Comment by cipig** [comment]
> This doesn't seem like something that can be changed in desktop app. The prices endpoint has a parameter `expire_at` which will filter out stale data older than this value (in seconds).

expire_at could set much higher here https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/api/komodo_prices/komodo.prices.cpp#L83
i for example use 24h (86400) in my builds... this might be too high, but 10 minutes is unrealistic for most small cap coins

**Comment by smk762** [comment]
We can increase that in the app, but prices source from nomics using the same API would need to make the same changes for it to display there.

What would be an optimal value to cover small caps?

**Comment by ilienongithub** [comment]
I know cipi version of ADEX which I run on my mac has tracked the price for months and is set for 24 hours.
The wallet headline has  on the right; ( price change 24 hours ) see attached screenshoot. to me to have it removed only if no trade in the last 24 hours makes sense.  But if that’s to long maybe stretch it to 1 hour and I will track and see if it solve the problem. Kind Regards Liam

<img width="1014" alt="Screenshot 2022-08-24 at 11 47 52" src="https://user-images.githubusercontent.com/90349751/186401289-45a175b5-a844-4481-9289-d3b7aeedf7e0.png">
.

**Comment by cipig** [comment]
> thanks for update. Got this from cipi. "price is not shown in https://prices.komodo.live:1313/api/v2/tickers?expire_at=600 but shows up in my own endpoint https://prices.cipig.net:1717/api/v2/tickers?expire_at=600" does that help?

this has nothing to do with the expire_at setting, the setting is in the ADEX app, not on the endpoint
this can only be explained by different configs on those endpoints, my endpoint is using config from https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/0.5.6-coins.json (dev-branch)

**Comment by cipig** [comment]
> We can increase that in the app, but prices source from nomics using the same API would need to make the same changes for it to display there.
I don't understand the part about changes on nomics.
> 
> What would be an optimal value to cover small caps?
Good question. The expire_at was intended as a security setting, eg if Binance API is showing old prices (markets removed, no more trades, technical problems, maintenance), but is only important for the trading bot, not that much for ADEX Desktop, so we could very well use 1-4h.

**Comment by tonymorony** [comment]
`not that much for ADEX Desktop, so we could very well use 1-4h.`

Agreed, opened PR which set it to 6 hours: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1945
