### ISSUE TITLE
Update build docs

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1979]
Now that the repo doesn't include libwally.dll, windows build docs need to be updated to include building it from source. 

Linux CI is also due for an update from 18.04 to 20.04, so these docs may also need some updates for dependencies etc.

Build instructions have also recently been rearranged so that each OS in in a separate section.
https://github.com/KomodoPlatform/atomicDEX-Desktop/wiki/Build-Instructions

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1936#issuecomment-1249240668_

**Comment by SirSevenG** [comment]
@smk762 
https://github.com/KomodoPlatform/atomicDEX-Desktop/wiki/Build-Instructions/3325f1798f61491eb23b0ac19456d0e8741a2e60

Included updates to aqt commands from https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1987

Please recheck phrasing

**Comment by smk762** [comment]
> 
Looks good thanks. made a couple of minor edits :+1:
