### ISSUE TITLE
[FR]: Coin delistings

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1993]
Some coins have been unable to activate due to down electrums for a while now, and can probably be delisted.
As we don't have a formal delisting process, we should add one to the README. e.g.

1. Create issue for delisting specific coin.
2. Tag the user who initially PR'd the change to include the coin (check desktop and coins repo)
3. If user has contact info in coins repo PR, reach out for confirmation.
4. If no response after 2 weeks, do PR to remove coin.

**Comment by ologunB** [comment]
I have a list of not-working-coins [  'CIPHS', 'GMS', 'USDI', 'PIC', 'SCA', 'ZEC', 'LTFN', 'IC']. the [script](https://gist.github.com/smk762/56112c9acabf3333ca4af0b9efe81661) does work a deal, but for some reasons, some failed coins still install on desktop/app

**Comment by smk762** [comment]
With new unified coin config, this will occur in the coins repo.
