### ISSUE TITLE
[BUG]: Paste clipboard bug during password creation 

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/atomicDEX-Desktop#1994]
**Describe the bug**
Clipboard past bug on the create password step

**To Reproduce**
1. copy any text to the clipboard 
2. start creating or importing a wallet
3. on the "create password" step don’t click o the input field, 
4. past the text using the keyboard 

**Actual behaviour**
Text from the clipboard was pasted into the "name wallet" field

**Expected behaviour**
~~Past test into the password input field~~ Text should not be pasted inside `Wallet Name` field

**Operating Environment(s):**
 - OS: macOS and Windows 10
 - AtomicDEX Version: 0.5.6-beta

https://user-images.githubusercontent.com/77272165/193248648-74f31676-96ab-476a-b935-9452130ca64b.mov

**Comment by SylEze** [comment]
I'm not sure if the expected behaviour is good because in the last step the password field does not have the focus and should not therefore catch paste events.

But in any case it should not paste the text inside the wallet name field.
