### ISSUE TITLE
[FR]: Spanish Translation

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#2009]
PTYX has kindly provided translations in spreadsheet format. This needs to be converted to .ts file, and test build made available to native speakers in the community.

**Comment by Canialon** [comment]
Now Spanish translation has at least these bugs (0.5.7 mac):

- address book -> add contact button
<img width="165" alt="image" src="https://user-images.githubusercontent.com/77272165/202325873-35185974-30a6-486c-9374-ec2f7930d482.png">


- support page overflow:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/77272165/202325981-7f051069-451f-4f35-8358-cff5bcbf5c0f.png">
