### ISSUE TITLE
historical price for charts

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX-Desktop#203]
Plz add a local persistence layer and store the price of each asset at suitable intervals - whenever possible do use DEX orderbooks for price eval - in case of longer offline times plz fill the "gaps" with webAPI prices.  

@artemii235 @tonymorony probably time for us to start thinking about adding such a `historic_price(coin, offset)` or `avg_price(coin, startdate, enddate)` functionality or something along those lines to API. I know we do not store these price metrics thus not persisting them in the network - however, lets start brainstorming this layer. (we should keep exotic or "unreliable" things out of this, CC, external endpoints, etc. - goal is direct API integration)

**Comment by tonymorony** [comment]
>@artemii235 @tonymorony probably time for us to start thinking about adding such a historic_price(coin, offset) or avg_price(coin, startdate, enddate) functionality or something along those lines to API. I know we do not store these price metrics thus not persisting them in the network - however, lets start brainstorming this layer. (we should keep exotic or "unreliable" things out of this, CC, external endpoints, etc. - goal is direct API integration)

Result of brainstorm:
https://github.com/KomodoPlatform/atomicDEX-API/issues/654

**Comment by tonymorony** [comment]
For 0.1.5 we've decided to go ahead with own endpoint-cacher server for coinpaprika prices API

**Comment by Milerius** [comment]
Switched to coingecko recently
