### ISSUE TITLE
[BUG]: GRMS coin electrum servers

### ISSUE THREAD

**Issue by Miner113** [KomodoPlatform/atomicDEX-Desktop#2077]
Replace electrum servers for the GRMS coin with new ones for release in the next release
"electrum": [
{
"url": "electrum.grms.pw:17485"
},
{
"url": "electrum1.grms.pw:17485"
},
{
"url": "electrum2.grms.pw:17485"
},
{
"url": "electrum3.grms.pw:17485"
}

**Comment by smk762** [comment]
Issue has been move to coins repo
