### ISSUE TITLE
[BUG]: Empty portfolio / empty wallet (without coins) on 6be7e94c2a4e24d9e3d7370ae50b4a1b794c006b

### ISSUE THREAD

**Issue by DeckerSU** [KomodoPlatform/atomicDEX-Desktop#2078]
After update to 6be7e94c2a4e24d9e3d7370ae50b4a1b794c006b on `Win64` my portfolio and coins list looks like this:

Portfolio tab:
![image](https://user-images.githubusercontent.com/22120003/202016124-65cee6d5-32a8-40ce-9eb2-ceadfb9b12a6.png)

Wallet tab:
![image](https://user-images.githubusercontent.com/22120003/202016234-a545b2ae-c739-42fb-840b-37613266bb93.png)

But if I launch old version `0.5.6a`, built from `master` portfolio and tx history are there.

I did small investigation and found that it depends on `C:\Users\Decker\AppData\Roaming\atomic_qt\config\0.5.7-coins.esxi.json` file content:
[0.5.7-coins.esxi.zip](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/10015951/0.5.7-coins.esxi.zip)
If delete it - all starts showing normally. So, a way to reproduce probably:

1. Build latest `dev` version (6be7e94c2a4e24d9e3d7370ae50b4a1b794c006b) for Win64.
2. Copy `0.5.7-coins.esxi.json` file to the `C:\Users\Decker\AppData\Roaming\atomic_qt\config\` and rename it according to your wallet name (in my case it's `esxi`).
3. Start the AtomicDEX ... 

Also "Reset wallet configuration" seems helps in this case, but it's indeed a question why AtomicDEX built from `master` works with this JSON and `dev` - doesn't.

**Comment by smk762** [comment]
This issue is due to changes in the coins config structure.
Related: https://github.com/KomodoPlatform/coins/pull/525
So older coins files used on newer builds will enter this state until assets reset.

**Comment by DeckerSU** [comment]
You mean differences in `nodes` array?

Old:
```
    "nodes": [
      "https://node.komodo.live:8080/avalanche",
      "https://api.avax.network/ext/bc/C/rpc"
    ],
```
New:
```
    "nodes": [
      {
        "gui_auth": true,
        "url": "https://node.komodo.live:8080/avalanche"
      },
      {
        "url": "https://api.avax.network/ext/bc/C/rpc"
      }
    ],
```
If so, may be auto-conversion is possible? Or any other solution to don't allow user see such bug. For example, it can detect at start in which state `nodes` array is: if it contains strings - it's old format, if it contains objects - new format and do conversion.

**Comment by smk762** [comment]
most users shouldn't encounter this problem (if downloading release builds only) as coins files are force-refreshed when the version number changes.

**Comment by DeckerSU** [comment]
May be, but I still don't understand why to don't do needed check inside `check_for_reconfiguration` and delete file if nodes in old format:
```cpp
fs::path actual_version_filepath = cfg_path / (std::string(atomic_dex::get_raw_version()) + "-coins."s + wallet_name + ".json"s);
if isNodesPreviousFormatConfig(actual_version_filepath) {
   fs_error_code ec;
   fs::remove(actual_version_filepath, ec);
}
```
`isNodesPreviousFormatConfig` also can be implemented relative easy, just need to parse json with `nlohmann`, iterate all coins and if just one of the `nodes` array element is `string` instead of object, than consider file format as old. Something like this:
```cpp
bool isNodesPreviousFormatConfig(const fs::path& actual_version_filepath){

    std::ifstream actual_config_file(actual_version_filepath);
    nlohmann::json actual_config_data;

    try {
        actual_config_data = nlohmann::json::parse(actual_config_file);
    }
    catch (nlohmann::json::parse_error& ex)
    {
        return true; // error in parsing - assume old (previous) format with further delete
    }
    
    for (auto& el: actual_config_data.items()) {
        if (el.value().contains("nodes")) {
            nlohmann::basic_json nodes = el.value().at("nodes");
            if (nodes.is_array()) {
                for (auto& a_el : nodes) {
                    if (a_el.is_string()) {
                        return true;
                    }
                }
            }
        }
    }

    return false;
}
```

**Comment by smk762** [comment]
cc: @SylEze
