### ISSUE TITLE
[BUG]: Spanish translation is available, yet it misses icon and short name on login page

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Desktop#2083]
![image](https://user-images.githubusercontent.com/44422309/202193263-e7cc728a-670e-4368-b431-215848ef5363.png)

Looks fine in Settings -> Language

**To Reproduce**
Logout/Start a fresh app, click on language slector

**Comment by SylEze** [comment]
Do you see any QML warning/error on your standard output ?

**Comment by SirSevenG** [comment]
No, didn't see any. Will recheck to be sure.
