### ISSUE TITLE
[enhancement]: Notifications do not change language on locale switch

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Desktop#2086]
**Describe the bug**
Notifications received keep the locale/language they were generated with.
![notifications_locale_same](https://user-images.githubusercontent.com/44422309/202217074-f0d4b41d-a59c-4426-9269-e840845fe01e.png)

1. Login to wallet, select locale A
2. make a swap/a few transactions to generate notifications
3. switch to a different locale
4. Open notifications dropdown
5. Dropdown button has new locale, yet notification themselves keep the previous language

**Comment by SylEze** [comment]
This one is not that urgent and is not really a bug, let's do it in next iteration

Looking at the code I think this notifications modal needs some refactoring !
