### ISSUE TITLE
[bug] Translation error

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#2089]
Now Spanish translation has at least these bugs (0.5.7 mac):

- address book -> add contact button
<img width="165" alt="image" src="https://user-images.githubusercontent.com/77272165/202325873-35185974-30a6-486c-9374-ec2f7930d482.png">

- support page overflow:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/77272165/202325981-7f051069-451f-4f35-8358-cff5bcbf5c0f.png">

_Originally posted by @Canialon in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2009#issuecomment-1317898221_

**Comment by smk762** [comment]
@Canialon what screen resolution is your mac running at? This button should be sized in relation to the text within
![image](https://user-images.githubusercontent.com/35845239/202375664-624f4e7a-61af-4315-8b4c-6eeb11672c7a.png)

**Comment by Canialon** [comment]
> what screen resolution is your mac running at? 

2560x1600 px

**Comment by smk762** [comment]
Replicated, thanks. Looks like some elements which derive size from their content do not resize when changing language in user settings rather than before logging in. We have enough space to make this button large enough to cover all with a static width.
