### ISSUE TITLE
[BUG]: faucet button alignment

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#2100]
To make room for the Alert icon if zombie faucet not yet usable (during activation), alignment was changed to the same as send/receive/swap buttons with variable margin offset depending on whether or not the alert icon is visible.
![image](https://user-images.githubusercontent.com/35845239/202652167-caf7f184-2c21-4a04-ae86-ec530c915a37.png)

It looks a bit weird now - to balance it out, we should add a "faucet" icon to  the right of the text similar to the arrows present on the other buttons .

**Comment by SylEze** [comment]
I do not like the idea to have one icon at this place, can we just reduce button size or center the text ?

**Comment by smk762** [comment]
Text centering gets  a bit messed up if the Alert Icon present, though that can probably be dealt with in a different way
I have it like this at the moment, was about to push
![image](https://user-images.githubusercontent.com/35845239/202684101-b44a79ad-2c53-42e0-ba09-0ec6d1311f6f.png)
![image](https://user-images.githubusercontent.com/35845239/202684202-43af2131-8025-4038-a898-c31046dba644.png)
![image](https://user-images.githubusercontent.com/35845239/202684321-827f1d02-c178-4903-b65b-382a24e2d83a.png)
![image](https://user-images.githubusercontent.com/35845239/202684378-73933d73-fcd6-40a5-b0ad-9e07d2e8f967.png)

**Comment by SylEze** [comment]
Looks better than I thought 😅 
You can push I guess

**Comment by SylEze** [comment]
Fixed by a6ffb57ff1f57fe0db858cc9d5d3fd09f97d0d80
