### ISSUE TITLE
[BUG] Trade confirmation tickers not same as selected in order

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/atomicDEX-Desktop#2105]
![image](https://user-images.githubusercontent.com/21057518/203459628-d1bc5795-8a5f-445c-aee6-0ab94aef770c.png)
Parts of it say KMD/Komodo and none of it should when making a TKL/ARRR trade

**Comment by smk762** [comment]
Can you pls attach logs or replication steps

**Comment by TheComputerGenie** [comment]
> or replication steps

Click "DEX" tab in left-hand menu
Set left coin to ARRR
Set right coin to TKL
Click "Buy ARRR"
Set Price
Set Volume
Click "START SWAP"

"Confirm Exchange Details" shows KMD as coin instead of ARRR
"Confirm Exchange Details" shows KMD as fee coin also

**Comment by TheComputerGenie** [comment]
As for logs, I wouldn't know where to look to find a non-placed order in the logs. Since it throws KMD in there on its own, I'm not about to click "Confirm" and just hope it's a GUI visualization error and I'm not somehow spending both TKL and KMD to get KMD and not the ARRR I'm after.

**Comment by smk762** [comment]
I cant replicate here. Is it happening consistently? Is it just after login or other actions prior (e.g. on wallet page for specific coin before clicking dex tab; coins are being enabled etc).
Try an assets reset too. Not sure why it would make a difference, but cant hurt to rule it out.

**Comment by smk762** [comment]
Related report from Discord - KMD on both sides
https://media.discordapp.net/attachments/1045638310485303336/1045638342101971005/image.png?width=609&height=658
This came from ARRR on left combo and KMD on right combo in sell mode, selecting from orderbook.
When KMD on left and ARR on right, user did not have problem.

@SylEze can you think of any potential cause or race condition etc which might result in this?

**Comment by smk762** [comment]
@Canialon @SirSevenG A discord user provided video which showed steps to replicate in 0.5.7 release or `ticker_bug` branch, though so far I have still not been able to. 

Please try the following on both the 0.5.7 release and on the `ticker_bug` & `fix/trade-conf-modal-ticker-same` branches:
- Login
- go to dex page
- change right ticker
- flip combo boxes with the button between them
- select a red order from the orderbook (buy order)
- click "start swap"
- see tickers incorrect in confirmation window

Additional context:
- user was not busy enabling coins when it happened
- 11 coins were enabled, and wallet page was sorted by balance.
- "Show only coins with balance" filter was not applied.
- 3 of the 11 coins had a balance. KMD had highest balance (and was the duplicated ticker). The other two coins with balance were USDT-BEP20 & TKL.
- The remaining coins without balance were BNB, some BEP20 tokens BTC and LTC.

Ping me in chat if you want a copy of the video to refer to.

If you are able to replicate this, take a screenshot, share logs in chat, and start the swap so we can confirm this is just a visual glitch.

**Comment by SylEze** [comment]
> ![image](https://user-images.githubusercontent.com/21057518/203459628-d1bc5795-8a5f-445c-aee6-0ab94aef770c.png) Parts of it say KMD/Komodo and none of it should when making a TKL/ARRR trade

I really think it's a frontend issue as I mentionned here: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2134#issuecomment-1332341974, where I explain why

I managed to reproduce and after confirming the swap everything was good

**Comment by SirSevenG** [comment]
Couldn't reproduce so far a single time.

**Comment by SylEze** [comment]
Hey @TheComputerGenie, if you have time can you test our possible recent fix please ?
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2134

**Comment by smk762** [comment]
The other Discord use who reported this has tested new branch and been unable to replicate
