### ISSUE TITLE
[BUG]: Infinity loading fees

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#2112]
1. select order from orderbook, press start swap button
2. if you repeat step 1. few times on some point there will be infinity "Loading fees" state 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/24797699/204008732-47cf0d46-0961-42c5-86ef-aaf8e7087b0c.png">

`[15:41:05] [error] [cpprestsdk.utilities.cpp:51] [6379677]: pplx task error: Error resolving address in log`

upd: reproduction is much simplier

1. select order from bottom part of the orderbook and press start swap
2. select order from top part of the orderbook and press start swap
3. see fees hanged

https://user-images.githubusercontent.com/24797699/204010091-db36087b-22fb-4a76-a423-ba08daf0bb20.mov

**Comment by SylEze** [comment]
Not so sure this is related to a repetition of selecting random orders

Got the bug when the volume I wanna trade is near is near the 100% of my total volume.=

**Comment by smk762** [comment]
It was related to multiple  calls to `trade_preimage` (even on a single order), and if getting an error response which model would not parse. I removed the extra calls and made it show the error if it is returned, but need to clean up  some overflow
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2114#issuecomment-1328135409

**Comment by smk762** [comment]
I've reduced the `trade_preimage` triggers down to 
- on simple mode at `onSelectedOrderChanged` (i.e. selecting from the `to` dropdown list.
- On pro mode, once "Start swap" button is pressed.

In simple mode, selection of order already has price / volume set from `from` and bestorders response so no validation required, and fees are calculated before "swap now" button activates. While we might be able to fit this in on the pro view order form, potential manual changes to the price / volume input would cause too many `trade_preimage` requests so not reeally a good option.
