### ISSUE TITLE
[BUG]: Orderbook entries are reversed

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#2116]
Right now top (red) part of the orderbook is suboptimal - best orders are on the bottom and worst are on top what makes interface inconsistent, and in case of orderbook update user have to scroll from top to the bottom to see best order / loses focus from best order what a) just not good in terms of UX b) can cause not best order matching

We should reverse it's content and show best orders on top (same as in green part) and ensure that best order is always on top on orderbook refresh without the need to scroll anything 

https://user-images.githubusercontent.com/24797699/204137086-4cc37b47-3553-469c-812f-f3efc6311651.mov

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/204960988-f07abf99-764d-46b6-bb2a-5c599b5b73cc.png)
the sorting of the orders was correct... like it is on CEXs, see screenshot... the highest bids (green) are on the top while the cheapest asks (red) are on the bottom... so it's centered, so you can see the spread (0.2128 - 0.2135 in the above example)
the only problem is that ADEX doesn't center the bids/asks correctly (bids from top to bottom and asks from bottom to top) right after swithich pairs, you have to scroll to see best asks (cheapest) when there are more asks then the height of orderbook tab... but it does so when it updates orderbook every x seconds

**Comment by tonymorony** [comment]
```
the sorting of the orders was correct... like it is on CEXs, see screenshot... the highest bids (green) are on the top while the cheapest asks (red) are on the bottom... so it's centered, so you can see the spread (0.2128 - 0.2135 in the above example)
the only problem is that ADEX doesn't center the bids/asks correctly (bids from top to bottom and asks from bottom to top) right after switching pairs, you have to scroll to see best asks (cheapest) when there are more asks then the height of orderbook tab... but it does so when it updates orderbook every x seconds... then it looks like this (VRSC/KMD), which is correct... both asks and bids contain more orders then are visible, both can be scrolled... to see the more expensive asks scroll asks up... to see the cheaper bids scroll bids down
```

Yeah, that got sense. We have to fix scroll problems tho to ensure that the user see best order of orderbook on refresh/price updates without need to scroll

**Comment by SylEze** [comment]
Let's make an other issue for orderbook tweaks
