### ISSUE TITLE
[BUG]: Trade confirmation modal views broken by translations

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#2131]
English :heavy_check_mark: 

Spanish
- [x] Fix overlap
![image](https://user-images.githubusercontent.com/35845239/204725144-66532f0c-a379-4579-badc-c75bb50c432e.png)

French
- [x] Translate warning
![image](https://user-images.githubusercontent.com/35845239/204725281-e0b01003-ea10-4932-a77c-1cd9d35fa6c1.png)

German
- [x] Translate warning
![image](https://user-images.githubusercontent.com/35845239/204725455-95c11f42-5a53-4a60-a462-66798f0c1c3e.png)

Russian
- [x] Translate warning
- [x] Fees detail formatting
![image](https://user-images.githubusercontent.com/35845239/204725639-566531b5-e2a2-4059-8519-2f9cdd3ceacc.png)

Turkish
- [x] Translate warning
- [x] Fees detail formatting
![image](https://user-images.githubusercontent.com/35845239/204725562-6452b12e-76f1-4170-8a86-7712b7da8b17.png)

**Comment by coingirl87** [comment]
German Translation:

Der Handelspreis unterscheidet sich um mehr als 50% vom CEX-Preis. Bestätigen?
