### ISSUE TITLE
[BUG]: orderbook shows wrong quantity values

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#2147]
https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/6c4160aae708396f0899ec53d3ca873c49bff02a introduced a bug in pro view orderbook, KMD/LTC now looks like this... the values in "Quantity (KMD)" are wrong, they are the same as "Total (LTC)"
![image](https://user-images.githubusercontent.com/32116761/205298790-906bd4b6-ea8c-46e2-995a-15c7fac1b62c.png)

it should look like this... "Quantity (KMD)" is correct and different from "Total (LTC)"
![image](https://user-images.githubusercontent.com/32116761/205299281-a933694c-4db8-499f-9422-5404de7954e5.png)

**Comment by smk762** [comment]
thanks, will check it
