### ISSUE TITLE
[BUG]: endless loading if 0 balance

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/atomicDEX-Desktop#2149]
It will be endless loading on simple mode if the balance of the selected coin is 0

<img width="405" alt="image" src="https://user-images.githubusercontent.com/77272165/205473301-5d7de200-1b05-4682-856d-f97037cb8061.png">

**Comment by smk762** [comment]
@Canialon I think this has been fixed, can you please confirm in latest dev and close issue if working?

**Comment by Canialon** [comment]
yes, i don't see this issue on 0.5.8
