### ISSUE TITLE
[BUG]: swaps with rel/base volume < 0.00777 can't be started

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#2153]
![image](https://user-images.githubusercontent.com/32116761/205502833-071aeba3-44bc-4cce-a18b-6b3ff9a579a6.png)

"Start Swap" button is disabled when i try to sell NENG for KMD because "Total KMD" is 0.00746392, which is lower then 0.00777
the order has
```
        "rel_min_volume": {
          "decimal": "0.0001"
        },
```
so it should actually work
the fixed 0.00777 min_volume from mm2 should only apply to BTC, not to all coins

it applies to base min_volume too, can't buy 0.00597299 PAXG-PLG20 (worth 11$) because it's < 0.00777
![image](https://user-images.githubusercontent.com/32116761/205522905-051f0723-044d-4256-818c-de04fae16313.png)

**Comment by smk762** [comment]
I know where this is - it was likely introduced in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2115
