### ISSUE TITLE
[BUG]: Random 70+ decimals issues showing on both maker & taker

### ISSUE THREAD

**Issue by auroracoin101** [KomodoPlatform/atomicDEX-Desktop#2173]
**Describe the bug**
70 decimals showing on maker and taker trade amount

**To Reproduce**
Cannot reproduce

**Operating Environment(s):**
 - OS: Windows 10
 - AtomicDEX 5.6 Desktop   ( however made in April 2022,  I dont remember when it showed up like this) 

*  I am so sorry - but I accidentally pressed "Cancel Order"  instead of "Close" !    So it is no longer an open trade. 

Hopefully this still helps. 

![AtomicDex Desktop-15-57-14](https://user-images.githubusercontent.com/86576259/206745271-db3300fa-861c-4a06-ae53-af5a71197a58.png)

**Comment by tonymorony** [comment]
Thank you for issue opening!

Hmm, it might be not actual on latest version (0.5.7). I think we fixed something similar in the previous sprint [ CC @smk762 ]

**Comment by smk762** [comment]
Yep, this is solved in 0.5.7 (https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1906)
