### ISSUE TITLE
[BUG]: Avian Coin not receiving coin

### ISSUE THREAD

**Issue by neo1106** [KomodoPlatform/atomicDEX-Desktop#2176]
![gtbug](https://user-images.githubusercontent.com/1093228/206871485-442e19f4-32a5-41ad-ba5f-aa0cbd168954.jpg)
sometimes the number of avian balances does not increase, even though after checking the explorer coin it was stated that it was successfully entered

**Comment by cipig** [comment]
the 2 AVN electrum servers are lagging behind/are stuck

```
(echo '{ "id": 1, "method": "blockchain.headers.subscribe" }'; sleep 1) | ncat electrum-us.avn.network 50001

{"jsonrpc":"2.0","result":{"hex":"000001324e35274daa50129a85cad3b6f588f7aa619ceb1c69733e2a194eafc300000000db93914d358308a41c9187d0ae6a0e4f05220a7f018eb1ace4de940368a8b17cf0b29463d55d081d59150000","height":1308899},"id":1}
```

```
(echo '{ "id": 1, "method": "blockchain.headers.subscribe" }'; sleep 1) | ncat electrum-eu.avn.network 50001

{"jsonrpc":"2.0","result":{"hex":"0000003269e4e5500164162c009febbe291cc2e6b14b654ed566d2ced8f05c0000000000f9951cb404973d886016ed92527c4eeab89c3f6a9415e443b3c4a45def9b201e9fb29463b3e0001c020bf9a1","height":1308894},"id":1}
```

while block explorer https://explorer.avn.network shows block 1309252

**Comment by cipig** [comment]
electrums seem to have been fixed, they are both on same height and same as explorer
