### ISSUE TITLE
[BUG]: ADEX shows wrong orderbook

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#2185]
The following sequence will lead to ADEX showing wrong orderbook:

- start with BCH (left), DOGE (right)
- click on the arrows between the tickers to invert (you will see DOGE left, BCH right)
- change right ticker to KMD (from BCH)

result: you see the orderbook of LTC KMD, instead of DOGE KMD

when you the click on the arrows again, it will show KMD LTC, which is then correct, so using arrows kind of "fixes" it

**Comment by BURLY7** [comment]
Experiencing the same error on several lesser known project coins.
