### ISSUE TITLE
[FR]: add Memo in ARRR transactions

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#2205]
Depositing ARRR on Kucoin and Coinex requires a memo field in the tx.
![image](https://user-images.githubusercontent.com/32116761/217995198-938beb4c-9e3f-4514-9448-88e006c2c0b1.png)

This was already added to ADEX-API:
```
curl --url "http://127.0.0.1:7783" --data "{
	\"mmrpc\":\"2.0\",
	\"userpass\":\"${userpass}\",
	\"method\":\"task::withdraw::init\",
	\"params\": {
		\"coin\":\"ARRR\",
		\"to\":\"zswhatever\",
		\"memo\":\"1234567arrr\",
		\"amount\":\"2000\"
	}
	,\"id\":0
}"
```

**Comment by smk762** [comment]
@cipig can you please provide a list of coins which should include a memo field for withdrawals?

**Comment by cipig** [comment]
added in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/2230

and works fine with kucoin
![image](https://user-images.githubusercontent.com/32116761/229301745-e15f48c1-dc5f-4c1a-aa59-699daad7a90b.png)

and coinex
![image](https://user-images.githubusercontent.com/32116761/229301789-d6d68960-843b-430d-9bb2-527aede73079.png)
