### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mantrid123** [KomodoPlatform/atomicDEX-Desktop#2222]
Add MEMO for BEP 2,0 ANKR deposits please.

**Comment by cipig** [comment]
BEP2 tokens are not supported, only BEP20... and those don't have any MEMO
we need MEMO, just not for BEP2, but for ARRR: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2205

**Comment by smk762** [comment]
Closing, duplicate of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2205
