### ISSUE TITLE
[BUG]: Loading data from chart

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/atomicDEX-Desktop#2250]
**The chart does not appear in the first loading time, till the user click in coins, or change the coins**

This is the first view after the user clicks at "Pro": 

![image](https://user-images.githubusercontent.com/32954585/231449806-36ffa950-078b-46cd-8284-91e41d8c79a8.png)

It will stay like this as soon as the user takes action: 

1. click on the arrows: 

    ![image](https://user-images.githubusercontent.com/32954585/231449956-b42bbff7-bd12-47dd-b849-5a8caab9e500.png)

2. changes the coins: 
    
    
![image](https://user-images.githubusercontent.com/32954585/231450105-ed45e497-c3c9-4a19-a919-27b41728454c.png)

if any of this actions is performed by user the chart will be visible: 

![image](https://user-images.githubusercontent.com/32954585/231450230-f3a6ccd2-6e13-4bdf-a5cc-8e782731e4fe.png)

**To Reproduce**
1. Go to 'Dex -> Pro'
2. Scroll down to 'chart data stays at loading'
4. Click on 'arrows or change coins'
5. Chart will be visible

**Expected behavior**
The user should see the chart at any time clicks at Pro.

**Operating Environment(s):**
 - OS: Windows
 - OS version: 10
 - AtomicDEX Version: 0.5.7.2-beta

**Comment by Canialon** [comment]
Hm, I cannot reproduce it on MacOS and Windows 11. Have you tried to Reset assets (Settings -> General -> Reset wallet configuration)?

**Comment by smk762** [comment]
Unable to replicate here so far. Will keep an eye on it, if only happens sometimes, might be due to api not responding etc. Can you please attach logs for a session where it happened?
