### ISSUE TITLE
Switch to bitcoincash addresses

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#230]
ref : https://github.com/KomodoPlatform/atomicDEX-API/issues/466

**Comment by cipig** [comment]
updating mm2 and rebuilding after https://github.com/KomodoPlatform/coins/pull/16/commits/fdb62eb0741be071f773a4a259cee7d1d7f9dac1 should do the trick

**Comment by tonymorony** [comment]
thanks!
I'll keep this one opened to not forget to test that UI is not broken because of longer addresses and to include it into changelog

**Comment by cipig** [comment]
my address is `qq4x9cw2ht96xas2ce0wwy5rgs3636kasvvwug3mql`
receive looks like this
![bch_receive](https://user-images.githubusercontent.com/32116761/84382698-8b821600-abda-11ea-8873-81819594f3da.png)

sending works fine... i sent to `qrplwyx7kueqkrh6dmd3fclta6u32hafp5tnpkchx2` (without the `bitcoincash:`)
![bch_sent](https://user-images.githubusercontent.com/32116761/84382715-90df6080-abda-11ea-8e35-7b328ef6f5e7.png)

**Comment by tonymorony** [comment]
@Milerius adex-api return bitcoincash:<address> part now for BCH addresses if format is cashaddress and network is bitcoincash (what is default setup now in coins file we use https://github.com/KomodoPlatform/coins/blob/master/coins#L161) 

Could you please left only <address> part in such cases?

**Comment by Milerius** [comment]
#260 Solved this issue

**Comment by tonymorony** [comment]
Done, will be available in 0.1.5

**Comment by tonymorony** [comment]
we can validate and convert addresses now (can use it for ethereum as well): 

https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#convertaddress

https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#validateaddress

so now we should be able to detect if user input valid legacy address and propose to convert it to cash format,
also would be great to switch ETH addys converter to this call (don't think it worth separate issue)

**Comment by Milerius** [comment]
done
