### ISSUE TITLE
Add icons on all platforms and change name to atomicDEX-Pro from atomic_qt

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#262]
I have to provide .ico file at first

![image](https://user-images.githubusercontent.com/24797699/84947884-316edc80-b115-11ea-8876-9350d1d383e1.png)

**Comment by Milerius** [comment]
#264 Is the first part of this transition, the icon now appears in the bundle, but we need an atomic dex icon for OSX rather than a Komodo icon

**Comment by tonymorony** [comment]
tyvm for icon on OSX ! Afaik you have adex logo now :)

so just:

- [ ] windows icon
- [ ] linux icon

outstading

**Comment by Milerius** [comment]
Windows icon is done, Unfortunately on Linux there is much more problem to set an icon than expected

**Comment by Milerius** [comment]
done
