### ISSUE TITLE
[FEATURE REQUEST]: Detailed swap progress

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#351]
**Is your feature request related to a problem? Please describe.**

Detailed swap progress page with time estimations based on previous local swaps and statistics on next event type probability with same information representation as in mobile app

![image](https://user-images.githubusercontent.com/24797699/87154879-3245f900-c2e4-11ea-9069-d9536013ef88.png)
![image](https://user-images.githubusercontent.com/24797699/87154936-45f15f80-c2e4-11ea-829c-0282a739afe0.png)

**Comment by tonymorony** [comment]
We can add custom fields into our json with coins data info with coin blocktime and current notarisation cycle time and show estimates even before swap quite precise based on this data

**Comment by tonymorony** [comment]
implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/429

**Comment by tonymorony** [comment]
It would be great to count swap estimates by entries from DB for specific pair user trade, not by whole DB to get more precise information.

re-opening as a matter of future enhancement

**Comment by tonymorony** [comment]
Also now there is a bug with step progress counter resets to zero on progress popup closing
we can solve it if use time of previous event end as time of next event start, as I proposed in DMs @Milerius

**Comment by Milerius** [comment]
done
