### ISSUE TITLE
[FEATURE REQUEST]: Addressbook alphabetical sort

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#360]
It would be great to sort addressbook alphabetically without the app restart

**Comment by naezith** [comment]
This is a back-end task.

**Comment by tonymorony** [comment]
> This is a back-end task.

Sounds like dynamical redraw on new address adding task, afaik @Milerius already sort it on backend because on app restart it's rendering sorted

**Comment by naezith** [comment]
> > This is a back-end task.
> 
> Sounds like dynamical redraw on new address adding task, afaik @Milerius already sort it on backend because on app restart it's rendering sorted

Data model / array is handled fully in back-end now. The data is directly fed to the `ListView`.

**Comment by tonymorony** [comment]
became duplicate of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/534 I wonder.
