### ISSUE TITLE
[FEATURE REQUEST]: Push notifications feature

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#398]
- [x] incoming transactions
- [x] swap step progress (for each step a notification)
- [x] matching maker orders
- [ ] rewards need claim
- [x] version update

**Comment by tonymorony** [comment]
Some notes:

- probably it worth to try to activate notifications popup such way by clicking on logo with notifications amount number (not sure if it'll be good in dynamics):

![image](https://user-images.githubusercontent.com/24797699/89640789-82f84400-d8da-11ea-8447-4348a0db1e3d.png)

similar to:

![image](https://user-images.githubusercontent.com/24797699/89640847-a3c09980-d8da-11ea-9c3e-ede859e2efe7.png)


- also there should be button to disable notifications

- it would be great to make notifications about swap events clickable and on click get screen with detailed information about swap

- if scroll is enabled mart of the info is cut:

![image](https://user-images.githubusercontent.com/24797699/89640945-d8345580-d8da-11ea-955e-1d73fb49a9e3.png)

- unlikely we'll want to keep "pop test notification" button for the release

**Comment by Milerius** [comment]
Done
