### ISSUE TITLE
[BUG]: [NEW UI] Hover text for the Coin tickers in Wallet tab blocks tickers of other coins

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX-Desktop#400]
**Describe the bug**
In the wallet tab of New UI, when you hover the mouse pointer over a Coin Ticker, its name is displayed in Hover text above the ticker. This hover text blocks the ticker name of another coin. The highlighted text in the following picture is the hover text for KMD blocking the BTC ticker.    
![Screenshot from 2020-07-31 09-36-39](https://user-images.githubusercontent.com/21151592/89001614-5a8bab00-d318-11ea-82bd-de1b6295cfdd.png)

**To Reproduce**
1. Go to Wallet tab
2. Hover over KMD ticker
3. Observe the hover text's location

**Expected behavior**
Make the hover text appear on the right side of the ticker

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version 0.2.0 alpha

**Comment by tonymorony** [comment]
improved by https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1601
