### ISSUE TITLE
[FEATURE REQUEST]: Chart on Dashboard page

### ISSUE THREAD

**Issue by theblackmallard** [KomodoPlatform/atomicDEX-Desktop#441]
Should include a chart of the total portfolio balance on the dashboard page with the ability to toggle multiple currencies. Some people prefer to see their balances in Fiat or Satoshis, the chart should ideally show each of these. Should be filterable by day, month, year or other timelines.

Another option, or an additional chart, would be a donut chart showing the current portfolio balance makeup.

**Comment by tonymorony** [comment]
thanks for the issue opening!

portfolio tracking chart by tx history parsing is definetly something duable in the future - most probably it worth to create separate section with charts/trade history for accounting
there is already possibility to toggle between calculations in fiat/BTC/KMD (have to click on porfolio sum in dashboard) and in 0.2.1 in settings will be possible to select between different fiat pairs so it might be a good foundation for this one

**Comment by smk762** [comment]
Donut chart on dashboard has been implemented, and nomics chart is now available for wide range of currencies in dex pro page.
