### ISSUE TITLE
[BUG]: Kaspersky anti virus mm2.exe suspicious application

### ISSUE THREAD

**Issue by acemi1** [KomodoPlatform/atomicDEX-Desktop#444]
![image](https://user-images.githubusercontent.com/39681665/90951611-03837c80-e465-11ea-92f5-978c764077e0.png)

kaspersky anti virus sees mm2.exe file as suspicious application. And deleting it prevents the program from running.
I used atomicdex-pro-0.2.0-alpha-windows.zip for windows 10 64 bit operating system. I ran the atomic_qt.exe file.

**Comment by tonymorony** [comment]
Hi! Thank you for issue opening and reporting that. mm2.exe is a https://github.com/KomodoPlatform/atomicDEX-api/ binary (the core) of program. For now to use the app please exclude mm2.exe from Kaspersky quarantine manually. We'll re-check this case and contact Kaspersky to prevent such cases.

**Comment by smk762** [comment]
Kaspersky AV alone does not appear to cause this issue, but Kaspersky Internet Security does. 
![image](https://user-images.githubusercontent.com/35845239/91292013-8475a780-e7c8-11ea-96f1-598a7ae88f55.png)

Windows mm2 binary submitted to https://opentip.kaspersky.com 
Results at 
https://opentip.kaspersky.com/F4498493AA36FEF0273C67E236E04CA06AC3454C56ADBC27B1EA0C1046E2AAED/ indicate clean object -  it appears Kaspersky is flagging activity, not code.

Higher level access to the Threat Intelligence Portal may be required to get more detailed results - I've contacted Kaspersky to arrange this and review the binary in action.

**Comment by cipig** [comment]
https://github.com/KomodoPlatform/atomicDEX-API/pull/712
the renaming could affect this... mm2 will be renamed to atomic_defi

**Comment by tonymorony** [comment]
@smk762 could you please re-check if latest version of Kaspersky Internet Security still behave this way?

**Comment by smk762** [comment]
Kaspersky Internet Security still views it as 'legitimatte softwa can be useedd by intruders to damam your computer or personal data detected" then terminates the process and deletes the object (not-a-virus:PDM:AdWareNSIS.ConvertAd.bCb).

Adding "mm2" to trusted applications overcomes the issue (though binary might need to be extracted again from archive if it was deleted).

Previous email to intelligence@kaspersky.com has not yet been responded to - I have sent a follow up.

**Comment by jansako** [comment]
Confirming Kaspersky Total Security still (mis)behaves the same way with version 0.3 :-(

**Comment by mvbarboz** [comment]
Confirming Kaspersky Total Security still (mis)behaves the same way with version 0.4

**Comment by Milerius** [comment]
Please open an issue to https://github.com/KomodoPlatform/atomicDEX-API, this is not related to AtomicDEX-Desktop.
