### ISSUE TITLE
Allow minimize to system tray - run on the background

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Desktop#453]
I would love to be able to have DeFi Pro running in the system tray, without the icon in my taskbar. Now that notification push is implemented, there is no reason to have an extra icon in the tray for everyone to see... :-)

Thanks!

**Comment by jansako** [comment]
![image](https://user-images.githubusercontent.com/34211887/91634217-93648180-e9a3-11ea-86e5-23b234499cf4.png)

**Comment by Milerius** [comment]
I wont implement that, because it' something rly minor and. not that much important. Furthermore AtomicDEX is an executable, not a service.
