### ISSUE TITLE
[QUESTION]: Notifications combined total amount from multiple transactions on qrc20

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Desktop#463]
Sent 4 transactions back to back:
<img width="831" alt="Screenshot 2020-09-17 at 18 44 38" src="https://user-images.githubusercontent.com/11756768/93466551-a15c5100-f916-11ea-8166-6496d65a466b.png">
And received the following notification:
<img width="541" alt="Screenshot 2020-09-17 at 18 44 57" src="https://user-images.githubusercontent.com/11756768/93466585-ade0a980-f916-11ea-87d4-cc00896848ab.png">

Is it expected behaviour that notifications would combine those txs to total amount?

MacOS 10.15.6 on stylized_combobox branch.

**Comment by Milerius** [comment]
Yes it's detecting balance change just update everything at the same time

**Comment by tonymorony** [comment]
I think it would be more correct if we'll have single notification for single transaction

**Comment by Milerius** [comment]
We had to make a choice to have as much performance on this part of the program.

Only the history of the currency currently selected is refresh.

Balance of every coins are refreshed every 30seconds, if your balance change of one of your coin means you receive or send a transaction.

If you click on the notification it's will select the coin and load his history.

This method makes it possible to avoid storing in memory all the histories of all the currencies.

**Comment by Milerius** [comment]
Duplication of #591
