### ISSUE TITLE
[FEATURE REQUEST]: faucet integration

### ISSUE THREAD

**Issue by joe2x4** [KomodoPlatform/atomicDEX-Desktop#472]
**Is your feature request related to a problem? Please describe.**
If the problem is defined as lack of users then this is related to that issue, however it is broader in scope.
This is a feature for user incentive, repeat user attention, and coin community advertising.

**Describe the solution you'd like**
Id like an optional integrated multicoin faucet that automatically pays out in defined time increments based on user open order online status.
It would work such that any supported coin would have a faucet address to donate to. Then when you are running AtomicDex and have an open order for a defined time length, it triggers the faucet automatically for you and your address gets the payout amount. Faucet funds would be maintained by coin communities

**Describe alternatives you've considered**
An alternative could be to link to an api of a multicoin faucet website

**Comment by Milerius** [comment]
done #542
