### ISSUE TITLE
[BUG]: Disable a coin does not update the global balance

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#500]
**Describe the bug**
When you disable a coin in the dashboard, the global balance does not update immediately.

**To Reproduce**
1. Go to the dashboard page
2. Disable a coin that has a fiat value
3. Check the global balance

**Expected behavior**
The global balance should be immediately updated

**Video**
[bug_disable_balance_update.zip](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/5385708/bug_disable_balance_update.zip)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.14
 - Version 0.3.0-beta

**Additional context**
Release build (dev branch).

**Comment by smk762** [comment]
Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/501/commits/38cede4ae97f86ad7600f9b4166eea61b43d53eb
