### ISSUE TITLE
[BUG]: Input fields not drawing after language change

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#502]
**Describe the bug**

After language switch all input fields not drawing (tested on windows so far). Only app restart helps.

**To Reproduce**
1. switch language to any
2. check send or receive popup in wallet section

**Screenshots**

Before language switch:

![image](https://user-images.githubusercontent.com/24797699/96191065-8dcff480-0f6d-11eb-89df-4996e8994d94.png)

After langauge switch:

![image](https://user-images.githubusercontent.com/24797699/96190912-36ca1f80-0f6d-11eb-9ebb-64f5ee3eb7fc.png)

**Desktop (please complete the following information):**
 - OS: windows, latest dev

**Comment by naezith** [comment]
It's really strange. It was tricky to debug. I fixed it but test everywhere please because changes are in generic components. https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/0f8b175ff5d339d46e09a5b6975761dd8541494d
