### ISSUE TITLE
[FEATURE REQUEST]: Display tooltip when hovering the band oracle icon

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#521]
**Describe the solution you'd like**
When we hover the band icon with the mouse, we want to show a tooltip which tells from where the price is calculated.
Of course, adding a short delay (0.5s) when hovering the button is required, in order to do not annoy users when they pass on it.

**Additional context**
Demonstration:
![Display tooltip when hovering the band oracle icon](https://user-images.githubusercontent.com/14373103/96857352-2cbd8a80-145f-11eb-87c8-dd3dc4be37ab.gif)

**Comment by Milerius** [comment]
closed by #522
