### ISSUE TITLE
[FEATURE REQUEST]: Display fiat equivalent in order line

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#523]
**Describe the solution you'd like**
Add the price equivalent in fiat after the prices in coin.

**Additional context**
Result:
<img width="1444" alt="Capture d’écran 2020-10-22 à 19 52 45" src="https://user-images.githubusercontent.com/14373103/96912144-2d2b4500-14a2-11eb-94bd-905ac2471e6c.png">
<img width="1427" alt="Capture d’écran 2020-10-22 à 19 55 40" src="https://user-images.githubusercontent.com/14373103/96912152-2ef50880-14a2-11eb-84c4-0cae7efd6407.png">

**Comment by Milerius** [comment]
closed by #524
