### ISSUE TITLE
[FEATURE REQUEST]: Integrate RICK/MORTY Faucet

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#536]
To allow users to easily get some test coins, the following is proposed:

- Add a "FAUCET" button to the RICK / MORTY wallet pages (similar to the "CLAIM" button on KMD wallet page). 
- When user clicks this button, the {coin} and {address} variables of the wallet page are passed to the faucet api (e.g. `http://{faucet_ip}/faucet/{coin}/{address}`)

The API is being tested at the moment at using 
`http://116.203.120.91:8080/faucet/RICK/RSXhAHpMu3sgirNBqdeNvv83aWWiBNUzmc`

Replace coin and address as required. IP address will change once deployed.

The API has 6 outcomes:
- tx queued for payment in next cycle (5 min at the moment)
- error if coin is not RICK/MORTY
- error if address is not valid
- denied if address already has > 1 RICK / MORTY balance
- denied if tx already queued
- denied if address has had a facuet tx sent to it in the last 4 hours.

These messages can be passed on to the user as required in response to the button click.

**Comment by smk762** [comment]
API has been updated, use 

http://faucet.komodo.live/faucet/RICK/RSXhAHpMu3sgirNBqdeNvv83aWWiBNUzmc

Replace coin and address as required. IP address will change once deployed.

**Comment by Milerius** [comment]
close with #542 feel free to re-open if needed @smk762
