### ISSUE TITLE
[BUG]: Swap amounts in current currency is not updated when changing of currency

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#545]
**Describe the bug**
Swap value indication is incorrect when global curreny changing to crypto 

**To Reproduce**
1. Start swap with real value coin
2. Change global currency to non-fiat

![USD](https://user-images.githubusercontent.com/24797699/97709059-55dbbc00-1aec-11eb-9b4f-857952fcabb9.PNG)
![KMD](https://user-images.githubusercontent.com/24797699/97709071-583e1600-1aec-11eb-8b33-eb490b835529.PNG)
![BTC](https://user-images.githubusercontent.com/24797699/97709087-5e33f700-1aec-11eb-91ac-c6fde15ea789.PNG)

**Comment by SylEze** [comment]
This also occurs when you switch from a fiat to another fiat

**Comment by Milerius** [comment]
works for fiat @SylEze , need to implement for alternative currency too (KMD/BTC)

**Comment by Milerius** [comment]
Can you test / close on last dev if everything is fine @smk762  ?

**Comment by smk762** [comment]
![image](https://user-images.githubusercontent.com/35845239/105286140-b280db80-5bf0-11eb-84b2-8512433cc830.png)
![image](https://user-images.githubusercontent.com/35845239/105286184-c6c4d880-5bf0-11eb-8950-3807e5f43e63.png)
![image](https://user-images.githubusercontent.com/35845239/105286226-d5ab8b00-5bf0-11eb-9970-429f3a69814d.png)

Remains an issue in build 161b8c6. 
Values update elsewhere, but not in DEX > Orders page. Currency prefix updates, value of selected currency does not.

To reproduce, start a trade, return to dashboard page and click on wallet value (at the top) to toggle between Fiat / BTC / KMD value. Return to DEX > Orders page. Currency prefix updates, numeric value does not.

**Comment by smk762** [comment]
Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/635
