### ISSUE TITLE
[FEATURE REQUEST]: QRC-20 Swaps

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#557]
**Is your feature request related to a problem? Please describe.**

Add support for QRC-20 swaps, change get_trading_infos according to new requirements
Re-enable QRC-20 for swaps from filters #482

**Comment by Milerius** [comment]
@naezith we should change some fields from `get_trade_infos` to be more specific regarding fees of QRC-20/ERC-20

**Comment by naezith** [comment]
> @naezith we should change some fields from `get_trade_infos` to be more specific regarding fees of QRC-20/ERC-20

Perhaps we should also rename `erc_` named variables to something different.

**Comment by Milerius** [comment]
done with new trading logic
