### ISSUE TITLE
[FEATURE REQUEST]: Improve hyperlink visibility in support page

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#559]
Blue on blue is suboptimal. Perhaps underlined white (or slight grey for visited links) would be kinder on the eyes? Underline plus pointer cursor should be enough to indicate it is a hyperlink.
![image](https://user-images.githubusercontent.com/35845239/97958512-4f995880-1de8-11eb-8341-8de3aa83352a.png)

**Comment by naezith** [comment]
`TextEdit` of QML API does not have link color setting. So I made a new component which uses `Text`. `Text` ones can't be selected with mouse, that's why titled texts were read-only `TextEdit`.

https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/443c5db9eebf9479785c06ab564d4f72b493bd53
