### ISSUE TITLE
[FEATURE REQUEST]: Write MM2 logs

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#572]
We have to write mm2 log separately with GUI log on all platforms to be able to properly debug

**Comment by Milerius** [comment]
Already done in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/c78d5c41eac7e44a1b701fec115fd205d445fb7e

please use appropriate communicating channels before opening an issue.
