### ISSUE TITLE
[FEATURE REQUEST]: Include Maintainence tool in start menu with windows installer

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#581]
Currently the windows installer adds a shortcut to the app in the start menu, but you need to manually navigate to the maintenance tool with windows explorer to uninstall when updating. 
Can we please include the maintenance tool in the atomicdex start menu folder?

**Comment by naezith** [comment]
Please try https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/fa696d837eba51d8d0b566c79d6fc499bd18146a

**Comment by Milerius** [comment]
done in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/fa696d837eba51d8d0b566c79d6fc499bd18146a
