### ISSUE TITLE
[BUG]: Broadcast rpc call can fail, not handled by GUI

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#582]
**Describe the bug**

<img width="682" alt="Capture d’écran 2020-11-22 à 09 06 45" src="https://user-images.githubusercontent.com/21139416/99898525-2f9bdd00-2ca2-11eb-9669-6ed6833013c5.png">

**To Reproduce**

1. Go to Wallet page
2. Enable tQTUM
3. Send some tQTUM to someone

**Expected behavior**

An Error popup that doesn't say complete -> check if the string in the backend contains "error" to detect that

**Desktop (please complete the following information):**
 - OS: Windows/MacOS/Linux
- 0.3.1

**Comment by naezith** [comment]
Please test https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/58a67269cea3b8f4b303876d836aa19940959a4f
