### ISSUE TITLE
[FEATURE REQUEST]: view private key option

### ISSUE THREAD

**Issue by lightspeed393** [KomodoPlatform/atomicDEX-Desktop#588]
Add a button in Settings Menu under `View Seed` for `View Private Key`. 

This could either ask the user to select one of the enabled coins or show the key for each enabled coin. 

Having this option would allow user to import their key into other wallets to claim funds. 

For example with HUSH being removed, users are coming to discord trying to figure out how to access their funds. They could simply view the private key from their seed and import it into whatever wallet they choose to use now.

**Comment by Milerius** [comment]
> Add a button in Settings Menu under `View Seed` for `View Private Key`.
> 
> This could either ask the user to select one of the enabled coins or show the key for each enabled coin.
> 
> Having this option would allow user to import their key into other wallets to claim funds.
> 
> For example with HUSH being removed, users are coming to discord trying to figure out how to access their funds. They could simply view the private key from their seed and import it into whatever wallet they choose to use now.

I'm not against this feature, but you will be able to see the private keys of supported coin, `HUSH` is not supported anymore so you will not be able to see your `HUSH` private key

**Comment by lightspeed393** [comment]
In the case of HUSH they could just export KMD privkey, but I was thinking more about the future and having users export their key before the coin is delisted.

**Comment by smk762** [comment]
Implemented in #599
