### ISSUE TITLE
[BUG]: Fonts displaying issue on Apple Silicon M1

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#597]
Opening this issue to track compatibility status. At the moment latest dev application displaying with corrupted fonts in Apple M1 VM (Big Sur 11.0, QT 5.15.2):

![image](https://user-images.githubusercontent.com/24797699/100735809-655c6680-3404-11eb-8623-419984f963fd.png)

**Comment by naezith** [comment]
Looks like the texture offset for each character is shifted a bit to right. I don't have any custom code for that. Need to search QTBUG portal.

**Comment by Milerius** [comment]
Openned https://bugreports.qt.io/browse/QTBUG-89379 for clarification it's seems that #615 don't solve the problem.

**Comment by tonymorony** [comment]
> Openned https://bugreports.qt.io/browse/QTBUG-89379 for clarification it's seems that #615 don't solve the problem.

#615 resolved issue on my side

**Comment by yurii-khi** [comment]
Faced same issue on intel macbook as well. macOS Catalina 10.15.7
It is different every time, sometimes app became unusable, so I just restart it with the ⌘+Q

<img width="1440" alt="Screenshot 2021-01-16 at 08 41 27" src="https://user-images.githubusercontent.com/29194552/104806388-63454000-57d7-11eb-88a1-6e4cf4f0b0b9.png">

**Comment by Milerius** [comment]
Fixed by #615
