### ISSUE TITLE
[Improvements]: Change wallet_manager to a standalone system + QObject

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#598]
**Is your feature request related to a problem? Please describe.**

Clearing app.hpp/cpp

**Describe the solution you'd like**

Standalone wallet_manager system/QObject + full unit tests

QML functions should call `API.app.wallet_manager.function();` instead of `API.app.function()`

**Describe alternatives you've considered**
None

**Comment by smk762** [comment]
@Milerius can you pls confirm if this is complete?
I can see https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/app/app.cpp#L783 so I assume so.

**Comment by smk762** [comment]
@SylEze  do you know if this was completely implemented? Can we close this issue?

**Comment by smk762** [comment]
Closing issue due to no response. Please feel free to reopen if required.
