### ISSUE TITLE
[FEATURE REQUEST]: Give hints to windows user when mm2 is being blocked or quarantined

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX-Desktop#608]
**Is your feature request related to a problem? Please describe.**
On Windows OS when the firewall blocks mm2 or antivirus quarantines it on the first run, there is an endless "mm2 is initializing" screen and the user doesn't know how to proceed.

**Describe the solution you'd like**
Say, the OS is windows and mm2 initialization is taking "too long". Say, more than 20 seconds. (we could even have a seconds timer on the screen to let the user know that the app hasn't hanged)

AtomicDEX could then check if the mm2.exe file exists in the expected location. If it doesn't, it could display a hint to the user to check antivirus

Say, mm2.exe exists at the location, but still takes too long to initialize, AtomicDEX could display a hint to check firewall and antivirus

This is just one solution I have thought of, any others that let users know the possible courses of action are also good.

**Comment by smk762** [comment]
closing, rolled into https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1310
