### ISSUE TITLE
[Feature Request]: reset assets configuration button immediately restarts without asking user if its OK

### ISSUE THREAD

**Issue by dth88** [KomodoPlatform/atomicDEX-Desktop#612]
Probably would be better for UX if we ask the user if it's ok to restart before doing so :)

UPD

**Is your feature request related to a problem? Please describe.**
I am always frustrated when something like restart in the app is happening suddenly and without asking me if I want to restart it.

**Describe the solution you'd like**
I would very much like it if you could put a modal window notifying me about the upcoming restart and most importantly asking me if I want to proceed.

**Describe alternatives you've considered**
Unfortunately, there's no alternative to a better user experience other than providing users with the expected "This action will restart the app, would you like to continue?"

**Additional context**
Additionally, we could also notify users that deleting a custom ERC-20/QRC-20 asset from the app will restart it.

Please let me know if any further explanation needed, always here to help.

**Comment by Milerius** [comment]
Please use the template for feature request and describe

**Comment by smk762** [comment]
As we've recently added an "are you sure" confirmation msgbox for logout, it would be good to link it to resetting assets config also @ssakone

**Comment by tonymorony** [comment]
There is confirmation modal rn
