### ISSUE TITLE
[BUG]: After saving note with max number of characters, it shows up on every transaction.

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Desktop#613]
Here's a video: https://youtu.be/KWdD6O41Zpo

Reproducible on Mac 10.15.7 and ubuntu 18.04, have not yet tried other platforms but pretty it is there as well.

It's not permanent though, as soon as you restart the app, all notes return to where they are supposed to be.

0.3.1

**Comment by Milerius** [comment]
Can you verify on the loader branch if this error it's still present ? 

Shouldn't happen with the new modal approach.

**Comment by dathbezumniy** [comment]
all good on loader branch.
