### ISSUE TITLE
[FEATURE REQUEST]: Generic configuraiton approach

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#614]
**Is your feature request related to a problem? Please describe.**

Currently the configuration of `AtomicDEX Desktop` mixes the custom tokens with the generic coins, it gives some problems I think we should have the configuration in a generic repo which could be re-downloaded each time the `SHA256` changes, that would correct the problems without re-release. In addition, resets assets configuration would no longer remove customs tokens.

**Describe the solution you'd like**

- [x] A repo where the `AtomicDEX-Desktop`configuration is located.
- [x] separate `0.3.1-coins.json` (remote) with `0.3.1-custom-tokens.json` (local)
- [ ] Use `SHA256` to compare diff between remote and local
- [ ] Add Unit tests

**Additional context / Motivation**

- `coinpaprika` just changed today the ID for `zcoin` to `firo`, in our current approach we have to re-release for that.
- `Reset assets configuration` is removing custom tokens at the moment, with this new approach this will not be the case anymore

**Cons**

- This change is a breaking change and will break every custom tokens from the current `0.3.1-wallet-name-coins.json` of the user.

**Comment by cipig** [comment]
That is the purpose of the https://github.com/KomodoPlatform/coins repo. If we add the coinpaprika and coingecko ids to the coins file too (which i was thinking about anyway), it contains all infos needed by the GUI, so no need to setup a new repo.
We can also make changes to the format if needed.

**Comment by Milerius** [comment]
no this need a standalone repo because i want to use last GitHub hash @cipig and coins repo change to often, will trigger unwanted redownload

**Comment by cipig** [comment]
the format of the file https://github.com/KomodoPlatform/coins/blob/master/coins itself is given by mm2, everything else in the coins repo can be changed or added as pleased
using only one repo eliminates the need to make PR for 2 or more repos when adding or changing coins... the last ZEC consensus branch change needed 2 PR and 2 new releases (Desktop and Mobile) to become active

**Comment by Milerius** [comment]
will then probably move the contents from `atomicdex-desktop-generics` to `coins` repo but i need a way to not be spammed by coins repo addition

**Comment by Milerius** [comment]
done in #890
