### ISSUE TITLE
[FEATURE REQUEST]: Add support for proxy settings in cli and gui

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX-Desktop#617]
I think it would be useful for users to be able to set a proxy to be used by the DEX. 
Some software allow such arguments from command line:
```
                --proxy-server="socks://foobar:1080"
                --proxy-server="socks4://foobar:1080"
                --proxy-server="socks5://foobar:66"
                --proxy-server="https=proxy1:80;http=socks4://baz:1080"

```
it would be very useful for users to be able to test the dex using different than system wide proxy setting. 

```
./atomicdex --proxy-server="socks://foobar:1080"
```
It would be even better if we could have the option to setup a proxy server for the wallet as done in many popular applications. It would enhance privacy and security IMHO.

**Comment by damascene** [comment]
Would you consider having such option in AtomicDex @artemii235 , it's vital for privacy IMO?

**Comment by smk762** [comment]
Closing, issue has been transferred to API repo.
