### ISSUE TITLE
[BUG]: Send modal is not correctly reset after sending coins

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#618]
**Describe the bug**
When you send coins, the send modal is not correctly reset. Therefore when sending coins again you will see the `Send` window instead of the `Prepare` window

**To Reproduce**
1. Go to the Wallet page
2. Click on the `SEND` button from the coin of your choice
3. Fill required data: address and amount
4. Click on `Prepare`
5. Click on `Send`
6. Reproduce steps from 1 to 2
8. `Send` window should be displayed instead of `Prepare` window

**Expected behavior**
Each time you send coins, the window which should be displayed first is the `Prepare` window

**Screenshots**
![Enregistrement de l’écran 2020-12-12 à 11 49 48](https://user-images.githubusercontent.com/14373103/101981890-61381080-3c70-11eb-8fa6-c81f13923c9d.gif)

**Comment by SylEze** [comment]
Should be fixed on  https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/599

**Comment by smk762** [comment]
Confirmed working as expected in current dev branch.
