### ISSUE TITLE
[BUG]: How to transfer coins from old wallets to new wallets? Verus-Desktop-Windows-v0.7.2-6

### ISSUE THREAD

**Issue by sohrab007006** [KomodoPlatform/atomicDEX-Desktop#619]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tonymorony** [comment]
Could you please clarify what exactly the problem is?
If you want to use seed created in Verus wallet just use the "Restore wallet" button in AtomicDEX wallet and use this seed phrase.

**Comment by sohrab007006** [comment]
I have some old rfox and I want to convert them to new rfox

**Comment by sohrab007006** [comment]
That's why I want to move them from the old version to the new version

**Comment by cipig** [comment]
RFOX is now ERC20: https://github.com/KomodoPlatform/coins/blob/master/coins#L1281 and https://github.com/KomodoPlatform/atomicdex-desktop-generics/blob/main/config/0.3.1-coins.json#L831
conversion must be done by RFOX team

**Comment by tonymorony** [comment]
Closed this one - it doesn't seems to be related to atomicDEX-Desktop

**Comment by sohrab007006** [comment]
I mining some RFOX but can not convert it?Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [KomodoPlatform/atomicDEX-Desktop] [BUG]: How to transfer coins from old wallets to new wallets? Verus-Desktop-Windows-v0.7.2-6 (#619)From: tonymorony To: KomodoPlatform/atomicDEX-Desktop CC: sohrab007006 ,Author 
Closed this one - it doesn't seems to be related to atomicDEX-Desktop

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/619#issuecomment-759942487",
"url": "https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/619#issuecomment-759942487",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sohrab007006** [comment]
How can I convert them? Please help me-------- Original Message --------Subject: Re: [KomodoPlatform/atomicDEX-Desktop] [BUG]: How to transfer coins from old wallets to new wallets? Verus-Desktop-Windows-v0.7.2-6 (#619)From: cipig To: KomodoPlatform/atomicDEX-Desktop CC: sohrab007006 ,Author 
RFOX is now ERC20: https://github.com/KomodoPlatform/coins/blob/master/coins#L1281 and https://github.com/KomodoPlatform/atomicdex-desktop-generics/blob/main/config/0.3.1-coins.json#L831
conversion must be done by RFOX team

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/619#issuecomment-758546084",
"url": "https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/619#issuecomment-758546084",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
