### ISSUE TITLE
[FEATURE REQUEST]: Add min_volume handling

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#624]
https://github.com/KomodoPlatform/atomicDEX-API/issues/473

min_volume param needs to be handled from both trade sides:

1) maker when creating the order via setprice (btw I think we need to add support of creating order via setprice when user don't want to wait 30 seconds for order transformation)

2) taker when matching the order should see min_volume (at least on order selection stage) - probably detailed order info popup on order selection is needed to be added

**Comment by TheComputerGenie** [comment]
The severity of this lies in the market price of BTC
If BTC reaches $100k then, under the current GUI design, no user will be able to trade with BTC for any amount under $900 
Which might seem like a far-fetched "what if", but the reality is that at the movement BTC is over $39k and the minimum trade is in excess of $300.
A $300 trade may be small to most of us, but not by any means small to "the average user".

**Comment by Milerius** [comment]
> The severity of this lies in the market price of BTC
> If BTC reaches $100k then, under the current GUI design, no user will be able to trade with BTC for any amount under $900
> Which might seem like a far-fetched "what if", but the reality is that at the movement BTC is over $39k and the minimum trade is in excess of $300.
> A $300 trade may be small to most of us, but not by any means small to "the average user".

I agree that for very expensive fees amount we should probably warn the user with a orange message.

**Comment by tonymorony** [comment]
> The severity of this lies in the market price of BTC
> If BTC reaches $100k then, under the current GUI design, no user will be able to trade with BTC for any amount under $900
> Which might seem like a far-fetched "what if", but the reality is that at the movement BTC is over $39k and the minimum trade is in excess of $300.
> A $300 trade may be small to most of us, but not by any means small to "the average user".

just for ref. : https://github.com/KomodoPlatform/atomicDEX-API/issues/715 here is another possible way to save ~3% on every 300$ ETH or BTC trade

**Comment by Milerius** [comment]
> > The severity of this lies in the market price of BTC
> > If BTC reaches $100k then, under the current GUI design, no user will be able to trade with BTC for any amount under $900
> > Which might seem like a far-fetched "what if", but the reality is that at the movement BTC is over $39k and the minimum trade is in excess of $300.
> > A $300 trade may be small to most of us, but not by any means small to "the average user".
> 
> just for ref. : [KomodoPlatform/atomicDEX-API#715](https://github.com/KomodoPlatform/atomicDEX-API/issues/715) here is another possible way to save ~3% on every 300$ ETH or BTC trade (on the taker side)

Sounds promising.

**Comment by TheComputerGenie** [comment]
> > The severity of this lies in the market price of BTC
> > If BTC reaches $100k then, under the current GUI design, no user will be able to trade with BTC for any amount under $900
> > Which might seem like a far-fetched "what if", but the reality is that at the movement BTC is over $39k and the minimum trade is in excess of $300.
> > A $300 trade may be small to most of us, but not by any means small to "the average user".
> 
> I agree that for very expensive fees amount we should probably warn the user with a orange message.

Fees are an aside
If I had half of all the BTC in the world, I couldn't use it to trade for 150 KMD with the current hard-coded limit

**Comment by cipig** [comment]
seems we have 2 issues dealing with the same
https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/553 is a duplicate of this

**Comment by TheComputerGenie** [comment]
same feature, different reasons?
but, seems yes

**Comment by tonymorony** [comment]
ty for the hint!
closed as a duplicate of #553
