### ISSUE TITLE
[FEATURE REQUEST]: Swap constructor / Simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#625]
As I think a missing key element of UX at the moment is orderbooks scanning part - right now user has to brute force to find the orderbook with liquidity. I think we can make a tab (and use it as a default and current order book tab as "advanced" for pro-traders) with simplified uniswap-like UX.

The idea is a simple screen like a "trade wishmaster":

the first question is (first selector): do you want to buy or sell?
the second question is what coin/token you want to sell/buy (action is set by the first selector)

then order books scanning for  `selected coin` vs `every activated coin` or `every activated coin` vs `selected coin` (depends on if user want to buy or sell)

in the end generating a list of liquid pairs,
 like you can buy VRSC for:
 BTC (5 orders, 20000 depth, best price 0.21$)
 KMD (2 orders, 10000 depth, best price 0.2$)
 ...
 and same for sell

then the user may select a market from the generated list and will see another list with orders for this market (for buy or sell vs selected coin), then select/confirm order and trade

so just two simple questions (UX will be very minimalistic and simple) and orderbooks scan

![buy:sell](https://user-images.githubusercontent.com/24797699/106267521-5a834e00-625c-11eb-99c6-48233a9fe009.png)

**Comment by Milerius** [comment]
Please vote for your preffered view for the swap constructor - feel free to comment if you have other idea:

View 1:

<img width="854" alt="Capture d’écran 2021-02-12 à 09 11 51" src="https://user-images.githubusercontent.com/21139416/107769702-ab08aa00-6d38-11eb-8b01-e0d415002e0d.png">

View 2:
<img width="834" alt="Capture d’écran 2021-02-12 à 09 11 56" src="https://user-images.githubusercontent.com/21139416/107769705-ac39d700-6d38-11eb-8911-c58bf6955621.png">

View 3:
<img width="873" alt="Capture d’écran 2021-02-12 à 09 12 02" src="https://user-images.githubusercontent.com/21139416/107769708-ad6b0400-6d38-11eb-8625-3830b0d34897.png">

http://www.strawpoll.me/42622211

**Comment by ciumete** [comment]
All !

**Comment by daemonfox** [comment]
I like the card background style of 3, would mash into view 2 very well.

Can these all be added and toggled as choices for graphs and UI styles?

**Comment by julioasoares** [comment]
> Can these all be added and toggled as choices for graphs and UI styles?
hat would perfect!

**Comment by julioasoares** [comment]
UX question... Could we? start a swap simply by 

1. Selecting the icon the coin we have
2. Entering the amount you want to swap
3. As you type, icons of coins with enough liquidity would appear at the top (ordered by best returns(?))
4. Icons of coins withtout liquidity appear dimmed at the bottom (or disappear) 
5. Drag and drop the icon of your coin on top of the coin you want.
6. Confirm or cancel
?

**Comment by paperballs** [comment]
I would use style 2 the most with the chart and order book

**Comment by mogrith** [comment]
> I like the card background style of 3, would mash into view 2 very well.
> 
> Can these all be added and toggled as choices for graphs and UI styles?

I do like the idea of top being view 2 but bottom being View 3. But if it's just one view I would pick 3. as I can see most of the View 2 on other pages

**Comment by Milerius** [comment]
Implemented

**Comment by smk762** [comment]
First iteration of this merged into dev via https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889
Tweaks / enhancements can be put into new issues.
