### ISSUE TITLE
[FEATURE REQUEST]: Addressbook buttons naming

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#626]
In addressbook, some of the confirmation buttons have strange naming. Request that "Validate" is changed to "OK" or "Confirm".

![image](https://user-images.githubusercontent.com/35845239/104042729-ce11dc80-5215-11eb-92ea-3c103e49a2fd.png)
![image](https://user-images.githubusercontent.com/35845239/104042787-dff37f80-5215-11eb-8e3c-428ea8f17c35.png)

When adding a new address, it currently has "OK", but "Validate" might be warranted in this context, as address validation is taking place.
![image](https://user-images.githubusercontent.com/35845239/104042675-bf2b2a00-5215-11eb-95bf-fa38a8ddb949.png)
Also, the "enter a key" default text is ambiguous, implying perhaps a private key, which user wont have if its to an third party address (and also not a good idea for them to store privkey like this as it will be in plaintext in user data). Request this text changed to "Enter a name".

**Comment by SylEze** [comment]
Should be fixed by 189b0ec607c820e4329bcaaf13ba414d787a4804.
