### ISSUE TITLE
[FEATURE REQUEST]: Add show private key feature

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#627]
https://github.com/KomodoPlatform/developer-docs/pull/158

that's a useful feature and many users want/need that afaik

**Comment by lightspeed393** [comment]
Duplicate of #588

**Comment by smk762** [comment]
Implemented in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/599
