### ISSUE TITLE
[BUG]: Welcome screen not translated

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#628]
**Describe the bug**

New Wallet / Recover Wallet / Welcome not translated but it's the first screen user see after download

<img width="1436" alt="Screenshot 2021-01-14 at 09 54 48" src="https://user-images.githubusercontent.com/24797699/104538630-d2435d00-564e-11eb-9c1a-091dd6fad9b1.png">

**Comment by naezith** [comment]
Is it not being localized or are the translations missing?

**Comment by tonymorony** [comment]
@naezith just checked in code and it's not translated, localisation in place
thanks for a good question :)

**Comment by tonymorony** [comment]
Was translated
