### ISSUE TITLE
[BUG]: App UX stop refresh after put PC into sleep mode

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#630]
**Describe the bug**
After I put PC into standby mode and then wakeup app stops to refresh coin balances and orders in orderbook on selectors switch.
Then after I change the language in settings (or restart the app) app starting to work as usual.
Reproduced it on mac/windows laptops (e.g. closing the lid, going to lunch - when open the lid have to restart the app), and desktop windows PC which

**To Reproduce**
1. Put PC into sleep mode
2. Wait some time
3. Try to change selectors in orderbook or receive a transaction and check balance change

@smk762 would be great if you try to reproduce that on your side

marketmaker continue to react correctly on selectors change:

e.g.

```
18 07:40:16, lp_ordermatch:3566] Orderbook response {"askdepth":0,"asks":[],"base":"RICK","biddepth":0,"bids":[],"netid":7777,"numasks":0,"numbids":0,"rel":"BTC","timestamp":1610955616}
```

![paste (4)](https://user-images.githubusercontent.com/24797699/104886034-a18b5c80-599b-11eb-851c-daad902855d7.png)

also was able to broadcast tx (but txhistory/balance not updating)

**Comment by smk762** [comment]
Tested on win desktop, put to sleep manually.
Upon awaking after sleep, "waiting for connection". Once connected, coins sent while asleep appeared withing 30 seconds. A subsequent send of coins also appeared soon after in DEX, Wallet and Dashboard screens.
Will test again with a longer sleep (non-manual).
