### ISSUE TITLE
[BUG]: "show only coins with balance" doesn't keep it's visual state on tab switch

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#631]
**To Reproduce**
1. Enable "show only coins with balance"
2. Switch to DEX tab
3. Switch back to the Dashboard
4. See toggle deactivated (however 0 balance coins hiding)

**Expected behavior**
The toggle should keep its state (visually)

**Comment by SylEze** [comment]
Fixed in 0739af82a93d2bdf7589c4359f10187168598245

**Comment by tonymorony** [comment]
Thanks for a prompt fix
