### ISSUE TITLE
[FEATURE REQUEST]: Addressbook tweaks

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#645]
A few suggestions to improve Addressbook UX - sometimes it feels a bit like I'm clicking too much to get where I want to be.

On this modal, I think it would be better to show the complete list of stored addresses for a contact in the table, rather than have to define the coin or coin category to have them displayed. 

![image](https://user-images.githubusercontent.com/35845239/105806010-20a51400-5fde-11eb-83a3-7fc641c917a6.png)

IMO, the "change of wallet type" button would be better as a filter than a selector (e.g. show all by default, filter to selected)

This change would mean that when user is adding a new address, they would need to click the "new" button first, then select the coin. Currently the "new" button is inactive/disabled until the "change of wallet type" is defined.

Another feature that could reduce number of clicks to get where I'm going would be to auto-apply the filter of addresess when clicking into addressbook from the wallet page, to match the coin active on the wallet page's send modal.

![image](https://user-images.githubusercontent.com/35845239/105806471-0881c480-5fdf-11eb-971c-9ea6a6776560.png)

Currently if I click on the "Address book" button in this modal, it is no different than clicking on to addressbook tab from the sidebar menu, then I have to specify the coin all over again.

The addressbook selection flow is "contact > coin > address". Perhaps it might be more efficient to have the addressbook table display ALL contacts, coins, and addresses, and then allow filtering by contact, filtering by coin and/or filtering by address. 
i.e. separate the "add new" flow from the "select to send" flow.

Rough concept image below
![image](https://user-images.githubusercontent.com/35845239/105808870-8ba51980-5fe3-11eb-945a-1448ec1a7a3b.png)

Note edit/delete icons added to row for each address for future removal or modification.

Form to add/edit contacts like below.
![image](https://user-images.githubusercontent.com/35845239/105809418-9dd38780-5fe4-11eb-8d86-1581a32b2945.png)

I think something like this could streamline the use of the addressbook, allowing for less clicks to achieve the same outcomes.

**Comment by SylEze** [comment]
I think that having everything gathered: contact name, coin type, address and tags in one single view is too much. However I'm not against having every address of whatever coin in the contact edition modal table. I'm also not against having less modals and simplify usage.

**Comment by tonymorony** [comment]
Addressbook implementation on mobile is quite clean and usable - you can install mobile app and try if insipartion will be needed. Moreover, @yurii-khi added tx notes / address book import/export so we can do it cross-platform compatible maybe in the future

One more current issue not mentioned above is that on default non-fullscreen view buttons cutting so only way to use addressbook is to stretch it full screen

![image](https://user-images.githubusercontent.com/24797699/106450115-599a2880-64b7-11eb-8c70-965215131b75.png)
