### ISSUE TITLE
[BUG]: multiple taskbar icons

### ISSUE THREAD

**Issue by lightspeed393** [KomodoPlatform/atomicDEX-Desktop#653]
**Describe the bug**
After logging out of a wallet and logging into a different wallet, another AtomicDEX icon is added to the taskbar.

**To Reproduce**
1. Login to wallet
2. Log out of wallet
3. Login to another wallet
4. See multiple AtomicDEX icons in taskbar/top bar

**Expected behavior**
Only 1 AtomicDEX icon in the top taskbar.

**Screenshots**
![atomicdex_taskbar_icon_bug](https://user-images.githubusercontent.com/61478086/106039774-83161700-60a7-11eb-8d84-4b0270fbe59a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: v0.4.0

**Comment by tonymorony** [comment]
fixed in current dev
