### ISSUE TITLE
[BUG]: The orders list doesn't change when I select a different pair

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/atomicDEX-Desktop#659]
**Describe the bug**

It happened to me only once but I report the case. 

The app had been running for a few days, open on the trade tab with the KMD/VRSC market. After a few days it always showed the KMD/VRSC orders list when I change to any other pair 

Restarting the app fixed it

**To Reproduce**
1. Open the app on the Trade tab with a specific pair
2. Let the app run a few days
3. Try to select a different pair
4. It continues to show the orders list for the original pair

**Expected behavior**
It should show the orders list for the new pair selected

**Screenshots**
Attached screenshots

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 3.1 Desktop

**Additional context**
Restarting the app fixed the problem, still unable to reproduce but I'll let it run a few days and check again
![Schermata del 2021-01-28 23-57-44](https://user-images.githubusercontent.com/35692099/106278335-da002580-623a-11eb-85b9-b0fc6ecbb619.png)

**Comment by Milerius** [comment]
hey @barbierir it's should be fixed in dev branch - you should be disconnected if you lost connection

**Comment by barbierir** [comment]
Ok, I reproduced the issue after a few days. I'll try again with dev and next release and I will reopen the issue in case it happens again
