### ISSUE TITLE
[BUG]: Problems when too many coins enabled

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#668]
If too many coins are enabled, Coinpaprika API requests can be rate limited, resulting in attempting to enable coins not working, and attempting to enter the settings menu results in a "spinning circle" state.

**To Reproduce**
1. Open App
2. Enter activation menu
3. Select enable all
4. Enable the coins
5. Try to go to settings menu, or enable additional coins later that failed to enable.

**Suggested Soultions**
- Rate limit Coinpaprika API calls
- Enforce a hard maximum number of coins that can be enabled
- Remove the "Enable All" button.
- Add a hint mocal

**Comment by Milerius** [comment]
I propose to speedup development of https://github.com/Milerius/Niloticus which will be a market aggregator automatically fetching from oracle_band/oracle_link/coingecko/coinmarketcap/paprika/binance dex with generic response format that we can discuss with mobile team will also solve this pb because after that every `atomicDEX` project can use the Market Aggregator `Niloticus` with cached values

**Comment by tonymorony** [comment]
Yes, I think a simple go/python "price proxy" script we can do quite fast.

It can: 

a) pre-fetch all data every x seconds from coinpaprika or whatever

b) store it (in JSON file or db)

c) then the user receives data from this data source (any webserver on top to share this static constantly updating price info with endusers)

Sounds mostly like a one evening webserver configuration task.

Are you sure we need to make a complex C++ program for that?

**Comment by Milerius** [comment]
> Yes, I think a simple go/python "price proxy" script we can do quite fast.
> 
> It can:
> 
> a) pre-fetch all data every x seconds from coinpaprika or whatever
> 
> b) store it (in JSON file or db)
> 
> c) then the user receives data from this data source (any webserver on top to share this static constantly updating price info with endusers)
> 
> Sounds mostly like a one evening webserver configuration task.
> 
> Are you sure we need to make a complex C++ program for that?

@tonymorony Yes i think C++ is perfectly adapted for this kind of program + i can reuse the utilities from atomicdex such as coin configuration parsing - the project itself is not rly hard consist into 2 binaries:

- Worker -> fetch every N Seconds and store it in the cache/db as the standard data format
- Server -> read the standard format from DB / Cache and expose it to a nice API

We don't need to be cross platform only UNIX support is enough which make a C++ a good choice.

The good things with c++ is the performance, even if we read lot of tickers data from cache it's should be super fast regarding http answer

**Comment by smk762** [comment]
current dev build is no longer causing problems with large amount (or all) coins enabled.
