### ISSUE TITLE
[BUG]: notifications for REV and REVS transactions that don't exist

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#673]
I get a lot of notifications (every minute) for REV and REVS transactions that don't exist:
![image](https://user-images.githubusercontent.com/32116761/107558698-03259c00-6bd3-11eb-874a-ac85373bbd38.png)
Only happens with REV/REVS and the amount is always the same.
REV does not have any transactions at all, REVS has this ones:
![image](https://user-images.githubusercontent.com/32116761/107558928-4d0e8200-6bd3-11eb-8b64-82370ca4ad7e.png)

EDIT: saw that the balance of REVS is exactly 0.00087 (the amount of the fake transactions)... it's for sure related to the problem.

**Comment by SylEze** [comment]
Solved by #676

**Comment by smk762** [comment]
haven't come across this on any OS in latest dev build

**Comment by cipig** [comment]
Works fine now, thanks for the fix.
