### ISSUE TITLE
[BUG]: Send page contact list does not display contacts with coin type addresses (e.g. ERC20)

### ISSUE THREAD

**Issue by SylEze** [KomodoPlatform/atomicDEX-Desktop#696]
**Describe the bug**
The send page contact list is displaying only contacts with an address type equivalent to the selected coin. 

However let say that the given coin is a `Smart Chain` coin: KMD, the contact list will not display any address of type `Smart Chain`, only the KMD ones

**To Reproduce**
- Having a contact with a `Smart Chain` address
- Go to the wallet page
- Choose `KMD` and click on `Send`
- Click on `Address Book`
- The contact with a `Smart Chain` address does not appear even though it should be compatible with `KMD`

**Expected behavior**
Display every contact which has a compatible address with the selected coin.

**Comment by Milerius** [comment]
done in #697
