### ISSUE TITLE
[FEATURE REQUEST]: Change dPoW settings based on value of trade.

### ISSUE THREAD

**Issue by lightspeed393** [KomodoPlatform/atomicDEX-Desktop#702]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, more of a inconvenience, but dPoW can make trades take up to an hour or longer. This can be a negative thing for AtomicDEX, especially for traders expecting CEX like trade times.

**Describe the solution you'd like**
When placing the order, calculate the value of the trade and if it's below `x` amount, disable dPoW automatically. User could still enable it if they want extra security. Maybe there could be an option in the wallet settings that each user can set what the `x` amount is to them. 

**Additional context**
![image](https://user-images.githubusercontent.com/61478086/108579042-2b0fb080-72f3-11eb-9938-8b01aeafa439.png)

**Comment by TheComputerGenie** [comment]
Maybe instead of "disable below _x_" just do as someone suggested in discord and disable and suggest above _x_?
Three's a fine line between "looking out for users" and "forcing control because I think _y_"

**Comment by smk762** [comment]
@Milerius @tonymorony we already have the ability for user to select custom confirmation settings, which seems better than making this decision for the user based on a threshold of 'x' which they may not be aware of or not in line with their risk tolerance (unless configurable in settings). 
I think we can close this issue.
