### ISSUE TITLE
[FEATURE REQUEST]: Trading chat room

### ISSUE THREAD

**Issue by Jcharming** [KomodoPlatform/atomicDEX-Desktop#710]
**Is your feature request related to a problem? Please describe.**

Communication channel for being able to trade with peers that are also investigating trad opps using decentralized orderbooks.

**Describe the solution you'd like**

Add trading chat rooms for each coin please. Starting with 1 "troll box" that users of AtomicDEX can use to communicate with each other. 

**Describe alternatives you've considered**
Chat channels in discord - using my fav social media channels to communicate with others. 

**Additional context**
my son ay son added chat to his agario game server and it blew up

**Comment by kmdkrazy** [comment]
User would need a KMD deposit to use the troll box

**Comment by kmdkrazy** [comment]
start with 1 trading troll box and then when it fills up you can start making 1 for each coin when they change from Base/Rel the roll box "can" change with it and you can keep the Lobby or create a Free to Troll box

**Comment by kmdkrazy** [comment]
0 KMD = Novice Trading Room, 10 KMD = Intermediate Trading Room, 100 KMD = Advanced Trading Room

**Comment by kmdkrazy** [comment]
Crabby PaddyToday at 9:30 PM
Special badges for achievements too 
Tylor inDEXToday at 9:37 PM
This is a great idea - goto github and comment --- its a GREAT idea for P2P
[9:38 PM]
The Golden Lizard Badge  @Crabby Paddy
[9:40 PM]
this is the score system that allows future nSPV - Sub Atomic trades

**Comment by kmdkrazy** [comment]
Crabby PaddyToday at 9:40 PM
I have no account but if anyone wants to comment on git 
[9:41 PM]
Maybe some fun badges too like
[9:41 PM]
Buying a coin 20% under market rate for an achievement
[9:41 PM]
“Low baller”
[9:41 PM]
Arbitrage king
[9:41 PM]
Hodler etc
[9:41 PM]
Coloured names too 
[9:42 PM]
Holding over 50 coins in same wallet etc

**Comment by kmdkrazy** [comment]
#talk-trading

**Comment by smk762** [comment]
Merged into https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1606
