### ISSUE TITLE
[FEATURE REQUEST]: Pie chart on dashboard for assets repartition

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#718]
**Is your feature request related to a problem? Please describe.**

For now the dashboard page is just a table but it could be more complete and integrate the repartitions of the assets.

**Describe the solution you'd like**

Pie chart like on the figma models.

**Comment by ssakone** [comment]
this piechart ?
![image](https://user-images.githubusercontent.com/39985611/109272744-35590f80-7809-11eb-9a16-5311ec1b7f3e.png)
