### ISSUE TITLE
[BUG]: Typing text and clicking buttons not working correctly

### ISSUE THREAD

**Issue by Cykey** [KomodoPlatform/atomicDEX-Desktop#724]
I**Describe the bug**

I have the desktop version on W10. When I first downloaded it and clicked on the box to type in the password nothing happened, i.e. I could not see any indication that I had typed anything, however if I maximized or minimized the DEX window only then would it be apparent I had typed anything. I assumed this to be a signup glitch so I finished the signing up. But the same issue happens when I am on the Dashboard, for example if I click from Wallet to Settings or Address Book, etc. it's as if I clicked nothing until I mouse-click-hold the window and move it around on my monitor screen or maximize/minimize the DEX, only then does my action show up. So, I did a complete uninstall, waited a few days, and reinstalled it from your official link, but it's doing the very same thing. Please advise what could be the issue here and any way I can fix this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10 Pro OS Build 19041.804
 - Browser [e.g. chrome, safari] - FIREFOX 86.0 (64-bit)
 - Version [e.g. 22] - 2004
 

**Additional context**

**Comment by smk762** [comment]
@Cykey I've not seen this behaviour, can you please let us know if it persists in latest version?

**Comment by smk762** [comment]
Closing this issue as I have not encountered it during testing. Suspect could be isolated to reporting user's environment.
@Cykey please advise if this is resolved, or if it persists, please provide more information regarding your PC hardware.
