### ISSUE TITLE
[FEATURE REQUEST]: Remove seednode param from config generation

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#738]
since we got peer discovery mm2 connecting to the DNS seeds first: https://github.com/KomodoPlatform/atomicDEX-API/blob/mm2.1/mm2src/lp_native_dex.rs#L46

and these seeds sharing client list: https://github.com/KomodoPlatform/atomicDEX-API/blob/mm2.1/mm2src/mm2_libp2p/src/atomicdex_behaviour.rs#L531

**Comment by tonymorony** [comment]
Was it implemented? @Milerius @smk762

**Comment by Milerius** [comment]
> Was it implemented? @Milerius @smk762

Not yet, after #759  #773 this will be immediatly implemented
