### ISSUE TITLE
[BUG]: Crash on "Open logs folder" button click (OSX)

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#739]
(tried only on M1 macbook so far)

To reproduce:
1) Go to settings
2) Press "Open Logs Folder"
3) Insta crash

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unable to parse the string "" as a floating point value.
[15:52:29] [error] [main.prerequisites.hpp:137]: sigabort received, cleaning mm2
No matching processes belonging to you were found
[15:52:29] [error] [main.prerequisites.hpp:143]: stacktrace:  0# main in /Applications/atomicdex-desktop.app/Contents/MacOS/./atomicdex-desktop
 1# _sigtramp in /usr/lib/system/libsystem_platform.dyl
```

upd, crashes with same trace happens not only on log pressing only. also caught when pressed notifications button and during interaction with dex page

upd, noticed a correlation between connectivity problems - might be resolved by / related to https://github.com/KomodoPlatform/atomicDEX-API/issues/846

**Comment by smk762** [comment]
ok in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/726
