### ISSUE TITLE
[BUG]: Filter not disabling on Filter button click if not ALL/ALL state was selected

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#741]
Video demonstration: https://drive.google.com/file/d/1W8qA8S_rq3OrHn_OGsqfBd0drAXOBXyx/view?usp=sharing

**Comment by smk762** [comment]
https://user-images.githubusercontent.com/35845239/122672784-eee85000-d1ff-11eb-94f2-ad2b338b865d.mp4

Current state in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930:

- Apply button stays active when filter fields have changed and then are hidden
- hiding filter fields keeps filter active, with no indication of what filter is. Suggest either it is locked open while a filter is in effect, or some "filter summary" text appears in space next to filter button when fields are hidden.

e.g. 
![image](https://user-images.githubusercontent.com/35845239/122673007-1d1a5f80-d201-11eb-9329-b6abc4b7b442.png)

**Comment by SylEze** [comment]
I think it can be closed atm

![couldbeclosed](https://user-images.githubusercontent.com/14373103/128853665-8df098f8-92c7-4927-ad8d-1f6e515298e3.PNG)

**Comment by tonymorony** [comment]
yep, looks like this one is fixed atm, thanks for the heads up!
