### ISSUE TITLE
[BUG]: 24h price change displaying for 0 price coins when dashboard currency switched to KMD or BTC

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#742]
(it using reversal KMD/BTC 24h change atm, but it should be 0 since we don't know at what price 0 price assets trading and what was their value change last 24h)

<img width="1432" alt="Screenshot 2021-03-12 at 16 53 06" src="https://user-images.githubusercontent.com/24797699/110923502-8f062180-8353-11eb-9ae2-d5556942b763.png">
<img width="1432" alt="Screenshot 2021-03-12 at 16 52 52" src="https://user-images.githubusercontent.com/24797699/110923533-96c5c600-8353-11eb-9a07-b34514a4e2e7.png">

**Comment by smk762** [comment]
percentage now only shown in fiat view
