### ISSUE TITLE
[BUG]: Band oracle last data link is not correct

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#743]
![Screenshot 2021-03-12 at 17 00 58](https://user-images.githubusercontent.com/24797699/110924420-97129100-8354-11eb-846c-8596f6a6e465.png)

pointing to https://guanyu-poa.cosmoscan.io/request/2041635 which calling data for stocks I believe (`["AAPL","GOOGL","TSLA","NFLX","QQQ","TWTR","BABA","IAU","SLV","USO","VIXY","AMZN","MSFT"]
`)

**Comment by smk762** [comment]
Last reference (Band Oracle) field is now empty?
![image](https://user-images.githubusercontent.com/35845239/111902142-d5a3fc00-8a76-11eb-974f-ee920d95ec45.png)

**Comment by smk762** [comment]
Can we close this? No longer see band oracle info icon etc, and afaik not using for prices anymore?

**Comment by smk762** [comment]
Issue is stale and no longer applies.
