### ISSUE TITLE
[BUG]:  OSX High CPU Usage

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#747]
**Describe the bug**

When starting multiple swaps kernel tasks start to activate and growth to take all the CPU usage
about kernel_task: https://www.makeuseof.com/tag/fix-mac-kernel-task-high-cpu-usage/

It's a security by the kernel that is trigger when too much cpu is use on a thread (here it's the main thread)

The problem is mostly from this file: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/trade_improvements/atomic_defi_design/qml/Exchange/Trade/Orders/SwapProgress.qml

But the problem also happens on the orders list in the trading page

Few solutions:

- Move the whole logic to backend and just use appropriate fields in the front-end (Even it's not only for visuals it's will worth to move it to the backend to avoid cpu spike, i believe c++ code will be more efficient)
- Do the update part of the timer in the backend

Other files to check: 

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/trade_improvements/atomic_defi_design/qml/Exchange/Trade/Orders/OrderList.qml#L53

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/trade_improvements/atomic_defi_design/qml/Exchange/Trade/Orders/OrderModal.qml#L156

**To Reproduce**
1. Go to Trading Page
2. Start some swaps
3. Stays on the order list and wait (optionally open the trade progress page)
4. See cpu growth

**Expected behavior**
Normal CPU usage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Big Sur
- Version: 0.4.0 and more

**Comment by smk762** [comment]
improved in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/726

**Comment by Milerius** [comment]
It's seems that the problem persist even with the recent fix, harder to trigger - @ssakone @SylEze 

Spinner seems to still be the issue (high cpu is not triggered without spinner)

Dirty solution: disable spinner on osx
Less dirty solution: disable spinner on macbook pro
Best solution: Make spinner consume less CPU

**Comment by Milerius** [comment]
Temporary disabled spinner on osx, works now.
