### ISSUE TITLE
[BUG]: Clean orderbook after selector change

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#750]
**Describe the bug**
During debugging session with @artemii235 we've discovered that orderbook in GUI not cleaning on rel/base selector change until it receives a new order book from API. It might cause potentially dangerous situations.
It would be great to instant clean order book view on selector change and show spinner until response received.

Can be easily reproduced with connection limit to Edge by this tool lets say: https://nshipster.com/network-link-conditioner/

**Comment by smk762** [comment]
done in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/726
