### ISSUE TITLE
[BUG]: Track coins activation by `get_enabled_coins` RPC

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#751]
https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#get-enabled-coins
it'll allow:

a) track activation progress during the huge batch request
b) display activated coins deterministic way since API keep this info

**Comment by smk762** [comment]
This could also be used for "greying out" the not enabled coins in the best orders menu. Bonus points for some filter animation over the coin icon while it is in the process of being activated.

**Comment by tonymorony** [comment]
right now activation seems to be fine, closing this one since context is lost anyway
