### ISSUE TITLE
[FEATURE REQUEST]: Restore mm2 version and app version in settings

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#769]
**Is your feature request related to a problem? Please describe.**

It's seems that we don't have `mm2_version` and app version in the settings anymore, would be nice to restore it.

**Describe the solution you'd like**

A page `version` in the settings with all version information we use:

- Qt version
- mm2 version
- app version

**Describe alternatives you've considered**

- None

**Comment by ssakone** [comment]
ok i will fix it soon
