### ISSUE TITLE
[BUG]: Settings header are in french

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#770]
**Describe the bug**

<img width="878" alt="Capture d’écran 2021-03-27 à 10 30 26" src="https://user-images.githubusercontent.com/21139416/112716570-736c5080-8ee7-11eb-9ae5-3012c0770c5d.png">

**To Reproduce**
1. Launch AtomicDEX
2. Log in
3. Click on settings

**Expected behavior**

`General` instead of `Géneral`

**Comment by ssakone** [comment]
ok
