### ISSUE TITLE
[BUG]: Chart legends are ugly / not readeable / blurry - Color are not appropriate

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#790]
**Describe the bug**

Currently it is difficult to read the axes correctly, it is not pleasant for the eye. I propose to imitate the figma as much as possible

Use same color and fonts from Figma - don't make it blurry, don't make background effect, try to immitate figma as much as possible.

**To Reproduce**
1. Go to 'Portfolio'
2. Observe chart axis / line and color
3. Does it feel pleasant for the eyes ? 

**Actual behavior**

<img width="750" alt="Capture d’écran 2021-04-12 à 20 46 05" src="https://user-images.githubusercontent.com/21139416/114447080-464fbb80-9bd2-11eb-8a6c-3b8c583b7838.png">

**Expected behavior**

<img width="1233" alt="Capture d’écran 2021-04-12 à 20 58 31" src="https://user-images.githubusercontent.com/21139416/114447137-57003180-9bd2-11eb-9e0e-04a5eaeca710.png">

**Desktop (please complete the following information):**
 - OS: MacOS / Linux / Windows
-  0.4.0

**Additional context**

Portfolio improvements

**Comment by tonymorony** [comment]
moved comment from #829 here:

maybe dots removal will help

![image](https://user-images.githubusercontent.com/24797699/115205515-da1a0e00-a123-11eb-834e-b95a9fa0a9be.png)

without the dots looked better, also an orange color for the line looked good imo:

<img width="682" alt="Screenshot 2021-04-19 at 15 32 42" src="https://user-images.githubusercontent.com/24797699/115206194-8956e500-a124-11eb-8375-34dcd8ccb446.png">
