### ISSUE TITLE
[Feature Request]: Better layout for portfolio page

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#792]
**Describe the bug**

The current layout is not at all optimized, it prevents you from seeing the bottom table, we can do better and here is how:

<img width="1392" alt="Capture d’écran 2021-04-12 à 21 12 10" src="https://user-images.githubusercontent.com/21139416/114448661-1ef9ee00-9bd4-11eb-8401-0db6def796d2.png">

You can inspire from figma:
<img width="881" alt="Capture d’écran 2021-04-12 à 21 15 04" src="https://user-images.githubusercontent.com/21139416/114448694-2a4d1980-9bd4-11eb-9468-957d570ec8a7.png">

You can use small sidebar, having an horizontal portfolio, smaller chart and get the bottom table a bit higher.

**To Reproduce**
1. Go to Portfolio
2. Observe the layout

**Expected behavior**

A figma like approach

**Desktop (please complete the following information):**
 - OS: MacOS, Linux and Windows
 - Version 0.4.0

**Additional context**

Portfolio improvements

**Comment by ssakone** [comment]
i don't understand, where is the bug.

**Comment by Milerius** [comment]
> i don't understand, where is the bug.

updated the title
