### ISSUE TITLE
[BUG]: Scrolling on dashboard page problem

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#804]
**Describe the bug**
After I scroll down, I can't scroll up from all places

with cursor  position in area `1` I'm not able to  scroll
with cursor  position in area `2` I'm able to  scroll

<img width="1438" alt="Screenshot 2021-04-15 at 13 46 53" src="https://user-images.githubusercontent.com/24797699/114826047-32ce6b80-9df1-11eb-8514-cde960a5b26a.png">

**Comment by tonymorony** [comment]
Page also not scrollable in the area with assets so I'm kind of trapped when enable many coins and scroll down:

<img width="1680" alt="Screenshot 2021-04-19 at 15 25 10" src="https://user-images.githubusercontent.com/24797699/115205324-a50dbb80-a123-11eb-9700-e2f7c7e80051.png">

**Comment by Milerius** [comment]
> Page also not scrollable in the area with assets so I'm kind of trapped when enable many coins and scroll down:
> 
> <img alt="Screenshot 2021-04-19 at 15 25 10" width="1680" src="https://user-images.githubusercontent.com/24797699/115205324-a50dbb80-a123-11eb-9700-e2f7c7e80051.png">

I'm not able to reproduce on Linux, can you try in windows ?
