### ISSUE TITLE
[FEATURE REQUEST]: Take advantage of the new titlebar in the trading page

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#807]
**Is your feature request related to a problem? Please describe.**

I think now we can take advantage of the custom title bar to get some free space, it's will be advantageous for small screen and small resolution:

<img width="1326" alt="Capture d’écran 2021-04-15 à 17 39 52" src="https://user-images.githubusercontent.com/21139416/114897881-f3644700-9e11-11eb-92cf-628cb95f4be5.png">

**Describe the solution you'd like**

I propose to move the header of the trading page directly withing the custom title bar and to use the free space to drag everything up a bit

**Comment by ssakone** [comment]
tu peux me donner plus de details sur la disposition?

**Comment by ssakone** [comment]
is ok? 
![image](https://user-images.githubusercontent.com/39985611/114995812-bccc1200-9e8d-11eb-9525-e4fdc46ad12c.png)
