### ISSUE TITLE
[BUG]: Sum of Portfolio percentages > 100% under BTC

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#811]
Portfolio percentage displays as greater than 100% when expressed in KMD

**To Reproduce**
1. Go to Dashboard 
2. Click in center of portfolio pie chart until it shows value in BTC
4. See sum of portfolio value percentages > 100%

A simple check would be to just have KMD balance and disable all coins, you will see a value of over 100%.
![image](https://user-images.githubusercontent.com/35845239/115002258-1c9adb00-9ed7-11eb-9364-4b8e77c65041.png)

**Expected behavior**
Portfolio percentages should always sum to 100% 
This calculation error also appears with more coins with balance active. e.g.

When set to BTC
![image](https://user-images.githubusercontent.com/35845239/115004556-80be9e80-9ed9-11eb-8f7c-f985d480ee67.png)

63.54+26.64+8.16+1.83 = 100.17

When set to fiat (AUD)
![image](https://user-images.githubusercontent.com/35845239/115003759-b44cf900-9ed8-11eb-9bec-c85a1b9cd6f8.png)

63.88+26.16+8.15+1.79 = 99.98 (could be due to rounding)

When set to KMD
![image](https://user-images.githubusercontent.com/35845239/115004040-f9712b00-9ed8-11eb-94a2-e964148492aa.png)
63.64+26.35+8.20+1.81 = 100

**Comment by Milerius** [comment]
it"s done in 0.4.2
