### ISSUE TITLE
[BUG]: Clicking within pie chart locks screen while calculations are done

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#812]
When clicking on the circle to change from BTC to KMD to fiat values, the app is unresponsive for a few seconds while values update

**To Reproduce**
1. Go to Dashboard
2. Click in the center of the pie chart circle
3. Try to change tab or click on other active app area
4. See app unresponsive to click until values are calculated

**Expected behavior**
Value updates should not block ability to click on other parts of app

**Comment by ssakone** [comment]
please @smk762  can you send screen, i want to see what exactly happen.

**Comment by smk762** [comment]
Seems to be a bigger issue when more coins enabled with a balance.
https://user-images.githubusercontent.com/35845239/115053727-052d1380-9f12-11eb-9f38-5a97c6339c43.mp4
before clicking to change the text in centre of circle, the mouseovers are working, highlight the coin sections etc.
Then click in center, and for a few seceonds, mouseover effects dont work, and all other active elements on screen are locked while new values are calculated.

**Comment by Milerius** [comment]
I think i've solved it in dev branch @smk762  can you check on all platform and close the issue if it's the case ?

**Comment by smk762** [comment]
Responsive now on all OS, thanks
