### ISSUE TITLE
[BUG]: Settings > UI > Apply theme button does nothing

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#822]
In the Settings screen, User Interface tab, selecting "light" theme and clicking the "Apply Theme" button doesn't change the theme.

**To Reproduce**
1. Go to Setting screen, User Interface tab
2. Select light.json Theme, and click "Apply Theme" button.
3. See no change to app theme

**Expected behavior**
Light theme activates

![image](https://user-images.githubusercontent.com/35845239/115099936-d3e13180-9f6b-11eb-9304-3b8636ffe9e2.png)

**Comment by Milerius** [comment]
> In the Settings screen, User Interface tab, selecting "light" theme and clicking the "Apply Theme" button doesn't change the theme.
> 
> **To Reproduce**
> 
> 1. Go to Setting screen, User Interface tab
> 2. Select light.json Theme, and click "Apply Theme" button.
> 3. See no change to app theme
> 
> **Expected behavior**
> Light theme activates
> 
> ![image](https://user-images.githubusercontent.com/35845239/115099936-d3e13180-9f6b-11eb-9304-3b8636ffe9e2.png)

Hey @smk762 he seems you are outdated regarding your theme, please manually delete your theme folder in your appdata folder, this will work

**Comment by smk762** [comment]
Yep thanks, resolved.
