### ISSUE TITLE
[UI]: Addressbook table style inconsistent with rest of app

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#823]
![image](https://user-images.githubusercontent.com/35845239/115101016-82d53b80-9f73-11eb-9526-0684b2cd2d59.png)

- Suggest removing white border from table.
- When save address list is long enough to require scrollbar, it cuts off part of the send icon on the right
- Suggest scrollbar style changed to same style as in other pages.

**Note:** the border and scrollbar issue seem to only present initially after first loading the app, later on it appears as it should (see below)
![image](https://user-images.githubusercontent.com/35845239/115100999-5e795f00-9f73-11eb-9273-a7b71ba63b85.png)

**Comment by SylEze** [comment]
I cannot reproduce your issue with the border, it does not appear on first launch
I will manually disable the frame and let me know if it's good

**Comment by smk762** [comment]
Fixed in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/841
