### ISSUE TITLE
[BUG]: Portfolio pie chart not updating when funds received

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#824]
Value within the chart updates, but zero balance coins with funds sent to them after loading do not appear in the chart and internal text says "0 assets".

![image](https://user-images.githubusercontent.com/35845239/115107190-ec694000-9f9b-11eb-885b-1c7ba58f7b7b.png)

After restarting the app, funded coins appear.

**To Reproduce**
1. Open app with fresh wallet (no funds on coins)
2. Send some funds to addresses in new wallet
3. See chart portfolio value inside circle updates, but no color added to circle, and "0 assets" text within.

**Expected behavior**
As balances update (specifically from coins previously without balance), the chart should update the count and pie chart color arc for newly funded coin.

**Comment by Milerius** [comment]
i think i solved it in dev branch can you check @smk762 and close if it's the case ?

**Comment by smk762** [comment]
fixed, thanks.
