### ISSUE TITLE
Aeternity coins support

### ISSUE THREAD

**Issue by willmendil** [KomodoPlatform/atomicDEX-Desktop#828]
Is there a reason I cannot find Aeternity coins?

**Comment by lightspeed393** [comment]
For a coin to be included here, it must first be added to the [KomodoPlatform/coins](https://github.com/komodoplatform/coins) repo.

That repo lists the rpc commands that are necessary to work with AtomicDEX-API. If it's not a btc clone, which afaik it doesn't appear to be, work would need to be done to the core to make it compatible.

**Comment by smk762** [comment]
Closing issue until coin added to KomodoPlatform/coins repo.
