### ISSUE TITLE
[BUG]: Validity [VAL] added to 0.4.2-beta

### ISSUE THREAD

**Issue by michelvankessel** [KomodoPlatform/atomicDEX-Desktop#839]
I have maybe a stupid request, but going to try it :-)

Validity [VAL] has been added to https://github.com/KomodoPlatform/atomicDEX-Desktop/releases/tag/0.4.2-beta. Thank you for that! 

Is it possible you can mention this also in the release notes? 

Thanks!

**Comment by Milerius** [comment]
done

**Comment by michelvankessel** [comment]
thank you very much!
