### ISSUE TITLE
[ENHANCEMENTS]: Extract the connection logic from mm2 service to a standalone service and add reconnection support

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#843]
**Is your feature request related to a problem? Please describe.**

Currently the mm2 service contains too many different things, it would be easier to move the enable / disable coins part to a separate service which could also handle all error cases.

On top of that, the current behavior is too unpredictable, if every corner fails to activate, the application is not behaving adequately, it would be better to do something more solid with attempts to reconnection in background without disturbing the user

**Describe the solution you'd like**

A separate service that could take care of the electrum / enable part of mm2, error management, each activation of assets leads to an important sequence of events:

- Enabling an asset into mm2
- Fetching coins market infos (from coingecko api)
- Emit a final event when everything is done to wake up the models

(All those steps are already cover by mm2 and the coingecko service, please check actual behaviour and improve it)

**Describe alternatives you've considered**

Websocket possibility for enabling coins, getting events from mm2

**Comment by smk762** [comment]
@Milerius would this perhaps resolve the mm2 connection loss issue cipi reported?
