### ISSUE TITLE
[FEATURE REQUEST]: Automatic release at each commit to master

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#844]
**Is your feature request related to a problem? Please describe.**

Currently we have to release manually after each commit to master, we have to automate the releases (we can do it without changelog at the beginning) or then generate one with https://www.conventionalcommits.org/en/v1.0.0/

We also need to change the name of the binaries generated by atomicdex in general so that they contain the current version (we can follow the current logic in the workflow of the CI)

When the release will be generated automatically, it is also necessary to automatically manage the virustotal reports and update the json checksum automatically on the server @tonymorony please help @SylEze to find a solutions in this regards

**Describe the solution you'd like**

Something similar to the atomicdex api approach which has an automatic release every time a commit is merged on the main branch (with us it will be master)

**Comment by tonymorony** [comment]
that's an unsafe practice for multiple reasons, in general, we shouldn't use CI builds for releases but build in secure env instead
