### ISSUE TITLE
[FEATURE REQUEST]: Change the way to change lang in the UI/UX

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#847]
**Is your feature request related to a problem? Please describe.**

For now with each new language this adds a flag to an already too long list, it would be better to switch to a selector and use the QMLSettings for that rather than the settings of the c++ program directly, for this task you will have to study the c++ code correctly to remove the old behavior and add the new one in the general qml settings (Supported languages, current language and what happens when you change language)

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/9f01c07035b4c0645323cbe5bc97553385e36170/src/core/atomicdex/pages/qt.settings.page.cpp#L88

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/9f01c07035b4c0645323cbe5bc97553385e36170/src/core/atomicdex/pages/qt.settings.page.hpp#L76

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/9f01c07035b4c0645323cbe5bc97553385e36170/src/core/atomicdex/pages/qt.settings.page.hpp#L97

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/9f01c07035b4c0645323cbe5bc97553385e36170/src/core/atomicdex/pages/qt.settings.page.hpp#L43

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/cfg.json

https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/9f01c07035b4c0645323cbe5bc97553385e36170/src/core/atomicdex/pages/qt.settings.page.hpp#L103

With QML Settings all this code will became useless and will need to be removed

However, the set_current_lang can be changed to `change_lang` and still use the same behaviour just using QML Settings.

**Comment by Milerius** [comment]
partially implemented in #848

**Comment by smk762** [comment]
@Milerius can we close this one?

**Comment by smk762** [comment]
Closing. Note added to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1803 for later review
