### ISSUE TITLE
[BUG]: Custom ERC20 token send fees showing zero currency fee and not showing Ethereum fees

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/atomicDEX-Desktop#853]
**Describe the bug**
I've added a custom ERC20 token. When I press Prepare before send I see the token fees as 0 and no Eth fees are shown. I'm facing this with version 4.2. I've version 3.1 that shows fees in Eth.

**To Reproduce**
1. Add custom token
2. click send and put an eth address
3. Press prepare
4. See fees are zero

**Expected behavior**
Fees should be shown in Eth

**Screenshots**
version 4.2
![image](https://user-images.githubusercontent.com/411046/115947090-18ba1a80-a4ce-11eb-95f1-6c61192b2ab1.png)

version 3.1
![image](https://user-images.githubusercontent.com/411046/115947250-14dac800-a4cf-11eb-9d5e-218d6478d5af.png)

**Desktop (please complete the following information):**
 - OS: Linux appimage
 - Version 4.1 Beta

**Additional context**
Token price is shown correctly in my wallet.

**Comment by Milerius** [comment]
Hey @damascene - can you please share the config of your custom ERC20 ? You can find it in ~/.atomic_qt/config/0.4.2-coins.your_wallet.json

**Comment by Milerius** [comment]
Should be fixed in dev @smk762 https://github.com/KomodoPlatform/atomicDEX-Desktop/actions/runs/779993564 can you confirm and close the issue after the CI passed and you tested it ?

**Comment by smk762** [comment]
Confirmed fees in ETH as expected
