### ISSUE TITLE
[BUG]: BEP-20 trades when no BNB show no warning until confirmation

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#855]
If user has funds (e.g. DOGE) and wants to trade (sell) for BNB or BEP-20 coin, no warning tooltip is displayed such as it does on buy side as below
![image](https://user-images.githubusercontent.com/35845239/115957143-6157ef00-a533-11eb-90ad-2bbca67a263d.png)

Instead, waning only appears once trade confirmation window pops up as below - 
![image](https://user-images.githubusercontent.com/35845239/115957168-80ef1780-a533-11eb-8f38-323127e7b663.png)

**To Reproduce**
1. Have 0 BNB balance
2. Attempt to sell another coin for BNB or a BEP-20 coin

**Expected behavior**
Tooltip warning should appear, and user should not be able to click on orderbook leading to activation of "Start Swap" button and then confirmation screen. Warning should be displayed before user gets that far.

**Comment by Milerius** [comment]
>  Tooltip warning should appear, and user should not be able to click on orderbook leading to activation of "Start Swap" button and then confirmation screen. Warning should be displayed before user gets that far.

This case is very specific, it's only for trades that have a parent chain - I find the current error to be pretty self-explanatory.

However, you should know that when you sell an asset (here DOGE) - your minimum amount is expressed in DOGE, not in BNB making an exception for trades which have a parent chain is possible, but will result in a draft and not very maintainable code - I will still see what I can do to have a better UX / UI on this point

**Comment by smk762** [comment]
I understand the warning, it is just confusing for some users when not seen until confirmation pop up. Also the buy/sell form is active (sell side) when probably should not be on the same pair.

https://user-images.githubusercontent.com/35845239/115957499-6c138380-a535-11eb-8ecf-52a353e255aa.mp4

If we can disable form and avoid user getting to confirmation screen they might be less confused.

**Comment by Milerius** [comment]
> I understand the warning, it is just confusing for some users when not seen until confirmation pop up. Also the buy/sell form is active (sell side) when probably should not be on the same pair.
> 
>  kmd_BNB.mp4 
> If we can disable form and avoid user getting to confirmation screen they might be less confused.

I added a warning for empty parent chain or disabled parent chain in this situation
