### ISSUE TITLE
[FEATURE REQUEST]: Make orders/history widget generic to re-use it on simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#867]
Preparation to: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/625

Also needs fixes for issues described in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/846 (probably @Milerius can elaborate on it, provide more examples)

**Comment by ssakone** [comment]
In ui part its already generic, just new to add it in simple trading view

**Comment by ssakone** [comment]
> Preparation to: #625
> 
> Also needs fixes for issues described in #846 (probably @Milerius can elaborate on it, provide more examples)

Ok i will make it soon

**Comment by tonymorony** [comment]
> In ui part its already generic, just new to add it in simple trading view

Oh, cool. Closing this one so :)

> Ok i will make it soon

thanks! no rush, you can proceed to this one after ongoing notifications polishment finshed
