### ISSUE TITLE
[BUG]: wrong sort order in best orders

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Desktop#876]
![image](https://user-images.githubusercontent.com/32116761/116810353-d9757480-ab32-11eb-9929-1668fde99ccd.png)
when fiat price is low, the sort order is wrong

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/116810468-76381200-ab33-11eb-91d6-ea5072c824b9.png)
when coin has no fiat price, the order is also wrong on sell side

**Comment by Milerius** [comment]
> ![image](https://user-images.githubusercontent.com/32116761/116810353-d9757480-ab32-11eb-9929-1668fde99ccd.png)
> when fiat price is low, the sort order is wrong

We sort by fiat price and not by % change for the simple reason that we consider that the initial input in fiat (for example $ 500) and how much in value you can have in exchange (550 $ for the example) is is much more interesting information than the change in % as you can see on your screen.

**Comment by Milerius** [comment]
> ![image](https://user-images.githubusercontent.com/32116761/116810468-76381200-ab33-11eb-91d6-ea5072c824b9.png)
> when coin has no fiat price, the order is also wrong on sell side

Does the asset in question have a valid coingecko ID?

**Comment by cipig** [comment]
> Does the asset in question have a valid coingecko ID?
no, it doesn't, but on buy side, the sort order is correct, on sell side it seems inverted

**Comment by smk762** [comment]
Sort order is now based on percentage in both simple and pro views.
