### ISSUE TITLE
[FEATURE REQUEST]: Limit simultaneously activated coins amount 

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#884]
cf: https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/745

if the user activating all availiable coins now it might break the app (until he "reset assets configuration") with a high probability 
also, it might create a lot of file descriptors cf: https://github.com/KomodoPlatform/atomicDEX-API/issues/791 what can cause huge loading on user's machine/network and infra

I do propose 50 simultaneously activated coins as a starting point / reasonable limit

**Comment by Milerius** [comment]
> cf: [KomodoPlatform/AtomicDEX-mobile#745](https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/745)
> 
> if the user activating all availiable coins now it might break the app (until he "reset assets configuration") with a high probability
> also, it might create a lot of file descriptors cf: [KomodoPlatform/atomicDEX-API#791](https://github.com/KomodoPlatform/atomicDEX-API/issues/791) what can cause huge loading on user's machine/network and infra
> 
> I do propose 50 simultaneously activated coins as a starting point / reasonable limit

Maybe a child issue of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/843

**Comment by Milerius** [comment]
implemented in #886
