### ISSUE TITLE
[FEATURE REQUEST]: Disable all zero balance coins context menu option

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#905]
I have a bad habit of enabling all coins, because I'm too lazy to go thru the list and select them individually. The result of this ends up being a long list of mostly zero balance coins. The "show only coins with balance" toggle is nice, but it would be nicer to disable all the zero balance coins via a right click, similar as we have with disabling all coins of a specific type.

**Describe the solution you'd like**
Add a "disable coins with no balance" option to the right click context menu

**Describe alternatives you've considered**
Another option could be to do this via the "enable coins" form, with a checkbox that selects all zero balance coins, though this option is more clicking and less good in terms of UX.

**Comment by Milerius** [comment]
> I have a bad habit of enabling all coins, because I'm too lazy to go thru the list and select them individually. The result of this ends up being a long list of mostly zero balance coins. The "show only coins with balance" toggle is nice, but it would be nicer to disable all the zero balance coins via a right click, similar as we have with disabling all coins of a specific type.
> 
> **Describe the solution you'd like**
> Add a "disable coins with no balance" option to the right click context menu
> 
> **Describe alternatives you've considered**
> Another option could be to do this via the "enable coins" form, with a checkbox that selects all zero balance coins, though this option is more clicking and less good in terms of UX.

Excellent idea, i'm in !

**Comment by MrChriZ** [comment]
I came here to ask for exactly this!

**Comment by smk762** [comment]
Something like an extra option here `disable all coins without balance` would be awesome
![image](https://user-images.githubusercontent.com/35845239/132184742-8674f970-f0e8-45df-805a-f90c44af814d.png)
