### ISSUE TITLE
[FEATURE REQUEST]: Currency switch by click on top balance

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#957]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/951

it would be great to make new top balance clickable currency switcher (fiat - btc - kmd - ltc), same as on circle diagram 

<img width="285" alt="Screenshot 2021-06-07 at 16 52 49" src="https://user-images.githubusercontent.com/24797699/120996936-fac02500-c7b0-11eb-982d-55a47436d9c4.png">

**Comment by ssakone** [comment]
Ok, no problem.
