### ISSUE TITLE
[FEATURE REQUEST]: Add warning/confirmation on logout attempt

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#959]
It became easier to accidentally log out since it's in the top right corner menu + it's a good tone in general for logout operation

e.g.:
![image](https://user-images.githubusercontent.com/24797699/121008524-4b3d7f80-c7bd-11eb-94ea-2c036c30e94f.png)

**Comment by smk762** [comment]
Working here also, both from top bar and within settings. 
Suggested change to title / wording in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/970/files
