### ISSUE TITLE
[BUG]: Fiat evaluation on withdraw calculating not correctly if not fiat currency selected

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#962]
<img width="1276" alt="Screenshot 2021-06-09 at 16 35 19" src="https://user-images.githubusercontent.com/24797699/121331198-d8f5a800-c940-11eb-9acc-258094bb8bf7.png">

reproduced on both: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/951 and https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889 so shouldn't be a problem introduced by one of these PRs

Evaluation in `()` should be always in fiat on these page

**Comment by ssakone** [comment]
ok
