### ISSUE TITLE
[FEATURE REQUEST]: swaps history / swap progress reflection on simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#965]
my best idea so far is to make such tabs on a simple trading widget (it should be some simplified table to fit such a small area + on "In progress" we can show the only swap in progress instead of in progress + maker orders as on pro view
 
<img width="1177" alt="simple" src="https://user-images.githubusercontent.com/24797699/121403940-a3bf7900-c985-11eb-847f-5c030d182d56.png">

have swaps in progress/history on the separate tab (e.g. forward to pro view or have third "History" tab) will be quite confusing for the users because atomic swap taking a while and new user will be super stressed if not understand what's going on / where to see what's going on with his trade

ideally, it would be great to optimize swap progress for a simple view also to fit this small widget and contains less scary words

![image](https://user-images.githubusercontent.com/24797699/121404942-a9698e80-c986-11eb-86cb-d2cb5b41d2cd.png)

make it like a progress bar with bulbs and timer prob (and/or add some cool gif animation)

![image](https://user-images.githubusercontent.com/24797699/121405249-02d1bd80-c987-11eb-8f1f-9ff93309a138.png)

**Comment by Milerius** [comment]
implemented
