### ISSUE TITLE
[FEATURE REQUEST]: handle order state change after user selected it

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#966]
discovered that created issue on this matter in 2019 in mobile repo, cf: https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/480 cc @yurii-khi 

order state change = 
a) order with selected price does not exist anymore (was matched fully and gone from orderbook, or LP re-created it with different price)
b) volume of the order changed (was partially matched)

after the order is selected we can probably poll selected order state some way like this (that's just first/most straightforward idea came to mind, might be not optimal way.):

```python
selected_uuid = selected_order()["uuid"]
amount_user_selling = swap_form.amount
while True:
    time.sleep(1)
    pair_orderbook = get_orderbook(pair)
    uuids_list = []
    for order in pair_orderbook["bids"]: # or "asks"
        uuids.append(order["uuid"])
    # this check checking both a and b cases
    # checking if initial order still in the orderbook and if volume still covers amount user want to sell/buy
    if selected_uuid in uuids_list and pair_orderbook["bids"][selected_uuid]["volume"] <= amount_user_selling:
         print("Order still there and volume still covers user's trade amount")
         pass
    else:
         print("Notify user that selected order is not available anymore and make swap button inactive")
         break
```

or another way might be probably additional API RPC call like a `get_uuid_state <uuid>` which will allow receiving information on created not by user order availability / parms by uuid (not sure how good this idea is, cc @artemii235 )

 We've discussed same way on today's call if I remember correctly - @SylEze raised concern that it might be annoying for the user, but I think if write good warning it's much better than permanent swaps mismatch
We might improve algo above (e.g. automatic match under the hood re-created order with different uuid without user's need to manually select if the price is changed to the profitable side for the user

**Comment by Milerius** [comment]
> discovered that created issue on this matter in 2019 in mobile repo, cf: [KomodoPlatform/AtomicDEX-mobile#480](https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/480) cc @yurii-khi
> 
> order state change =
> a) order with selected price does not exist anymore (was matched fully and gone from orderbook, or LP re-created it with different price)
> b) volume of the order changed (was partially matched)
> 
> after the order is selected we can probably poll selected order state some way like this (that's just first/most straightforward idea came to mind, might be not optimal way.):
> 
> ```python
> selected_uuid = selected_order()["uuid"]
> amount_user_selling = swap_form.amount
> while True:
>     time.sleep(1)
>     pair_orderbook = get_orderbook(pair)
>     uuids_list = []
>     for order in pair_orderbook["bids"]: # or "asks"
>         uuids.append(order["uuid"])
>     # this check checking both a and b cases
>     # checking if initial order still in the orderbook and if volume still covers amount user want to sell/buy
>     if selected_uuid in uuids_list and pair_orderbook["bids"][selected_uuid]["volume"] <= amount_user_selling:
>          print("Order still there and volume still covers user's trade amount")
>          pass
>     else:
>          print("Notify user that selected order is not available anymore and make swap button inactive")
>          break
> ```
> 
> or another way might be probably additional API RPC call like a `get_uuid_state <uuid>` which will allow receiving information on created not by user order availability / parms by uuid (not sure how good this idea is, cc @artemii235 )
> 
> We've discussed same way on today's call if I remember correctly - @SylEze raised concern that it might be annoying for the user, but I think if write good warning it's much better than permanent swaps mismatch
> We might improve algo above (e.g. automatic match under the hood re-created order with different uuid without user's need to manually select if the price is changed to the profitable side for the user

Here is what I propose after using the two views this morning:

- If the order changes just the price but none of the volumes, update the price and display a checkbox for the user indicating that the price has changed, if the user does not check the checkbox he cannot start the swap, if the price changes again, we can uncheck the box
- If the order uuid no longer exists that means that the order has been matched or canceled, in this case I just propose a message + a reset form, if the user clicks on the message, the message disappears and he can choose a new order
- If the order volume changes and it no longer satisfies the user's wishes, we can also add a message for the user to choose:
    * Adjust its volume
    * Clear the forms so that the user can choose a new order

**Comment by Milerius** [comment]
Implemented
