### ISSUE TITLE
[Enhancement]: move notification button to the title bar with a ring bell icon 

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#972]
**Describe the enhancement**

The notification button no longer needs to be on the sidebar, but can be directly in the titlebar.

You can inspire from binance desktop app for the ringbell notification / approach

**Comment by smk762** [comment]
For example on Binance:
![image](https://user-images.githubusercontent.com/35845239/122758181-1526f200-d2cb-11eb-8789-477f026e668b.png)
![image](https://user-images.githubusercontent.com/35845239/122758258-2a038580-d2cb-11eb-8d12-d0fa3d9b32a5.png)
![image](https://user-images.githubusercontent.com/35845239/122758315-3c7dbf00-d2cb-11eb-930e-b8a9969c5395.png)
