### ISSUE TITLE
[BUG]: Using loader for every dex view (simple/pro/liquidity)

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#976]
**Describe the bug**

The loading of the dex tabs is too long, let's use loader to speedup loading time, on top of that specific modal that are only on the simple view appear on the pro view due to the complete load of both page

Actually this is super problematic, slow down our efficiency when working on those pages, need to be fixed asap

**To Reproduce**
1. Login to the app
2. Click on DEX
3. See behaviour

**Expected behavior**

Instant load of page (atleast after the first launch), no modal collision

**Comment by smk762** [comment]
https://user-images.githubusercontent.com/35845239/122670125-e5a4b680-d1f2-11eb-9393-5de581612b15.mp4


Looks good in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930

**Comment by Milerius** [comment]
solved

**Comment by smk762** [comment]
closing, can reopen if issue is sighted again.
