### ISSUE TITLE
[BUG]: title bar is out of range in full screen

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#977]
**Describe the bug**

look at the top left:
![image](https://user-images.githubusercontent.com/21139416/121768282-c906df80-cb5d-11eb-915a-240c446213d7.png)

**Comment by smk762** [comment]
Looks ok in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930

**Comment by smk762** [comment]
closing, can reopen if issue is sighted again.
