### ISSUE TITLE
[FEATURE REQUEST]: Add max button for simple trading view "From" amount

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#982]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889

**Comment by SylEze** [comment]
Any preference for position/visual looking ?

**Comment by tonymorony** [comment]
shared with ssakone earlier:

![image](https://user-images.githubusercontent.com/24797699/122086606-0f925d80-ce2e-11eb-9034-8b21a8f24f85.png)

should set max_taker_volume if an order is selected and max user balance if he doesn't select the order atm
also would be great to center elements relative to the amount

**Comment by SylEze** [comment]
Take a look at 77828c5706162640be93ef0418b3223dc2882875

**Comment by SylEze** [comment]
Beautify and more visual effects added to the button in 3c72d5f29a34258d18aef55e3ad5e2758c5dd75e

**Comment by Milerius** [comment]
Implemented
