### ISSUE TITLE
[BUG]: Not possible to select text for copy/delete and not possible to paste on simple trading view

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#984]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889

<img width="431" alt="Screenshot 2021-06-15 at 16 51 34" src="https://user-images.githubusercontent.com/24797699/122032759-228b3a80-cdfa-11eb-822b-445bdd0a082f.png">

**Comment by SylEze** [comment]
Can you retry on latest CI build of #889 please ? I can select/copy/cut/paste on my side.

**Comment by tonymorony** [comment]
@SylEze Can confirm it's on the latest CI build of #889, I'm on M1 Mac - maybe it makes the difference. I will check on Windows

**Comment by Milerius** [comment]
> @SylEze Can confirm it's on the latest CI build of #889, I'm on M1 Mac - maybe it makes the difference. I will check on Windows

I'm able to select/copy/paste only if i do command + A on my side

**Comment by SylEze** [comment]
Should be fixed in e776810639755eebd7764af2a223dce7626f98d2

**Comment by Milerius** [comment]
Implemented
