### ISSUE TITLE
[BUG]: Order selection with less volume than input amount shouldn't set amount to 0 but to max order volume

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#985]
E.g. I set From to 10 KMD, then select AXE order with 5.69 KMD max volume, at the moment it's set From to 0 but would be much better if it'll set it to 5.69

cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889

**Comment by smk762** [comment]
https://user-images.githubusercontent.com/35845239/122669841-ade93f00-d1f1-11eb-858e-f1ff8163b0d9.mp4
Looks ok in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930

**Comment by Milerius** [comment]
With the new binding to the backend property this problem cannot be forced anymore
