### ISSUE TITLE
QRC20 also needs fallback smart contract.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/atomicDEX-Desktop#989]
Excuse me, I've just noticed that the fallback is also required for all QRC20 tokens. It should be equal to the current swap_contract_address. Thanks!

**Comment by Milerius** [comment]
> Excuse me, I've just noticed that the fallback is also required for all QRC20 tokens. It should be equal to the current swap_contract_address. Thanks!

Hey @artemii235 thanks for the feedback it's not merged to dev yet but already implemented in: https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/d5ba7671c2769904b0410fb461cce53ed012fedc

Will close the issue after it's merged to dev, thanks for the feedback !

**Comment by Milerius** [comment]
Simple view is now merged to dev and include this fix, closing now.
