### ISSUE TITLE
[BUG]: Fees not loading sometimes on confirmation screen

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#990]
used build from a2b6561

Tested on M1 mac and windows

on pro view also reproducing but not so often as on simple view

video with reproduction:
https://drive.google.com/file/d/1p2hPSFu6dJ596ghDJfy7guQm63nw9264/view?usp=sharing

not found anything helpful in log

cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889

**Comment by smk762** [comment]
unable to replicate in linux so far in https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930.
Sighted in Windows ETH/DOGE didnt see fees at all. BEP/DOGE fees came up after a sec and then were in confirm screen.

**Comment by cipig** [comment]
if fee information is not cached by GUI or mm2, then it depends on the coin (fixed fee or dynamic fee) and on the configured electrum servers... dynamic fee coins need to get the fee, so they will likely call https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-estimatefee

**Comment by tonymorony** [comment]
> In [43f74b3](https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/43f74b38a5b58b17310d731c9a8763fc54ec7930).
> Sighted in Windows ETH/DOGE didnt see fees at all. BEP/DOGE fees came up after a sec and then were in confirm screen.
> Unable to replicate in linux so far (ERC / BEP ok)

i guess this https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/9b7cd1687b8bee05a67b70a1e400af33cac32930 commit might related to this issue

**Comment by Milerius** [comment]
<img width="1326" alt="Capture d’écran 2021-06-20 à 17 54 58" src="https://user-images.githubusercontent.com/21139416/122680666-a2494880-d1f0-11eb-87af-21f99ade4145.png">

<img width="1326" alt="Capture d’écran 2021-06-20 à 17 55 06" src="https://user-images.githubusercontent.com/21139416/122680671-a70dfc80-d1f0-11eb-8880-353bec70a0b5.png">

I fixed the bug yesterday

**Comment by Milerius** [comment]
I think it's solved, feel free to reopen if bug still occured

**Comment by tonymorony** [comment]
still persists on my side

**Comment by Milerius** [comment]
solved
